### ISSUE TITLE
skipIfTorchInductor Tracking Issue 

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#102207]
### 🐛 Describe the bug

We have a long list of known failures in test_torch.py. Some of these may be fixed, but because they are skipped we don't know. If you're working on an issue please tag yourself in the line.

./test/test_torch.py:
- [ ] 'test_scalar_check' - "segfaults"
- [ ] 'test_conv_transposed_backward_agnostic_to_memory_format' - "Please convert all Tensors to FakeTensors"

All the non deterministic tests are low pri, but it might be easy enough to fix
- [ ] 'test_nondeterministic_alert_AvgPool3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_AdaptiveAvgPool2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_AdaptiveAvgPool3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_MaxPool3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_AdaptiveMaxPool2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_FractionalMaxPool2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_FractionalMaxPool3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_interpolate_linear' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_interpolate_bilinear' - "aot-autograd issue"
- [ ] 'test_deterministic_interpolate_bilinear' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_interpolate_bicubic' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_interpolate_trilinear' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReflectionPad1d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReflectionPad2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReflectionPad3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReplicationPad1d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReplicationPad2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_ReplicationPad3d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_CTCLoss' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_EmbeddingBag_max' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_cumsum' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_put_accumulate' - "warning is logged from the FallbackKernel: torch.ops.aten.put_.default when warn_only=True"
- [ ] 'test_nondeterministic_alert_grid_sample_2d' - "aot-autograd issue"
- [ ] 'test_nondeterministic_alert_grid_sample_3d' - "aot-autograd issue"
- [ ] 'test_sync_warning' - "FIXME"
- [ ] 'test_copy_transpose_math_view' - "https://github.com/pytorch/pytorch/issues/98175"
- [ ] 'test_errors_index_copy' - "FIXME"
- [ ] 'test_scatter_reduce_non_unique_index' - "FIXME"
- [ ] 'test_dim_function_empty' - "RuntimeError: Trying to create tensor with negative dimension -1: [-1]"
- [ ] 'test_ternary_op_mem_overlap' - "FIXME"
- [ ] 'test_multinomial_device_constrain' - "out_wrapper does not check devices correctly"
- [ ] 'test_multinomial_gpu_device_constrain' - "out_wrapper does not check devices correctly"
- [ ] 'test_memory_format_propagation_rules' - "To be supported"
- [ ] 'test_memory_format_empty_like' - "To be supported"
- [ ] 'test_memory_format_operators' - "To be supported"
- [ ] 'test_pin_memory_from_constructor' - "pin_memory isn't yet supported in TorchInductor"
- [ ] 'test_memory_format_to' - "To be supported"
- [ ] 'test_memory_format_type' - "To be supported"
- [ ] 'test_memory_format_clone' - "To be supported"
- [ ] 'test_memory_format_factory_like_functions_preserve' - "To be supported"
- [ ] 'test_memory_format_type_shortcuts' - "To be supported"
- [ ] 'test_memory_format_cpu_and_cuda_ops' - "To be supported"
- [ ] 'test_hook_remove' - "FIXME"
- [ ] 'test_assertRaisesRegex_ignore_msg_non_native_device' - "random_.from needs to be renamed"
- [ ] 'test_advancedindex_mixed_cpu_devices' - "FIXME"
- [ ] 'test_advancedindex_mixed_devices_error' - "FIXME"
- [ ] 'test_index_add_correctness' - "AssertionError: RuntimeError not raised by <lambda>"
- [ ] 'test_typed_storage_deprecation_warning' - "FIXME"
- [ ] 'test_pin_memory' - "pin_memory isn't yet supported in TorchInductor"
- [ ] 'test_memory_format' - "To be supported"
- [ ] 'test_upsample_nearest2d_meta' - "https://github.com/pytorch/pytorch/issues/97414"
- [ ] 'test_copy_broadcast' - "FIXME"
- [ ] 'test_copy_many_to_one' - "FIXME"
- [ ] 'test_copy_float16' - "FIXME"
- [ ] 'test_to' - "FIXME"
- [ ] 'test_slice' - "FIXME"
./test/test_modules.py:
- [ ] 'test_cpu_gpu_parity' - "to be fixed"
- [ ] 'test_memory_format' - "to be fixed"
./test/test_ops.py:
- [ ] 'test_python_ref_meta' - "Takes too long for inductor" (skip or find way to run periodically)
- [ ] 'test_python_ref' - "Takes too long for inductor" (skip or find way to run periodically)
- [ ] 'test_python_ref_torch_fallback' - "Takes too long for inductor" (skip or find way to run periodically)
- [ ] 'test_python_ref_executor' - "Takes too long for inductor" (skip or find way to run periodically)
- [ ] 'test_python_ref_errors' - "Takes too long for inductor" (skip or find way to run periodically)
- [ ] 'test_out_warning' - "Inductor does not support complex dtype yet"
- [ ] 'test_out' - "Inductor does not support complex dtype yet"
- [ ] 'test_variant_consistency_eager' - "Inductor does not support complex dtype yet"
- [ ] 'test_complex_half_reference_testing' - "Inductor does not support complex dtype yet"
- [ ] 'test_non_standard_bool_values' - "Inductor does not support view with dtype yet"
- [ ] 'test_conj_view' - "Inductor does not support complex dtype yet"
- [ ] 'test_neg_view' - "Inductor does not support complex dtype yet"
- [ ] 'test_neg_conj_view' - "Inductor does not support complex dtype yet"
./test/test_ops_fwd_gradients.py:
- [ ] 'test_inplace_forward_mode_AD' - "to be fixed" (lower pri)

### Versions

master

**Comment by eellison** [comment]
Inductor has three different main lowering processes. 
1. Dynamo tracing 
2. AOT Autograd Tracing
3. Lowering to Inductor

Since these tests do not have a skipIfTorchDynamo test skip they already work with dynamo. 

First, I would see if the test fails with AOT Autograd. To do this run with `PYTORCH_TEST_WITH_AOT_EAGER=1`. If that fails, the likely source of the cause is a bad meta registration, decomp, or bug in fake_tensor. 

If that succeeds you can then test inductor with `PYTORCH_TEST_WITH_INDUCTOR=1`.

**Comment by abhinpt0** [comment]
I'd like to work on 'test_sync_warning' from this list. Is anyone else looking into this, or can I be assigned?

**Comment by abhiyushS** [comment]
Hi! I want to work on fixing the `test_sync_warning` skip from this tracking list.

I see this test is marked as "FIXME" and I'll follow the testing procedure outlined by @eellison:
1. First test with PYTORCH_TEST_WITH_AOT_EAGER=1
2. Then test with PYTORCH_TEST_WITH_INDUCTOR=1
3. Identify and fix the root cause

Is this test still needing work? I'm ready to investigate and submit a PR.

cc @eellison

**Comment by Arraddhyyad** [comment]
Hi! I'd like to work on test_copy_float16 from this list. I'll follow the testing procedure with AOT_EAGER first, then INDUCTOR, and open a draft PR once I identify the root cause. Is this still available?

**Comment by Tweezky66** [comment]
Hi @eellison ! if this is still availiable, i would like to work on "test_to", may i?

**Comment by Arraddhyyad** [comment]
Hi! Just wanted to clarify that I'm planning to work on test_copy_float16 specifically. I'll follow the testing procedure outlined by @eellison (AOT_EAGER first, then INDUCTOR) and open a draft PR once I've identified the root cause. Excited to contribute!
