### ISSUE TITLE
Export+AOTInductor issue tracker

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#105217]
Updated (October 23)

- 14K github models (72%) (https://github.com/jansel/pytorch-jit-paritybench)
  - [x] #111691
  - [ ] #111693
  - [ ] 153 errors like: AssertionError: Failed to produce a graph during tracing. Tracing through 'f' must produce a single graph. (example ./generated/test_lucidrains_imagen_pytorch.py:UpsampleCombiner # pytest ./generated/test_lucidrains_imagen_pytorch.py -k test_007) (https://github.com/pytorch/pytorch/issues/111254)
  - [ ] 130 errors like: AssertionError: Mutating module attribute min_val during export. (example ./generated/test_NVlabs_GroupViT.py:Transformer # pytest ./generated/test_NVlabs_GroupViT.py -k test_004) (https://github.com/pytorch/pytorch/issues/105530)
  - [ ] 81 errors like: AssertionError: original output # 2 is None, but only the following types are supported: (<class 'torch.Tensor'>, <class 'torch.SymInt'>, <class 'torch.SymFloat'>, <class 'torch.SymBool'>) (example ./generated/test_elbayadm_attn2d.py:GridGatedMAX # pytest ./generated/test_elbayadm_attn2d.py -k test_011) (https://github.com/pytorch/pytorch/issues/111250)
  - [ ] 75 errors like: Unsupported: setattr(UserDefinedObjectVariable) <function Module.__setattr__ at 0x7f61e53808b0> (example ./generated/test_XPixelGroup_BasicSR.py:SFTUpBlock # pytest ./generated/test_XPixelGroup_BasicSR.py -k test_029)
  - [ ] 68 errors like: Unsupported: call_function BuiltinVariable(setattr) [TensorVariable(), ConstantVariable(str), ConstantVariable(bool)] {} (example ./generated/test_cedias_Hierarchical_Sentiment.py:EmbedAttention # pytest ./generated/test_cedias_Hierarchical_Sentiment.py -k test_000)
  - [ ] 53 errors like: AssertionError: Dynamo attempts to add additional input during export: value=0.1767766952966369, source=NNModuleSource(base=AttrSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='wscale')), member='scale')) (example ./generated/test_open_mmlab_mmgeneration.py:FullyConnectedLayer # pytest ./generated/test_open_mmlab_mmgeneration.py -k test_015) (https://github.com/pytorch/pytorch/issues/111255)
  - [ ] 52 errors like: RuntimeError: Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow. (example ./generated/test_kuprel_min_dalle.py:AttentionBase # pytest ./generated/test_kuprel_min_dalle.py -k test_000)
  - [ ] 51 errors like: Unsupported: 'call_function Mish in skip_files Builtin Mish, filename is None' (example ./generated/test_ikostrikov_pytorch_a2c_ppo_acktr_gail.py:Categorical # pytest ./generated/test_ikostrikov_pytorch_a2c_ppo_acktr_gail.py -k test_001)
  - [ ] 46 errors like: UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands (example ./generated/test_maudzung_SFA3D.py:FocalLoss # pytest ./generated/test_maudzung_SFA3D.py -k test_001)
  - [x] #111830
  - [ ] 41 errors like: UserError: Tried to use data-dependent value in the subsequent computation. This can happen when we encounter unbounded dynamic value that is unknown during tracing time.You will need to explicitly give hint to the compiler. Please take a look at constrain_as_value OR constrain_as_size APIs (example ./generated/test_mdv3101_CDeCNet.py:GHMC # pytest ./generated/test_mdv3101_CDeCNet.py -k test_008) (https://github.com/pytorch/pytorch/issues/111252)
  - [x] #111818
  - [x] #111813
  - [x] #111711
  - [ ] 23 errors like: Unsupported: call_method NNModuleVariable() _get_backward_hooks [] {} (example ./generated/test_xheon_panoptic_reconstruction.py:InstanceNorm3d # pytest ./generated/test_xheon_panoptic_reconstruction.py -k test_011)

- Huggingface (passrate 91%)
  - [x] ~~#105242~~
  - [x] ~~“torch._dynamo.exc.InternalTorchDynamoError: 'str' object has no attribute 'size’”~~
  - [x] ~~XLNetLMHeadModel: #109655~~
  - [x] #110096

- TIMM (passrate 98%)
  - [x] ~~crossvit_9_240: fail_accuracy~~
  - [x]  ~~deit_base_distilled_patch16_224: fail_accuracy~~
  - [x]  ~~dla102: fail_accuracy~~
  - [x]  ~~dpn107: fail_accuracy~~
  - [x]  ~~levit_128: fail_accuracy~~
  - [x] ~~volo_d1_224: fail_accuracy~~
  - [x] ~~#105530~~
  - [x] ~~#108173~~
  - [ ] cait_m36_384: OOM on A100 40GB

- Torchbench (passrate 78%) (repro cmd: `python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --export-aot-inductor  --only  `)
  - [x] ~~Background_Matting: fail_accuracy~~
  - [x] ~~LearningToPaint: fail_accuracy~~
  - [x] ~~Super_SloMo: fail_accuracy~~
  - [x] ~~dcgan: fail_accuracy~~
  - [x] ~~nvidia_deeprecommender: fail_accuracy~~
  - [x] ~~pytorch_CycleGAN_and_pix2pix: fail_accuracy~~
  - [x] ~~pytorch_unet: fail_accuracy~~
  - [x] ~~#108697~~
  - [x] ~~#108699~~
- **Export/Dynamo problems:**
  - [ ] BERT_pytorch, llama, yolov3: Mutating module attribute during export, the same as https://github.com/pytorch/pytorch/issues/105530
  - [x] ~~#109894~~
  - [ ] #109884
  - [ ] #109885
  - [ ]  doctr_det_predictor: ERROR:common:call_method UserDefinedObjectVariable(morphologyEx) __call__ [TensorVariable(), ConstantVariable(int), NumpyNdarrayVariable()] {}
  - [x] #108698
  - [ ] drq: AssertionError: traced result #0 (<class 'torchbenchmark.models.drq.drqutils.SquashedNormal'>) is not among graph-captured outputs (<class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>, <class 'torch._subclasses.fake_tensor.FakeTensor'>) or original args (<class 'torch.Tensor'>)
  - [ ] hf_T5_generate: torch._dynamo.exc.Unsupported: call_function deepcopy in skip_files /opt/conda/envs/py_3.10/lib/python3.10/copy.py
  - [x] #109895
  - [ ] pyhpc_isoneutral_mixing: Found following user inputs located at [16, 17, 18, 19, 20, 21, 22] are mutated. This is currently banned in the aot_export workflow.
  - [ ] soft_actor_critic: ERROR: mismatch between eager output (<class 'torchbenchmark.models.soft_actor_critic.nets.SquashedNormal'>) and traced output (list of tensors)
  - [ ] timm_efficientdet: torch._subclasses.fake_tensor.UnsupportedOperatorException: torchvision.nms.default
  - [x] #105532
  - [ ] #105531
- **Inductor problems:**
  - [x] ~~clip, hf_BigBird: #109655~~
  - [x] #111227
  - [x] #110304
  - [x] #110089
- **DATA DEPENDENT (will be skipped):**
  - [ ] (HF) AllenaiLongformerBase: Control flow on data-dependent [here](https://github.com/huggingface/transformers/blob/0a55d9f7376f72ad3ff296d4249840021b03bcc4/src/transformers/models/longformer/modeling_longformer.py#L601)
  - [ ] cm3leon_generate: ERROR:common:Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow
  - [ ] detectron2_fcos_r_50_fpn: data-dependent error occurring on https://fburl.com/code/7x2ztpni (probably needs a constraint)
  - [ ] fastNLP_Bert: ERROR:common:Consider annotating your code using constrain_as_*(). It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is i0 + 2 > 512 (unhinted: i0 + 2 > 512).  Scroll up to see where each of these data-dependent accesses originally occurred.
  - [ ] hf_Longformer: torch._dynamo.exc.UserError: Consider annotating your code using constrain_as_*(). It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is Eq(i0, 1) (unhinted: Eq(i0, 1)).  Scroll up to see where each of these data-dependent accesses originally occurred.
  - [ ] hf_Reformer: torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow
  - [ ] opacus_cifar10: ERROR:common:Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow
RROR:common:Tried to use data-dependent value in the subsequent computation. This can happen when we encounter unbounded dynamic value that is unknown during tracing time.You will need to explicitly give hint to the compiler. Please take a look at constrain_as_value OR constrain_as_size APIs
  - [ ] speech_transformer: ERROR:common:Dynamic slicing on data-dependent value is not supported

**Comment by yanboliang** [comment]
We recently added the export pass rate at #104382, look like the number is consistent.

**Comment by desertfire** [comment]
> We recently added the export pass rate at #104382, looks like the number is consistent.

My understanding is we are measuring export+eager there, and here we are checking export+AOTInductor. Is there an existing issue tracking the HF export issue? If not, I can create one.

**Comment by yanboliang** [comment]
> My understanding is we are measuring export+eager there, and here we are checking export+AOTInductor. Is there an existing issue tracking the HF export issue? If not, I can create one.

Correct, I means they are consistent. I'm not sure if there is an issue. cc @zhxchen17

**Comment by zhxchen17** [comment]
@yanboliang @desertfire I remember there's an issue to support kwargs in torch.export() properly, which means if an HF model uses kwargs to input to the model then we just fail for now.

**Comment by zhxchen17** [comment]
cc @ydwu4 who's working on kwargs support rn.

**Comment by ydwu4** [comment]
I'm working on it now: see D47478481

**Comment by zhxchen17** [comment]
@desertfire @yanboliang no GH issue that I know of, already cced Yidi

**Comment by desertfire** [comment]
https://github.com/pytorch/pytorch/issues/105242 created

**Comment by desertfire** [comment]
[Latest dashboard result](https://hud.pytorch.org/benchmark/compilers?startTime=Wed%2C%2012%20Jul%202023%2013%3A24%3A35%20GMT&stopTime=Wed%2C%2019%20Jul%202023%2013%3A24%3A35%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&lBranch=gh/desertfire/196/head&lCommit=c40856aeea373b6b2e9db9a0581b6d5dde06e75c&rBranch=main&rCommit=603a777b096ba1d7a13813ff1a44db2c0826ec3b)

**Comment by angelayi** [comment]
Latest dashboard [result](https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2028%20Jul%202023%2005%3A02%3A20%20GMT&stopTime=Fri%2C%2004%20Aug%202023%2005%3A02%3A20%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&lBranch=angelayi/bench&lCommit=e35a655e59b2038c0395f972a1f567f862093d9c&rBranch=main&rCommit=3e5a52cedd2d586fc6cb40a73a098252b9edc2a1) after https://github.com/pytorch/pytorch/pull/106564

**Comment by chenyang78** [comment]
I will take the one below if nobody is looking at it. Thanks.

```
395 errors like: RuntimeError: expected inputs vector size to be 1, but got 3 (example ./generated/test_LoSealL_VideoSuperResolution.py:make_dense # pytest ./generated/test_LoSealL_VideoSuperResolution.py -k test_042)
```

**Comment by desertfire** [comment]
> I will take the one below if nobody is looking at it. Thanks.
> 
> ```
> 395 errors like: RuntimeError: expected inputs vector size to be 1, but got 3 (example ./generated/test_LoSealL_VideoSuperResolution.py:make_dense # pytest ./generated/test_LoSealL_VideoSuperResolution.py -k test_042)
> ```

SGTM, thanks! For repro, you can look into https://github.com/jansel/pytorch-jit-paritybench

**Comment by chenyang78** [comment]
Cannot repro 

```
"186 errors like: RuntimeError: AOTInductorModelContainerRun( model_container.get(), input_handles.data(), input_tensors.size(), output_handles.data(), output_handles.size(), stream_handle, proxy_executor_handle) API call failed at /home/binbao/.cache/torch_extensions/py310_cu121/aot_inductor/main.cpp, line 66 (example ./generated/test_black0017_MedicalZooPytorch.py:LUConv # pytest ./generated/test_black0017_MedicalZooPytorch.py -k test_021)
```

**Comment by chenyang78** [comment]
The one below is not reproducible:

```
395 errors like: RuntimeError: expected inputs vector size to be 1, but got 3 (example ./generated/test_LoSealL_VideoSuperResolution.py:make_dense # pytest ./generated/test_LoSealL_VideoSuperResolution.py -k test_042)
```

**Comment by chenyang78** [comment]
couldn't repro the error

```
272 errors like: CalledProcessError: Command '['/home/binbao/local/ccache/lib/gcc', '/tmp/tmpxdqjpkf7/main.c', '-O3', '-I/home/binbao/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/home/binbao/.conda/envs/pytorch-3.10/include/python3.10', '-I/tmp/tmpxdqjpkf7', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpxdqjpkf7/triton_poi_fused__native_batch_norm_legit_no_training__prelu_kernel_add_convolution_relu_sigmoid_15.cpython-310-x86_64-linux-gnu.so', '-L/lib64', '-L/lib64']' returned non-zero exit status 1. (example ./generated/test_zjunlp_KnowPrompt.py:BertAttention # pytest ./generated/test_zjunlp_KnowPrompt.py -k test_000)
```

**Comment by chenyang78** [comment]
failed to repro this:

```
174 errors like: AssertionError: graph-captured input # 2, of type <class 'torch.nn.parameter.Parameter'>, is not among original inputs of types: (<class 'torch.Tensor'>) (example ./generated/test_HypoX64_DeepMosaics.py:inconv # pytest ./generated/test_HypoX64_DeepMosaics.py -k test_024)
```

**Comment by chenyang78** [comment]
cannot reproduce this:

```
56 errors like: ValueError: tree_unflatten(values, spec): values has length 2 but the spec refers to a pytree that holds 1 items (*). (example ./generated/test_chou141253_FGVC_PIM.py:StdConv2d # pytest ./generated/test_chou141253_FGVC_PIM.py -k test_102)
```

**Comment by chenyang78** [comment]
couldn't reproduce:

```
49 errors like: RuntimeError: Internal Triton PTX codegen error: (example ./generated/test_yqyao_SSD_Pytorch.py:BasicBlock # pytest ./generated/test_yqyao_SSD_Pytorch.py -k test_000)
```

**Comment by bhack** [comment]
Is this still valid?
