### ISSUE TITLE
TorchInductor Hack-a-Day on July 19th

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#105328]
### Better Engineering
- [x] #105571
- [ ] #105572

### Unit test
- [ ] skipIfTorchInductor tracker: https://github.com/pytorch/pytorch/issues/102207
- [x] #105534

### AOTInductor
- [x] #105552
- [x] #105553
- [ ] #105554
- [ ] Support rand fallback, https://github.com/pytorch/pytorch/issues/103415
- [x] #105555

###  Decompositions (write decomp, verify that Inductor has good performance on them and fuses as expected):
- [x] #105556
- [x] #105557
- [x] #105558
- [x] #105559
- [ ] #105560
- [ ] #105561
- [ ] #105562
- [x] #105563
- [x] #105564
- [x] #105565
- [ ] #105566
- [ ] #105567
- [ ] #105568

### Decomposition optimizations
- [ ] Lowering matmuls to pointwise operators when they’re small or bandwidth bound (https://github.com/pytorch/pytorch/issues/103313) 
- [ ] #105569

### Lowering:
- [ ] #105570
aten.grid_sampler_2d_backward (investigate using decomposition for backward as well)
aten.avg_pool3d

### Performance:
- [ ] Improve concat fusion with matmuls,   https://github.com/pytorch/pytorch/issues/102804
- [ ] Do smarter layout planning with concatenate, https://github.com/pytorch/pytorch/issues/102805
- [ ] Do concatenate copies with a foreach kernel if applicable, https://github.com/pytorch/pytorch/issues/103475
- [ ] Pattern-match operators into foreach kernels
- [ ] Stop zero-ing out non-differentiable outputs in AOTAutograd, https://github.com/pytorch/pytorch/issues/104272 

### Compilation time
- [ ] `will_fusion_create_cycle` takes a long time  , https://github.com/pytorch/pytorch/issues/98467
