### ISSUE TITLE
test_torchinductor_opinfo tracker

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#105534]
https://github.com/pytorch/pytorch/blob/main/test/inductor/test_torchinductor_opinfo.py

### Single sample failures
   - [x] "__getitem__": {b8, f16, f32, f64, i32, i64},
   - [x] "__rdiv__": {b8, f16, f32, f64, i32, i64},
   - [x] "addr": {f16},
   - [x] "allclose": {f16, f32, f64},
   - [x] "angle": {f32, f64},
   - [x] "argwhere": {b8, f16, f32, f64, i32, i64},
   - [x] ("as_strided", "partial_views"): {b8, f16, f32, f64, i32, i64}, (intentionally not handled)
   - [x] "baddbmm": {f16},
   - [ ] "bernoulli": {f16, f32, f64},
   - [x] "bincount": {i32, i64},
   - [x] "bucketize": {b8, f16, f32, f64, i32, i64}, likely related to @davidberard98 / @aakhundov 's PRs
   - [ ] "cholesky": {f32, f64},
   - [x] "combinations": {b8, f16, f32, f64, i32, i64},
   - [x] "corrcoef": {f16, f32, f64, i32, i64},
   - [x] "cov": {f16, f32, f64, i32, i64},
   - [x] "equal": {b8, f16, f32, f64, i32, i64},
   - [x] "index_reduce": {f16, f32, f64}, @davidberard98 
   - [x] "istft": {f32, f64},

    # Unsupported: data dependent operator: aten._local_scalar_dense.default
   - [x] "item": {b8, f16, f32, f64, i32, i64}, https://github.com/pytorch/pytorch/pull/105480
   - [x] "linalg.eig": {f32, f64},
   - [x] "linalg.eigh": {f32, f64},
   - [x] "linalg.eigvals": {f32, f64},
   - [x] "linalg.eigvalsh": {f32, f64},
   - [x] "linalg.householder_product": {f32, f64},
   - [x] "linalg.lstsq": {f32, f64},
   - [x]  ("linalg.lstsq", "grad_oriented"): {f32, f64},
   - [x] "masked_scatter": {f16, f32, f64}, (@int3)
   - [x] "masked_select": {b8, f16, f32, f64, i32, i64},
   - [x]  ("max", "reduction_with_dim"): {b8}, https://github.com/pytorch/pytorch/pull/109264
   - [x]  ("min", "reduction_with_dim"): {b8}, https://github.com/pytorch/pytorch/pull/109264
   - [ ] "multinomial": {f16, f32, f64}, (@int3) -- needs test RNG issues to be fixed first
   - [x] "nn.functional.adaptive_avg_pool2d": {f16},
   - [x] "nn.functional.ctc_loss": {f32, f64},
   - [x] "nn.functional.grid_sample": {f16},
   - [x] "grid_sampler_2d": {f16},
   - [x] "nn.functional.gaussian_nll_loss": {f16, f32, f64},
   - [x] "nn.functional.one_hot": {i64},
   - [x] "nn.functional.rrelu": {f16, f32, f64}, (@masnesral)
   - [x] "nn.functional.triplet_margin_with_distance_loss": {f16, f32, f64, i32, i64},
   - [x] "nonzero": {b8, f16, f32, f64, i32, i64},
   - [ ] "normal": {f16, f32, f64},
   - [ ]  "normal", "number_mean": {f16, f32, f64},
   - [x] "polar": {f32, f64},
   - [x] "rand_like": {f16, f32, f64},
   - [x] "randint_like": {f16, f32, f64, i32, i64},
   - [x] "randint": {f16, f32, f64, i32, i64},
   - [x] "randn_like": {f16, f32, f64},
   - [x] "repeat_interleave": {b8, f16, f32, f64, i32, i64},  data-dependent output shape
   - [x] ("round", "decimals_3"): {f16},  Internal upcast in inductor causes different results
   - [x] ("scatter_reduce", "prod"): {f16, f32, f64},  -> see index_reduce, same issue
   - [x]  ("_segment_reduce", "lengths"): {f16, f32, f64}, https://github.com/pytorch/pytorch/pull/109359
   - [ ] "sparse.sampled_addmm": {f32, f64},
   - [x]    ("std_mean", "unbiased"): {f16}, https://github.com/pytorch/pytorch/pull/109081
   - [x] "stft": {f32, f64},
   - [x] "tensor_split": {b8, f16, f32, f64, i32, i64},
   - [ ] "to_sparse": {f16, f32, f64},
   - [ ] "_upsample_bilinear2d_aa": {f16, f32, f64},

    # AssertionError: Tensor-likes are not close!
   - [ ] "atanh": {f32},
   - [x] "cauchy": {f16, f32, f64},
   - [x] "exponential": {f16, f32, f64},
   - [x] "geometric": {f16, f32, f64, i32, i64},
      ("normal", "in_place"): {f16, f32, f64},
   - [x] "log_normal": {f16, f32, f64},
   - [x] "nanquantile": {f32, f64}, may be fixed by #109172
   - [x] "uniform": {f16, f32, f64},
   - [x] "unique": {b8, f16, f32, f64, i32, i64},
   - [x] "unique_consecutive": {b8, f16, f32, f64, i32, i64},
   - [x] "nn.functional.triplet_margin_loss": {f16},
   - [x] "pca_lowrank": {f32, f64}, 
   - [x] "svd_lowrank": {f32, f64},
   - [x] "svd": {f32, f64},
   - [ ] "resize_" : {b8, f16, f32, f64, i32, i64} 
   - [ ] "resize_as_":  {b8, f16, f32, f64, i32, i64} 
    # AssertionError: Scalars are not close!
   - [x] "nn.functional.soft_margin_loss": {f16},
   - [x] "fft.fft": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.fft2": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.fftn": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.hfft": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.hfft2": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.hfftn": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.ifft": {f16, f32, f64, b8, i32, i64},
   - [x] "fft.ifft2": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.ifftn": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.ihfft": {f16, f32, f64, b8, i32, i64},
   - [x] "fft.ihfft2": {f16, f32, f64, b8, i32, i64},
   - [x] "fft.ihfftn": {f16, f32, f64, b8, i32, i64},
   - [x] "fft.irfft": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.irfft2": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.irfftn": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.rfft": {f16, f32, f64, b8, i32, i64},
   - [x] "fft.rfft2": {b8, f16, f32, f64, i32, i64},
   - [x] "fft.rfftn": {b8, f16, f32, f64, i32, i64},
 
    # These return complex tensors
   - [x] "cdouble": {b8, i32, i64, f16, f32, f64},
   - [x] "cfloat": {b8, i32, i64, f16, f32, f64},
   - [x] "chalf": {b8, i32, i64, f16, f32, f64},
   - [x] "complex": {f16, f32, f64},

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by eellison** [comment]
Commenting a number of good starter opinfo failures:

Missing lowering/decomp:

test_comprehensive_normal_in_place_cuda_float64:
> MissingOperatorWithoutDecomp: missing lowering
  target: aten.normal_functional.default

test_comprehensive_multinomial_cuda_float16:
> MissingOperatorWithoutDecomp: missing lowering
  target: aten.multinomial.default
  
 Inductor bug:
 
 - test_comprehensive_uniform_cuda_float32

>     buf_sizes = [buf.get_layout().storage_size() for buf in buffers]
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
AttributeError: 'MultiOutputLayout' object has no attribute 'storage_size'

Missing meta function:

test_comprehensive__segment_reduce_lengths_cuda_float32:
> segment_reduce(): Expected all rows of lengths along axis to sum to data.size(lengths.dim()-1) when !unsafe

**Comment by mlazos** [comment]
@desertfire should I close this? not sure if you plan on handing out the rest of these tasks.

**Comment by desertfire** [comment]
Yes, let me close this one.

**Comment by eellison** [comment]
I still think is a good source of first issues, even if low-pri.. @dessertfire mind if we open again and label as such?

**Comment by desertfire** [comment]
> I still think is a good source of first issues, even if low-pri.. @dessertfire mind if we open again and label as such?

You made a good point, but I think someone needs to triage those and create separate issues labeling with first-good-issue. Otherwise, this is low signal.
