### ISSUE TITLE
Add type annotations to TorchInductor

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#105571]
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by khushi-411** [comment]
Hi,
I'd like to pick this up! I haven't worked on adding Type annotations from scratch. Working on this will be a fun and great learning experience.
Please let me know if I can work on this or not. It seems like there's some internal hackathon going on in the PyTorch team, as per title #105328. Just wanted to confirm if it's open to others :-)
Thanks!

**Comment by gmagogsfm** [comment]
@khushi-411  Yes it is open, feel free to assign it to yourself and submit a PR!

**Comment by khushi-411** [comment]
Thanks for confirming, @gmagogsfm :-) Here's the list of files I think we need to add type annotations. Please let me know if there is something else. Thanks!
#### `codegen/`
- [ ] common.py
- [ ] cpp.py
- [ ] triton.py
- [ ] triton_foreach.py
- [ ] triton_utils.py
- [ ] wrapper.py
#### `fx_passes/`
- [ ] freezing_patterns.py
- [ ] fuse_attention.py
- [ ] group_batch_fusion.py
- [ ] joint_graph.py
- [ ] mkldnn_fusion.py
- [ ] pad_mm.py
- [ ] post_grad.py
- [ ] pre_grad.py
- [ ] quantization.py
- [ ] replace_random.py
- [ ] split_cat.py
#### `kernel/`
- [ ] bmm.py
- [ ] conv.py
- [ ] mm.py
- [ ] mm_common.py
- [ ] mm_plus_mm.py
---
- [x] __init__.py
- [ ] autotune_process.py
- [ ] bounds.py
- [ ] codecache.py
- [ ] compile_fx.py
- [ ] config.py
- [ ] coordinate_descent_tuner.py
- [x] cuda_properties.py #105620
- [ ] cudagraph_trees.py
- [ ] debug.py
- [ ] decomposition.py
- [ ] exc.py
- [ ] freezing.py
- [ ] fx_utils.py
- [ ] graph.py
- [ ] hooks.py
- [x] index_propagation.py #105622
- [ ] inductor_prims.py
- [ ] ir.py
- [ ] lowering.py
- [ ] metrics.py
- [ ] optimize_indexing.py #105621
- [ ] pattern_indexing.py
- [ ] pattern_matcher.py
- [ ] scheduler.py #105600
- [ ] select_algorithm.py
- [ ] sizevars.py
- [ ] test_operations.py
- [ ] triton_helpers.py
- [ ] triton_heuristics.py
- [ ] utils.py
- [ ] virtualized.py
- [ ] wrapper_benchmark.py

**Comment by khushi-411** [comment]
Whoops found a similar issue, #105230

**Comment by eellison** [comment]
Closing as dupe
