### ISSUE TITLE
ONNX-FX based exporter documentation/tutorial topics for PyTorch 2.1

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#108268]
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/tutorials/issues/2543
- [ ] Tutorial: Using diagnostics to find and report bugs - https://github.com/pytorch/tutorials/pull/2586
- [x] Tutorial: Using dynamic shapes
- [x] Tutorial: Using fake tensor to export large scale models
- [x] [Tutorial: Register custom operators](https://microsoft.sharepoint.com/:w:/t/ONNX2/Ee7O0MS48bZEr7ENbFt35-sBQO5xJsgeuZY4f-CU-ltl3w?e=gLvas8)
- [ ] Deep dive: ONNX-FX architecture
- [ ] Deep dive: Design comparison with TorchScript-based ONNX exporter
- [ ] https://github.com/pytorch/pytorch/issues/108274
- [ ] https://github.com/pytorch/tutorials/issues/2552
```
