### ISSUE TITLE
[dynamo] Tracking: object identity

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111663]
### 🚀 The feature, motivation and pitch

This covers many things:
1. Tensor Identity
2. User objects identity - usual objects, enums, builtins??

Use cases
- [x] https://github.com/pytorch/pytorch/issues/111550
- [x] https://github.com/pytorch/pytorch/issues/111556

Tensor Aliasing Methods and Obstacles
- [x] https://github.com/pytorch/pytorch/issues/111585
- [x] https://github.com/pytorch/pytorch/issues/111649
- [x] https://github.com/pytorch/pytorch/issues/111544

Overall Obstacles and Discussion
- [x] https://github.com/pytorch/pytorch/issues/111542
- [ ] https://github.com/pytorch/pytorch/issues/111562 - not sure if we want to implement non-aliasing for general objects

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by zhxchen17** [comment]
Tagging this as low-pri since this is only a tracker.

**Comment by zhxchen17** [comment]
closing this due inactivity for 2 years. Feel free to reopen this if there's a need and we'll be happy to revisit this. thanks
