### ISSUE TITLE
[Tracking] torch.compile + ctx manager bugs

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112164]
### 🐛 Describe the bug

- [ ] FSDP, grad_enabled (InternLM) https://github.com/pytorch/pytorch/issues/111552
- [ ] FSDP, autocast (MosaicML Diffusers) https://github.com/pytorch/pytorch/issues/110797
- [ ] FSDP, autocast (LlamaForCausalLM) https://github.com/pytorch/pytorch/issues/111317
- [ ] DDP, autocast (elastic DDP) https://github.com/pytorch/pytorch/issues/111794

Likely the same root cause - improper ctx manager handling when splitting the graph

### Versions

main

**Comment by jon-chuang** [comment]
As for justification for 2:
I understand that FSDP depends on eager-mode hooks to execute communication primitives.

All I can think is whether there is some reliance of this eager-mode code on `autocast` and `set_grad_enabled`. 

While naively, it should not, as these global states should only affect compute and graph building, not communication, I have a suspicion that under certain conditions, they would.
