### ISSUE TITLE
[Tracking] Follow ups for itertools infinite iterators

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112532]
### 🚀 The feature, motivation and pitch

Follow ups (https://github.com/pytorch/pytorch/pull/110967):
- [x] make listiterator an IteratorVariable, define iterator integrations on base IteratorVariable where unspecialized https://github.com/pytorch/pytorch/pull/110967#discussion_r1356656469
    - Please make a new issue for this 
- [ ] ~explore integrating cpython itertools test suite https://github.com/pytorch/pytorch/pull/110967#discussion_r1358326402~
- [x] Use something other than `StopIteration` to handle iterator termination https://github.com/pytorch/pytorch/pull/110967#discussion_r1358336038
- [x] Add test case for consuming iterator simultaneously from two code points https://github.com/pytorch/pytorch/pull/110967/files#r1358325511

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by Sacharith** [comment]
Can I contribute to this?

**Comment by jon-chuang** [comment]
Sure, which one are you interested in?

**Comment by Sacharith** [comment]
> Sure, which one are you interested in? I think the last one is the easiest to get started.

I will start with the last one. Thank you!

**Comment by Sacharith** [comment]
> No, you have to add a test that consuming an iterator from two codepoints will give the right results. I.e. they both mutate the same iterator.

Okay, thank you!

**Comment by williamwen42** [comment]
All relevant checkboxes completed
