### ISSUE TITLE
Torchbench Training Failing Models Tracker

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#112881]
### 🐛 Describe the bug

Note: i'm not duplicating issues across backends. A failure with inductor will also occur with cudagraphs and dynamic, and a cudagraphs failure will occur with cudagraphs dynamic.

Default Inductor backend:

- [ ] vision_maskrcnn: eager two runs differ. this is a failure with the dashboard. 

Cudagraphs

- [x] dlrm: sparsity has fundamental incompatibility with cudagraphs (at least in training, could potentially work in inference). we should be skipping here. (@eellison) (no longer failing??)

Inductor Dynamic: deferring until https://github.com/pytorch/pytorch/issues/113063

- [ ] demucs
`2023-10-27T09:50:53.4971595Z ERROR:common:Constraints violated (L['streams'].size()[0])! For more information, run with TORCH_LOGS=dynamic.
2023-10-27T09:50:53.4975118Z   - Not all values of RelaxedUnspecConstraint(L['streams'].size()[0]) are valid because L['streams'].size()[0] was inferred to be a constant (4).`
- [x] hf_Whisper - could not repro. look into it further
- [ ] speech_transformer - `AssertionError: nothing in example_inputs had a dim with 32`  benchmarking script issue.
- [x] timm_efficientdet - could not repro failure. 

Max autotune 
 - [x] Moco (following all look like similar issues - @shunting314 doing initial investigation) `2023-10-29T10:15:51.4480270Z SingleProcess AUTOTUNE takes 4.6186 seconds
2023-10-29T10:16:01.3670831Z ERROR:common:CUDA error: an illegal memory access was encountered
2023-10-29T10:16:01.3673431Z CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2023-10-29T10:16:01.3674868Z For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`
- [x] resnet152 `2023-11-05T10:44:03.8415416Z ERROR:common:CUDA error: misaligned address
2023-11-05T10:44:03.8416523Z CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. (shunting314)
2023-11-05T10:44:03.8417688Z For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`
- [x] resnet50 `misaligned address` (couldn't repro locally, let's see if next max autotune run fixes) (shunting314)
- [x] mobilenet_v3_large `'FusedSchedulerNode' object has no attribute 'node'`

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by xmfan** [comment]
hf_Whisper should be fixed once we update torchbench pin past https://github.com/pytorch/benchmark/pull/1935

**Comment by shunting314** [comment]
For max-autotune failures, I think this has been fixed in the new triton revision https://github.com/pytorch/pytorch/pull/114772/files  

Here is a summary of what I have done

1. at the beginning, the issue is very flaky to repro. I only reproed sometimes for resnet50 and resnet152 but never for moco
2. I tried to add '--cold-start-latency' to force using a fresh cache. It helps but still sometimes I can not repro
3. I start to focus just on resnet50. The crash happens after a epilogue fused kernel: triton_tem_fused__native_batch_norm_legit_no_training_add_convolution_relu_10 . I tried to force max-autotune to only pick triton config appear in that kernel and skip aten matmul. This results in a very stable repro for resnet50
4. I send out PR https://github.com/pytorch/pytorch/pull/114809 to generate benchmark code for epilogue fused matmul so we can run the kernel directly rather than the model or wrapper (which will be much slower)
5. Here is the runnable script for the kernel: https://gist.github.com/shunting314/f8c3b18ac261254a02cd42b73b52e582 . Just to verify if the issue has been fixed in triton already, I installed the new triton pin. And it turns out yes, it has been fixed.
6. I tried both resnet50 and resnet152 on the new triton pin and they both succeed now. I'm more confident on the fix on resnet50 since I have a stable repro. But I'm less confident on resnet152 since maybe I just did not repro the issue. I didn't tried moco again since I didn't repro for moco at the beginning. But overall, it's likely that all the models has been fixed. We can revisit if we see failure again.

cc @eellison
