### ISSUE TITLE
Tracking: Dynamo Tracing Improvements

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112901]
### 🚀 The feature, motivation and pitch

- [ ] Tracing while restoring from checkpoint - Solution: allow graph breaking over _regions_, not just single instruction
    - [ ] Graph break in Try Except (blocker: cannot restore block stack) https://github.com/pytorch/pytorch/issues/112865
        - inline all instructions until block stack is exited (or at least until the _problematic part_ of the block stack is exited), create `resume_at` there
    - [ ] Graph break in loop https://github.com/pytorch/pytorch/issues/112824
        - detect end of natural loop, inline all instructions till end of natural loop, create `resume_at` at end of natural loop (dominator node  of natural loop).
    -  [ ] Optimization: - skip `resume_at` while no `torch.*` in https://github.com/pytorch/pytorch/issues/94652
- [ ] Graph breaking while inlining - we currently restore to base-level tx before compiling https://github.com/pytorch/pytorch/issues/111003
    - Requires proper restoration of stacks at all levels, including ferrying the graph outs back to the top-level function call (which can then be consumed as locals). 
- [ ] Cache calls to inline, guard, and reuse recorded graphs - https://github.com/pytorch/pytorch/issues/112303

There is also an interesting duality here:
1. if we can convert all `push_block_stack` and natural loops into inlined functions, then we can correctly delineate where they exit. 
2. Conversely, we want to treat inlined functions as though one does not need to retrace the function call stack. We already know where it exits.
3. If we can "hoist" loop bodies into closures i.e. inline functions, we can apply the same inline function cacheing optimizations to speed up tracing loops

### Alternatives

NIL

### Additional context

NIL

**Comment by StrongerXi** [comment]
Issue scrubbing. I'll leave this open. I think #94652 is the only one that's not really worked on.
