### ISSUE TITLE
[ONNX] Track dynamic shapes integration for torch.onnx.dynamo_export

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#113705]
### 🐛 Describe the bug

- [x] Add meaningful dynamic shapes tests to guard `ExportedProgram` exported in `torch.onnx.dynamo_export`
- [x] https://github.com/pytorch/pytorch/issues/114166

### Versions

main branch

```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/issues/114954
```

**Comment by thiagocrepaldi** [comment]
@titaiwangms I've reopened this assuming we are not done with dynamic shapes just yet. What do you think?

**Comment by titaiwangms** [comment]
> @titaiwangms I've reopened this assuming we are not done with dynamic shapes just yet. What do you think?

What else task you have on mind?

**Comment by thiagocrepaldi** [comment]
did we cover tests that include SymInt, SymFloat, etc? the files below have examples of several dynamic shape tests that we could see how they behave on our exporter

https://github.com/pytorch/pytorch/blob/main/test/test_dynamic_shapes.py
https://github.com/pytorch/pytorch/blob/main/test/export/test_export.py#L306
https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_dynamic_shapes.py  # This file may have the test reuse infra we discussed one of these days
https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_export.py

**Comment by titaiwangms** [comment]
We did. Sym family is covered already in exporting. I guess remaining task is only extending op consistency test, which also needs a big refactor to catch up what we have in onnx-script.
