### ISSUE TITLE
Tracking: Improve SymNode/Dynamic Shapes Logging

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113879]
### 🚀 The feature, motivation and pitch

- [ ] https://github.com/pytorch/pytorch/issues/113700
- [ ] https://github.com/pytorch/pytorch/issues/113379
- [ ] https://github.com/pytorch/pytorch/issues/113876

### Alternatives

NIL

### Additional context

NIL
