### ISSUE TITLE
Add dynamic shape tests for important models to guard against regression

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#114954]
Most of these models are already statically tested at `test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxFakeTensorWithOnnxRuntime`, but we need to dynamic dimensions and cover them in CI

```[tasklist]
### Tasks
- [ ] tiny gpt
- [ ] toy mlp
- [ ] huggingface_google_t5
- [ ] huggingface_openai_whisper
- [ ] huggingface_mosaicml_mpt
- [ ] huggingface_bigscience_bloom_560m
```
