### ISSUE TITLE
[ONNX] Support Modularization in exporting ExportedProgram 

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#117292]
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/pull/116910
- [ ] https://github.com/pytorch/pytorch/issues/116670
- [ ] https://github.com/pytorch/pytorch/issues/117893
- [ ] `UnflattenedModule` and `InterpretModule` rewrites the original nn.Module, so we lose module package source
- [ ] https://github.com/pytorch/pytorch/issues/117791
- [ ] UnflattenedModule/InterpretModule doesn't support recompile()
- [ ] https://github.com/pytorch/pytorch/issues/116914
- [ ] https://github.com/pytorch/pytorch/issues/117892
- [ ] https://github.com/pytorch/pytorch/pull/119498
```
