### ISSUE TITLE
Cpp-wrapper mode issue tracker

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#117363]
This is a tracker issue for solving problems hit when enabling cpp wrapper codegen for JITInductor.

# Phase 1
Enable the cpp-wrapper mode for more Inductor unit tests. Basically, the task is to extend https://github.com/pytorch/pytorch/blob/main/test/inductor/test_cuda_cpp_wrapper.py to more unit tests, and still use the same non-ABI-compatible mode. Here is a task of found problems:

- [ ] Mismatched function overload type, e.g. at::_ops::mul_Tensor::call should be at::_ops::mul_Scalar::call
- [ ] TypeError: 'NullHandler' object is not iterable
- [ ] TypeError: 'int' object is not subscriptable
- [ ] AssertionError: Tensor-likes are not close!
- [ ] KeyError: torch.complex128, KeyError: torch.complex32
- [ ] BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
