### ISSUE TITLE
[MPS] Tracking issue for ModuleInfo failures when enabling testing for `torch.float16`

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#119108]
### 🐛 Describe the bug

The following tests fail when I enable `torch.float16` ModuleInfo testing for MPS

#### Not specific to MPS (also fail on CPU and CUDA)
- [ ] `test_check_inplace_nn_CELU_mps_float16`
- [ ] `test_check_inplace_nn_ELU_mps_float16`

#### Errors with "error: input types 'tensor<f32>' and 'tensor<...f16>' are not broadcast compatible"
- [ ] `test_forward_nn_AvgPool2d_mps_float16`
- [ ] `test_forward_nn_BCELoss_mps_float16`
- [ ] `test_if_train_and_eval_modes_differ_nn_AvgPool2d_mps_float16`
- [ ] `test_if_train_and_eval_modes_differ_nn_BCELoss_mps_float16`
- [ ] `test_memory_format_nn_AvgPool2d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_AvgPool2d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_BCELoss_mps_float16`
- [ ] `test_pickle_nn_AvgPool2d_mps_float16`
- [ ] `test_pickle_nn_BCELoss_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_MSELoss_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_SmoothL1Loss_mps_float16`

#### Errors with "MPSNDArrayConvolutionA14.mm:3976: failed assertion `destination datatype must be fp32'"
- [ ] `test_memory_format_nn_Conv1d_mps_float16`
- [ ] `test_memory_format_nn_Conv2d_mps_float16`
- [ ] `test_memory_format_nn_ConvTranspose1d_mps_float16`
- [ ] `test_memory_format_nn_ConvTranspose2d_mps_float16`
- [ ] `test_memory_format_nn_LazyConv1d_mps_float16`
- [ ] `test_memory_format_nn_LazyConv2d_mps_float16`
- [ ] `test_memory_format_nn_LazyConvTranspose1d_mps_float16`
- [ ] `test_memory_format_nn_LazyConvTranspose2d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_Conv1d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_Conv2d_mps_float16 `
- [ ] `test_non_contiguous_tensors_nn_ConvTranspose1d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_ConvTranspose2d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_LazyConv1d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_LazyConv2d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_LazyConvTranspose1d_mps_float16`
- [ ] `test_non_contiguous_tensors_nn_LazyConvTranspose2d_mps_float16`

#### Tolerance errors
- [ ] `test_ forward_nn_Bilinear_mps_float16`
- [ ] `test_ forward_nn_GELU_mps_float16`
- [ ] `test_ forward_nn_LogSigmoid_mps_float16`
- [ ] `test_ forward_nn_MSELoss_mps_float16`
- [ ] `test_ forward_nn_NLLLoss_mps_float16`
- [ ] `test_ forward_nn_SoftMarginLoss_mps_float16`
- [ ] `test_ forward_nn_Softmax2d_mps_float16`

#### inf nan error
- [ ] `test_ forward_nn_LogSoftmax_mps_float16`

#### Incorrect output dtype? values for attribute 'dtype' do not match: torch.float16 != torch.float32.
- [ ] `test_ forward_nn_HuberLoss_mps_float16`

### Versions

main

**Comment by hvaara** [comment]
Fix proposal for `test_forward_nn_Bilinear_mps_float16` in #135434
