### ISSUE TITLE
Tracking issue for PT2 dashboard inference passrate

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#120146]
This issue tracks the PT2 dashboard inference pass rate (excluding dynamic shape and aot-inductor). The pass rate is already pretty high so the issue just list the failed models and track the progress of fixing them.

# TB

- [x] mnasnet1_0: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings . https://github.com/pytorch/pytorch/issues/120545
- [x] moco: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings . https://github.com/pytorch/pytorch/issues/120545
- [x] shufflenet_v2_x1_0: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings . https://github.com/pytorch/pytorch/issues/120545
- [x] hf_T5_generate: pass accuracy test but fail performance run in cudagraphs/inductor_max_autotune settings. https://github.com/pytorch/pytorch/issues/121989
- [x] vision_maskrcnn: fail with 'fail_to_run' in inductor_max_autotune/inductor_with_cudagraphs_freezing_autotune setting. https://github.com/pytorch/pytorch/pull/123008

# HF

- [x] GPT2ForSequenceClassification: fail with 'fail_accuracy' in default/cudagraphs/inductor_max_autotune settings . https://github.com/pytorch/pytorch/pull/120537 

**ALL HF Inference REACH 100% NOW**

# TIMM

- [x] adv_inception_v3: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings. https://github.com/pytorch/pytorch/issues/120545
- [x] botnet26t_256: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings. https://github.com/pytorch/pytorch/issues/120545
- [x] gluon_inception_v3: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings. https://github.com/pytorch/pytorch/issues/120545
- [x] selecsls42b: fail with 'fail_accuracy' in cudagraphs_freezing settings. https://github.com/pytorch/pytorch/issues/120545
- [x] swsl_resnext101_32x16d: fail with 'fail_accuracy' in cudagraphs_freezing/inductor_with_cudagraphs_freezing_autotune settings. https://github.com/pytorch/pytorch/issues/120545

**ALL TIMM inference REACH 100% NOW (aot-inductor not covered here)**

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @penguinwu @eellison

**Comment by IvanKobzarev** [comment]
Hi @shunting314 , doing issues scrapping, am I right that this issue is fixed and can be closed?

**Comment by shunting314** [comment]
Let me close this one. We have a label to track new regressions.
