### ISSUE TITLE
Release 2.3.1 validations checklist and cherry-picks

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#127441]
We need to make sure that:
- [x] CUDA
   - [x] pypi binaries with slimmed dependencies are usable in standard AWS containers (amazonlinux:2 regression in 1.13) - @PaliC 
   ```pip3 install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/test/cu121```
   - [x] pypi binaries with slimmed dependencies are usable with stock  Ubuntu-20.04: https://github.com/pytorch/pytorch/issues/91067 . Test: https://github.com/pytorch/builder/actions/runs/9288567412/job/25566399559
  - [x] Check cuda 1.12.1 update issue: https://github.com/pytorch/pytorch/issues/94772 with small wheels @huydhn (This is an old issue from way back to 2.1, so I wonder if we need to continue verifying it)
 - [x] `torch.compile`
    - [x] Basic test works (for example see test mentioned in https://github.com/openai/triton/pull/1176 ) in PyTorch docker container @atalman
    - [x] `torch.compile` raises an error if used on Windows. Test: https://github.com/pytorch/builder/actions/runs/9288567412/job/25566416999#step:9:566
    - [x] `torch.compile` works on 3.11 : Test: https://github.com/pytorch/builder/actions/runs/9288567412/job/25566394822#step:12:4126
  - MPS
    - [x] Resnet is usable out of the box (i.e. https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py passes for MPS device). Test: https://github.com/pytorch/builder/actions/runs/9288567412/job/25566422463
- [x] Validate docker release builds - @atalman

### Cherry-Picks to validate

 - [x] https://github.com/pytorch/pytorch/issues/124897 @atalman 
 - [ ]  https://github.com/pytorch/pytorch/issues/124922 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/121834 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/124907 @atalman
 - [x] https://github.com/pytorch/pytorch/issues/125135 @huydhn 
 - [x] https://github.com/pytorch/pytorch/issues/125109 @atalman 
 - [ ] https://github.com/pytorch/pytorch/issues/125094 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/124850 @huydhn (The issue is not yet fixed, I'm moving it to 2.4.0 milestone)
 - [x] https://github.com/pytorch/pytorch/issues/124868 @PaliC  - Repro: https://github.com/pytorch/pytorch/issues/124868#issuecomment-2075765045
 - [x] https://github.com/pytorch/pytorch/issues/123954 @huydhn 
 - [x] https://github.com/pytorch/pytorch/issues/124335 @huydhn 
 - [x] https://github.com/pytorch/pytorch/issues/119607 @huydhn 
 - [ ] https://github.com/pytorch/pytorch/pull/123407 @PaliC 
 - [x] https://github.com/pytorch/pytorch/pull/126147 @PaliC 
 - [x] https://github.com/pytorch/pytorch/pull/126957 @atalman 
 - [ ] https://github.com/pytorch/pytorch/pull/126557 @atalman 
 - [x] https://github.com/pytorch/pytorch/pull/126559 @huydhn 
 - [x] https://github.com/pytorch/pytorch/pull/126567 @PaliC 
 - [x] https://github.com/pytorch/pytorch/pull/127219 @PaliC 

### Versions

2.3.1

**Comment by huydhn** [comment]
We can close this one now that 2.3.1 release is out
