### ISSUE TITLE
AOTAutogradCache implementation

### ISSUE THREAD

**Issue by jamesjwu** [pytorch/pytorch#128234]
This is just an umbrella issue for me to keep track of ongoing work/TODOs for AOTAutogradCache.

PR stack: https://github.com/pytorch/pytorch/pull/126791

```[tasklist]
### Tasks
- [x] Land V0-1 of AOTAutogradCache PRs
- [x] Implement caching for cudagraphification: cudagraphs runs after FXGraphCache as a post compile step
- [x] Fix serialization bugs for OutputAliasTypes that have tensors (AOTAutogradTestWithCache.test_input_aliased_with_mutation_output_alias) (PR out)
- [x] Implement certain unknown node ops (AOTAutogradTestWithCache.test_inner_grad) (PR out)
- [ ] Improve cache to support multiple backwards for a single forward
- [x] Fix cache key generation using torch_key in fbcode
- [x] Test on small model from benchmark
- [x] Don't specialize on real tensor metadata when dynamic shapes are turned on (PR out)
- [x] Handle higher order ops/custom autograd functions
- [x] Double check shape guard behavior: tests
- [x] Minor optimizations for perf: don't run debug_str every time, calculate triton cache key at load time instead of compile time
- [x] AOTAutogradCache calls FXGraphCache post compile steps (i.e. cudagraphs) (PR out)
- [x] Handle ephemeral + nccl timeouts properly in AOTAutogradCache
- [x] Implement remote AOTAutogradCache
```

cc @ezyang @bdhirsh @anijain2305 @chauhang @zou3519

**Comment by bhack** [comment]
Can we still track `remote AOTAutogradCache` here?

**Comment by StrongerXi** [comment]
Doing old issue scrubbing, @jamesjwu is this still on your plate?

**Comment by masnesral** [comment]
> Doing old issue scrubbing

Looks like a tracking task. There are still a few things left I think so we can leave this open.
