### ISSUE TITLE
[ONNX][low pri] Move old (non-public) implementation into legacy/ and schedule for deprecation

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#129308]
This can wait
```[tasklist]
### Tasks
- [ ] torch/onnx/_internal/io_adapter.py
- [ ] torch/onnx/_internal/onnx_proto_utils.py
- [ ] torch/onnx/_internal/diagnostics
- [ ] torch/onnx/_internal/fx/op_validation.py
- [ ] torch/onnx/_internal/fx/serialization.py
- [ ] torch/onnx/_internal/fx/torch_export_graph_extractor.py
- [ ] torch/onnx/_internal/fx/decomposition_table.py
- [ ] torch/onnx/_internal/fx/decomposition_skip.py
- [ ] torch/onnx/_internal/fx/analysis/unsupported_nodes.py
- [ ] torch/onnx/_onnx_supported_ops.py
- [ ] torch/onnx/operators.py
- [ ] torch/onnx/verification.py
- [ ] torch/onnx/utils.py
```
