### ISSUE TITLE
TensorDict - torch.compile issue tracker

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#129668]
### 🐛 Describe the bug

This is the sack of errors / improvements that would be required for a near-full support of tensordict functionalities within compile (will add other issues if they pop up)

Thanks for the support team, I was pleasantly suprised that a a lot of the items I had in this list were already closed!

- [ ] https://github.com/pytorch/pytorch/issues/127173 
- [ ] https://github.com/pytorch/pytorch/issues/129658
- [ ] https://github.com/pytorch/pytorch/issues/129659
- [ ] https://github.com/pytorch/pytorch/issues/129660
- [ ] https://github.com/pytorch/pytorch/issues/129661
- [ ] https://github.com/pytorch/pytorch/issues/129664
- [ ] https://github.com/pytorch/pytorch/issues/129662
- [ ] https://github.com/pytorch/pytorch/issues/129665
- [ ] https://github.com/pytorch/pytorch/issues/129666
- [ ] https://github.com/pytorch/pytorch/issues/129667

cc @shagunsodhani @ezyang @albanD @lezcano @bdhirsh 

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240627
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec 4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mujoco-torch==0.1.0
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.5.0.dev20240627
[pip3] torchao==0.1
[pip3] torchaudio==2.4.0.dev20240627
[pip3] torchrl==0.4.0+7c0a7c8
[pip3] torchtext==0.18.0
[pip3] torchvision==0.20.0.dev20240627
[conda] Could not collect

**Comment by ignaciobartol** [comment]
Hi, I was reading [this comment](https://github.com/pytorch/tensordict/pull/789#discussion_r1622355807) on PR [#789](https://github.com/pytorch/tensordict/pull/789) in tensordict, that those could be good issuest to start learning about dynamo. Is any of them still open to work on it? Which one would be a first issue to start working on? @vmoens 

Thanks a lot!

**Comment by lezcano** [comment]
There is https://pytorch.org/docs/main/torch.compiler_dynamo_deepdive.html, but in general PyTorch maintainers do not have much time to onboard new contributors, so you should have to fend for yourself for the most of it. You should get PDB, pick an issue you think you can approach and try to solve it.

**Comment by ignaciobartol** [comment]
Thanks @lezcano! I will take a problem and start working on it then.
