### ISSUE TITLE
Drop Python 3.8 and 3.9 support (following NEP 29)

### ISSUE THREAD

**Issue by isuruf** [pytorch/pytorch#129805]
#74203 adopted [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) and the schedule says that Python 3.8 was dropped on Apr 14, 2023, and Python 3.9 a week ago
on Jun 22, 2024.

- #74203

Is there any issue with dropping these Python versions?

This can also help with unifying `numpy` versions in #128860.

- #128860

------

This can also help with the type annotation issue for #117449.

- #117449

1. When we drop Python 3.8, we can use generic type-alias which are added in Python 3.9.

    - [Generic TypeAlias (PEP 585)](https://peps.python.org/pep-0585): e.g. `typing.List[T] -> list[T]`, `typing.Dict[KT, VT] -> dict[KT, VT]`, `typing.Type[T] -> type[T]`.

    This allows us to remove lots of imports from `typing` and also resolve an issue commented on https://github.com/pytorch/pytorch/pull/129420#issue-2371257204.

    This migration is auto-fixable by `ruff` rule [non-pep585-annotation (UP006)](https://docs.astral.sh/ruff/rules/non-pep585-annotation) when we set `target-version` to `py39`.

2. When we drop Python 3.9, we can use union-type which is added in Python 3.10.

    - [Union Type (PEP 604)](https://peps.python.org/pep-0604): e.g. `Union[X, Y] -> X | Y`, `Optional[X] -> X | None`, `Optional[Union[X, Y]] -> X | Y | None`.

    This allows us to remove the import of `typing.Union` and `typing.Optional` and completely remove `from __future__ import annotations`.

    This migration is auto-fixable by `ruff` rule [non-pep604-annotation (UP007)](https://docs.astral.sh/ruff/rules/non-pep604-annotation) when we set `target-version` to `py310`.

------

```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/issues/128860
- [ ] https://github.com/pytorch/pytorch/issues/117449
- [ ] https://github.com/pytorch/pytorch/pull/129420
- [ ] https://github.com/pytorch/pytorch/pull/129419
- [ ] https://github.com/pytorch/pytorch/pull/129375
- [ ] https://github.com/pytorch/pytorch/pull/129376
```

cc @albanD @malfet

**Comment by XuehaiPan** [comment]
Tweaked the issue comment for better readability.

**Comment by albanD** [comment]
Hey!
I would be curious if you have any comment on https://github.com/pytorch/rfcs/pull/65 ?
This would delay the removal of 3.9 and for sure prevent dropping 3.10 later this year.

**Comment by albanD** [comment]
The policy change in the RFC was accepted so I'm going to close this issue for now as we can use https://github.com/pytorch/pytorch/issues/120718 for the 3.8 deprecation coming soon and we have a whole year for  3.9

@isuruf could you comment on that issue with the points above about improvements we can make once 3.8 is dropped?
