### ISSUE TITLE
Release 2.4.0 validations checklist and cherry-picks

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#130151]
### 🐛 Describe the bug

We need to make sure that:
- [ ] CUDA
   - [x] pypi binaries with slimmed dependencies are usable in standard AWS containers (amazonlinux:2 regression in 1.13) 
   ```pip3 install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/test/cu121``` @PaliC 
   - [x] pypi binaries with slimmed dependencies are usable with stock  Ubuntu-20.04: https://github.com/pytorch/pytorch/issues/91067 . Test: https://github.com/pytorch/builder/actions/runs/9878730185/job/27288617275
  - [ ] Check cuda 1.12.1 update issue: https://github.com/pytorch/pytorch/issues/94772 with small wheels  (This is an old issue from way back to 2.1, so I wonder if we need to continue verifying it) @PaliC 
 - [ ] `torch.compile`
    - [x] Basic test works (for example see test mentioned in https://github.com/openai/triton/pull/1176 ) in PyTorch docker container @atalman 
    - [x] `torch.compile` raises an error if used on Windows. Test: https://github.com/pytorch/builder/actions/runs/9878730185/job/27288640469#step:9:408
    - [x] `torch.compile` works on 3.11, 3.12 : Test: https://github.com/pytorch/builder/actions/runs/9878730185/job/27288615685#step:12:5163
  - MPS
    - [x] Resnet is usable out of the box (i.e. https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py passes for MPS device). Test: https://github.com/pytorch/builder/actions/runs/9878730185/job/27288648048
- [x] Validate docker release builds  @atalman  https://github.com/pytorch/builder/actions/runs/10084146628

### Cherry-Picks to validate

 - [x] https://github.com/pytorch/pytorch/issues/126385
 - [x] https://github.com/pytorch/pytorch/issues/124497
 - [x] https://github.com/pytorch/pytorch/issues/128819
 - [ ] https://github.com/pytorch/pytorch/issues/129310 
 - [x] https://github.com/pytorch/pytorch/issues/119989
 - [x] https://github.com/pytorch/pytorch/issues/118581
 - [x] https://github.com/pytorch/pytorch/issues/118122
 - [ ] https://github.com/pytorch/pytorch/issues/128756
 - [x] https://github.com/pytorch/pytorch/issues/125804
 - [x] https://github.com/pytorch/pytorch/issues/127995
 - [x] https://github.com/pytorch/pytorch/pull/128688
 - [x] https://github.com/pytorch/pytorch/issues/128535
 - [ ] https://github.com/pytorch/pytorch/pull/128455 - Can't repro see comment: https://github.com/pytorch/pytorch/pull/128455#issuecomment-2161775721
 - [ ] https://github.com/pytorch/pytorch/pull/128363 - don't know how to test
 - [x] https://github.com/pytorch/pytorch/issues/127821 (checked revert is part of the release branch)
 - [ ] https://github.com/pytorch/pytorch/issues/124732
 - [x] https://github.com/pytorch/pytorch/issues/126799
 - [x] https://github.com/pytorch/pytorch/issues/126871 
 - [x] https://github.com/pytorch/pytorch/issues/126769 

### Versions

2.4.0

**Comment by oraluben** [comment]
https://github.com/pytorch/pytorch/issues/128756 actually breaks building torch with older version of nccl, is that expected?
