### ISSUE TITLE
Release 2.4.1 validations checklist and cherry-picks

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#134694]
### 🐛 Describe the bug

Similar to: https://github.com/pytorch/pytorch/issues/130151

We need to make sure that:
- [ ] CUDA
   - [x] pypi binaries with slimmed dependencies are usable in standard AWS containers (amazonlinux:2 and 2023  regression in 1.13) 
   ```pip3 install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/test/cu121``` @PaliC 
   - [x] pypi binaries with slimmed dependencies are usable with stock  Ubuntu-20.04: https://github.com/pytorch/pytorch/issues/91067 .  @kit1980 
   
    Can not be installed with default pip, the workaround is `python -m pip install pip --upgrade --force`:
    

```
    pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/test/cpu
Looking in indexes: https://download.pytorch.org/whl/test/cpu
Collecting torch==2.4.1
  Downloading https://download.pytorch.org/whl/test/cpu/torch-2.4.1%2Bcpu-cp38-cp38-linux_x86_64.whl (194.9 MB)
     |████████████████████████████████| 194.9 MB 26 kB/s 
Collecting torchvision==0.19.1
  Downloading https://download.pytorch.org/whl/test/cpu/torchvision-0.19.1%2Bcpu-cp38-cp38-linux_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 824 kB/s 
Collecting torchaudio==2.4.1
  Downloading https://download.pytorch.org/whl/test/cpu/torchaudio-2.4.1%2Bcpu-cp38-cp38-linux_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 810 kB/s 
Collecting networkx
  Downloading https://download.pytorch.org/whl/test/networkx-3.2.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 40.9 MB/s 
ERROR: Package 'networkx' requires a different Python: 3.8.10 not in '>=3.9'
```

    
   
  - [x] Check cuda 1.12.1 update issue: https://github.com/pytorch/pytorch/issues/94772 with small wheels  (This is an old issue from way back to 2.1, so I wonder if we need to continue verifying it) @PaliC 
 - [ ] `torch.compile`
    - [x] Basic test works (for example see test mentioned in https://github.com/openai/triton/pull/1176 ) in PyTorch docker container @atalman 
    - [x] `torch.compile` raises an error if used on Windows. Test: https://github.com/pytorch/builder/actions/runs/10599520657/job/29374895248#step:9:465
    - [x] `torch.compile` works on 3.11, 3.12 : Test: https://github.com/pytorch/builder/actions/runs/10599520657/job/29374840087#step:12:3785
  - MPS
    - [x] Resnet is usable out of the box (i.e. https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py passes for MPS device). Test: https://github.com/pytorch/builder/actions/runs/10599520657/job/29374889847
- [x] Validate docker release builds  @atalman  https://github.com/pytorch/builder/actions/runs/10084146628

### Cherry-Picks to validate

 - [x] https://github.com/pytorch/pytorch/issues/132004 @jithunnair-amd 
 - [x] https://github.com/pytorch/pytorch/issues/131662
 - [x] https://github.com/pytorch/pytorch/issues/131958 @atalman
 - [x] https://github.com/pytorch/pytorch/issues/132032
 - [x] https://github.com/pytorch/pytorch/issues/133437 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/131864 @kit1980 
 - [x] https://github.com/pytorch/pytorch/pull/133331 @jithunnair-amd
 - [x] https://github.com/pytorch/pytorch/issues/134242 @PaliC 
 - [x] https://github.com/pytorch/pytorch/issues/131668 Covered by test: https://github.com/pytorch/builder/actions/runs/10599520657/job/29374911786#step:9:506
 - [x] https://github.com/pytorch/pytorch/issues/130619 @atalman 
 - [x] https://github.com/pytorch/pytorch/pull/133888 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/133520 @PaliC
 - [x] https://github.com/pytorch/pytorch/issues/132486 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/132103
 - [x] https://github.com/pytorch/pytorch/issues/130815 @kit1980 
 - [x] https://github.com/pytorch/pytorch/issues/128130 @atalman 
 - [x] https://github.com/pytorch/pytorch/pull/130026
 - [x] https://github.com/pytorch/pytorch/issues/130196 @kit1980
 - [x] https://github.com/pytorch/pytorch/issues/131070 @kit1980
 - [x] https://github.com/pytorch/pytorch/issues/130659 @kit1980
 - [x] https://github.com/pytorch/pytorch/issues/130658 @kit1980
 - [x] https://github.com/pytorch/pytorch/issues/130242 @malfet
 - [x] https://github.com/pytorch/pytorch/issues/127055  @atalman 
 - [x] https://github.com/pytorch/pytorch/pull/128753 @jithunnair-amd
 - [x] https://github.com/pytorch/pytorch/pull/129075 @malfet 
 - [x] https://github.com/pytorch/pytorch/issues/130201 @PaliC
 - [x] https://github.com/pytorch/pytorch/issues/130806 @jithunnair-amd
 - [x] https://github.com/pytorch/pytorch/issues/132971 @chuanqi129 
 - [x] https://github.com/pytorch/pytorch/issues/128084 @PaliC
 - [x] https://github.com/pytorch/pytorch/pull/134497 @atalman 

### Versions

2.4.1
