### ISSUE TITLE
Release 2.5.0 validations checklist and cherry-picks

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#137492]
Similar to: https://github.com/pytorch/pytorch/issues/134694

We need to make sure that:
- [x] Python 3.13 wheel validate @atalman
- [x] CUDA
  - [x] pypi binaries with slimmed dependencies are usable in standard AWS containers 2023  regression in 1.13. @kit1980 Verified on amazonlinux:2023:
                  dnf update
                  dnf -y install python3-pip
                  pip3 install torch==2.5.0 --index-url https://download.pytorch.org/whl/test/cu124
  - [x] Check cuda 1.12.1 update issue: https://github.com/pytorch/pytorch/issues/94772 with small wheels  (This is an old issue from way back to 2.1, so I wonder if we need to continue verifying it) @atalman 
 - [x] `torch.compile`
    - [x] Basic test works (for example see test mentioned in https://github.com/openai/triton/pull/1176 ) in PyTorch docker container @atalman 
    - [x] `torch.compile` raises an error if used on Windows. Test: https://github.com/pytorch/builder/actions/runs/11238619993/job/31243853359#step:9:469
    - [x] `torch.compile` works on 3.11, 3.12 : Test: https://github.com/pytorch/builder/actions/runs/11236853245/job/31237993839#step:12:3709
  - MPS
    - [x] Resnet is usable out of the box (i.e. https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py passes for MPS device). Test: https://github.com/pytorch/builder/actions/runs/11236853245/job/31238016293#step:9:437
- [x] Validate docker release builds  @atalman  https://github.com/pytorch/builder/actions/runs/10084146628

### Cherry-Picks to validate

 - [x] https://github.com/pytorch/pytorch/issues/133437 @atalman
 - [ ] https://github.com/pytorch/pytorch/pull/136903
 - [x] https://github.com/pytorch/pytorch/pull/135869 @jithunnair-amd 
 - [ ] https://github.com/pytorch/pytorch/issues/135778 @jithunnair-amd
 - [ ] https://github.com/pytorch/pytorch/issues/135020 
 - [x] https://github.com/pytorch/pytorch/issues/135880 @kit1980
 - [ ] https://github.com/pytorch/pytorch/issues/132134
 - [x] https://github.com/pytorch/pytorch/issues/131701 @jithunnair-amd 
 - [x] https://github.com/pytorch/pytorch/pull/136139 @jithunnair-amd 
 - [ ] https://github.com/pytorch/pytorch/pull/135964
 - [x] https://github.com/pytorch/pytorch/pull/136471 @kit1980 
 - [x] https://github.com/pytorch/pytorch/pull/136371
 - [x] https://github.com/pytorch/pytorch/issues/136151 @atalman 
 - [x] https://github.com/pytorch/pytorch/issues/136132 @atalman
 - [ ] https://github.com/pytorch/pytorch/pull/136162 
 - [x] https://github.com/pytorch/pytorch/issues/136134
 - [x] https://github.com/pytorch/pytorch/pull/135882
 - [x] https://github.com/pytorch/pytorch/pull/135786
 - [x] https://github.com/pytorch/pytorch/issues/135700
 - [x] https://github.com/pytorch/pytorch/issues/136134
 - [x] https://github.com/pytorch/pytorch/pull/135882
 - [x] https://github.com/pytorch/pytorch/pull/135786
 - [x] https://github.com/pytorch/pytorch/issues/135700
 - [x] https://github.com/pytorch/pytorch/pull/135512
 - [x] https://github.com/pytorch/pytorch/pull/135607
 - [x] https://github.com/pytorch/pytorch/pull/135591
 - [x] https://github.com/pytorch/pytorch/issues/135419
 - [x] https://github.com/pytorch/pytorch/pull/135594
 - [x] https://github.com/pytorch/pytorch/pull/135520
 - [x] https://github.com/pytorch/pytorch/issues/135223
 - [x] https://github.com/pytorch/pytorch/pull/135418
 - [x] https://github.com/pytorch/pytorch/pull/135399
 - [x] https://github.com/pytorch/pytorch/pull/135378
 - [x] https://github.com/pytorch/pytorch/pull/135180
 - [x] https://github.com/pytorch/pytorch/pull/135234 @kit1980 
 - [x] https://github.com/pytorch/pytorch/pull/134976
 - [x] https://github.com/pytorch/pytorch/issues/135183
 - [x] https://github.com/pytorch/pytorch/pull/135261
 - [x] https://github.com/pytorch/pytorch/issues/135182
 - [x] https://github.com/pytorch/pytorch/issues/134798 @kit1980
 - [x] https://github.com/pytorch/pytorch/pull/134032 @kit1980
 - [x] https://github.com/pytorch/pytorch/pull/134662
 - [x] https://github.com/pytorch/pytorch/issues/134678
 - [x] https://github.com/pytorch/pytorch/pull/134304
 - [x] https://github.com/pytorch/pytorch/issues/133377 @kit1980
 - [ ] https://github.com/pytorch/pytorch/pull/128922

### Versions

2.5.0
