### ISSUE TITLE
Replace magma-cuda dependency on `pytorch/conda-builder` Docker image 

### ISSUE THREAD

**Issue by afrittoli** [pytorch/pytorch#138909]
### 🚀 The feature, motivation and pitch

This is an initial step towards removing anaconda from PyTorch CD.
The [`magma-cuda` build](https://github.com/pytorch/builder/blob/main/.github/workflows/build-magma-linux.yml) today relies on the [`pytorch/conda-builder` container image](https://hub.docker.com/r/pytorch/conda-builder), which we would like to remove.

I created this issue here as its parent issues are in the pytorch/pytorch repo. 
Changes associated with this will mostly be in the `pytorch/build` repo and in minor proportion in this repo too.

### Additional context

Related to https://github.com/pytorch/pytorch/issues/138506 and https://github.com/pytorch/pytorch/issues/138696.
I plan to work on this myself.

Magma: https://icl.utk.edu/magma/, https://developer.nvidia.com/magma
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/issues/139397
- [x] Switch to manywheel-builder (optional) -> using manylinux-cuda base images
- [ ] https://github.com/pytorch/pytorch/issues/140538
- [ ] https://github.com/pytorch/pytorch/issues/140001
- [ ] https://github.com/pytorch/pytorch/issues/140212
```

**Comment by afrittoli** [comment]
The current build creates a `conda` package, which looks like:

```
➜ tree
.
├── channeldata.json
├── index.html
├── linux-64
│   ├── current_repodata.json
│   ├── current_repodata.json.bz2
│   ├── index.html
│   ├── magma-cuda126-2.6.1-1.tar.bz2
│   ├── repodata.json
│   ├── repodata.json.bz2
│   ├── repodata_from_packages.json
│   └── repodata_from_packages.json.bz2
└── noarch
    ├── current_repodata.json
    ├── current_repodata.json.bz2
    ├── index.html
    ├── repodata.json
    ├── repodata.json.bz2
    ├── repodata_from_packages.json
    └── repodata_from_packages.json.bz2
```

The root-level files and the content of `noarch` are all metadata for the conda package.
The compiled magma library is in `magma-cuda126-2.6.1-1.tar.bz2`.
The [`install_magma`](https://github.com/pytorch/pytorch/blob/f8a5b7170a322225ddfd8fd505d9270f21c72193/.ci/docker/common/install_magma.sh#L23) script fetches the package from `anaconda` via `curl` and extracts the `include` folder.

**Comment by afrittoli** [comment]
Will close once #140417 is merged

**Comment by afrittoli** [comment]
All tasks completed, closing now.
