### ISSUE TITLE
[RFC] Disable CMake find_library(libm) on Windows, and solve libm conflict to MSVC runtime lib(ucrt.lib).

### ISSUE THREAD

**Issue by xuhancn** [pytorch/pytorch#141946]
### 🚀 The feature, motivation and pitch

Original issue is https://github.com/pytorch/pytorch/issues/134989 
After debug work, I found that `libm` is not should exist on Windows. On Windows, Microsoft already provided math libraries in its runtime library. If we called find_library(libm) from CMake file on Windows, it should occurred `libm` math functions conflict to MSVC runtime lib(ucrt.lib).

### Solution:
Currently, I debugged and found `XNNPACK` and `sleef` called  find_library(libm) from their CMake files. So I submit PRs to them to add CMake build option to turn off find_library(libm).

**XNNPACK:**
1. I submitted PR to add build option to disable `libm`: https://github.com/google/XNNPACK/pull/7456, and it was accepted and merged.
2. I occurred some build issue on `static_assert`: https://github.com/google/XNNPACK/issues/7534, I worked with Google engineers and fixed it now: https://github.com/google/XNNPACK/issues/7534#issuecomment-2513677937 
3. We have a PyTorch PR to update `XNNPACK` and turn off `libm` on Windows: https://github.com/pytorch/pytorch/pull/141943

**Sleef:**
1. I have submitted PR to add build option to disable `libm`: https://github.com/shibatch/sleef/pull/603 , I still discuss with maintainer now.
2. We have a PyTorch PR to update `Sleef` and turn off `libm` on Windows: https://github.com/pytorch/pytorch/pull/142245

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/pull/142245
- [ ] https://github.com/pytorch/pytorch/pull/141943
- [ ] https://github.com/pytorch/pytorch/pull/144644
```

**Comment by xuhancn** [comment]
Hi @malfet could you please review this RFC and the related two PRs: 
1. https://github.com/pytorch/pytorch/pull/142245
2. https://github.com/pytorch/pytorch/pull/141943
Thanks.

**Comment by xuhancn** [comment]
Intel was tested 20250117 nightly build, and confirmed no performance regression occurred. Thanks for @mengfei25 's great work.

**Comment by xuhancn** [comment]
Close it by all PRs landed.
