### ISSUE TITLE
Port TH operators to Aten (umbrella issue)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24507]
Porting guide: https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

Example PR with porting of the adaptive_avg_pool2d: https://github.com/pytorch/pytorch/pull/14714

Example PR with porting of the point-wise operator `addcmul`: #22874

How to use TensorIterator (if needed): https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator

Notes:

- While porting operators please include `[namedtensor ci]` into commit message, it will start names propagation test.

Issues were automatically generated based on `legacy::` dispatch rules in `native_functions.yaml` and operators `cname` in `Declarations.cwrap`

### CUDA Ops

- [x] #24523 Migrate `_index_copy_` from the TH to Aten (CUDA)
- [x] #24526 Migrate `_mode` from the TH to Aten (CUDA)
- [x] #24527 Migrate `_multinomial_alias_draw` from the TH to Aten (CUDA)
- [x] #24528 Migrate `_multinomial_alias_setup` from the TH to Aten (CUDA)
- [x] #24543 Migrate `cholesky_inverse` from the TH to Aten (CUDA)
- [x] #24565 Migrate `fmod` and `fmod_` from the TH to Aten (CUDA)
- [x] #24569 Migrate `geqrf` from the TH to Aten (CUDA)
- [x] #24571 Migrate `glu` from the TH to Aten (CUDA)
- [x] #24572 Migrate `glu_backward` from the TH to Aten (CUDA)
- [x] #24577 Migrate `index_fill_` from the TH to Aten (CUDA)
- [x] #24590 Migrate `log_sigmoid_backward` from the TH to Aten (CUDA)
- [x] #24591 Migrate `log_sigmoid_forward` from the TH to Aten (CUDA)
- [x] #24592 Migrate `lstsq` from the TH to Aten (CUDA)
- [x] #24597 Migrate `mode` from the TH to Aten (CUDA)
- [x] #24600 Migrate `multi_margin_loss` from the TH to Aten (CUDA)
- [x] #24601 Migrate `multi_margin_loss_backward` from the TH to Aten (CUDA)
- [x] #24602 Migrate `multilabel_margin_loss_backward` from the TH to Aten (CUDA)
- [x] #24603 Migrate `multilabel_margin_loss_forward` from the TH to Aten (CUDA)
- [x] #24607 Migrate `nll_loss2d_backward` from the TH to Aten (CUDA)
- [x] #24608 Migrate `nll_loss2d_forward` from the TH to Aten (CUDA)
- [x] #24609 Migrate `nll_loss_backward` from the TH to Aten (CUDA)
- [x] #24610 Migrate `nll_loss_forward` from the TH to Aten (CUDA)
- [x] #24614 Migrate `put_` from the TH to Aten (CUDA)
- [x] #24616 Migrate `renorm` and `renorm_` from the TH to Aten (CUDA)
- [x] #24618 Migrate `rrelu_with_noise` and `rrelu_with_noise_` from the TH to Aten (CUDA)
- [x] #24625 Migrate `sigmoid_backward` from the TH to Aten (CUDA)
- [x] #24637 Migrate `sort` from the TH to Aten (CUDA)
- [x] #24640 Migrate `take` from the TH to Aten (CUDA)
- [x] #24643 Migrate `tanh_backward` from the TH to Aten (CUDA)
- [x] #24644 Migrate `thnn_conv2d_backward` from the TH to Aten (CUDA)
- [x] #24645 Migrate `thnn_conv2d_forward` from the TH to Aten (CUDA)
- [x] #24646 Migrate `thnn_conv_depthwise2d_backward` from the TH to Aten (CUDA)
- [x] #24647 Migrate `thnn_conv_depthwise2d_forward` from the TH to Aten (CUDA)
- [x] #24648 Migrate `topk` from the TH to Aten (CUDA)

- [x] #24519 Migrate `_addr` and `_addr_` from the TH to Aten (CUDA)
- [x] #24520 Migrate `_cat` from the TH to Aten (CUDA)
- [x] #24521 Migrate `_cumprod` from the TH to Aten (CUDA)
- [x] #24522 Migrate `_cumsum` from the TH to Aten (CUDA)
- [x] #24524 Migrate `_max` from the TH to Aten (CUDA)
- [x] #24525 Migrate `_min` from the TH to Aten (CUDA)
- [x] #24529 Migrate `_std` from the TH to Aten (CUDA)
- [x] #24530 Migrate `_var` from the TH to Aten (CUDA)
- [x] #24533 Migrate `addbmm` and `addbmm_` from the TH to Aten (CUDA)
- [x] #24534 Migrate `addmm` and `addmm_` from the TH to Aten (CUDA)
- [x] #24535 Migrate `addmv` and `addmv_` from the TH to Aten (CUDA)
- [x] #24536 Migrate `addr` and `addr_` from the TH to Aten (CUDA)
- [x] #24538 Migrate `atan` and `atan_` from the TH to Aten (CUDA)
- [x] #24539 Migrate `baddbmm` and `baddbmm_` from the TH to Aten (CUDA)
- [x] #24540 Migrate `binary_cross_entropy` from the TH to Aten (CUDA)
- [x] #24541 Migrate `binary_cross_entropy_backward` from the TH to Aten (CUDA)
- [x] #24544 Migrate `clamp` and `clamp_` from the TH to Aten (CUDA)
- [x] #24545 Migrate `cos` and `cos_` from the TH to Aten (CUDA)
- [x] #24546 Migrate `cosh` and `cosh_` from the TH to Aten (CUDA)
- [x] #24547 Migrate `cumprod` from the TH to Aten (CUDA)
- [x] #24548 Migrate `cumsum` from the TH to Aten (CUDA)
- [x] #24549 Migrate `diag` from the TH to Aten (CUDA)
- [x] #24551 Migrate `dist` from the TH to Aten (CUDA)
- [x] #24552 Migrate `dot` from the TH to Aten (CUDA)
- [x] #24553 Migrate `eig` from the TH to Aten (CUDA)
- [x] #24554 Migrate `elu` and `elu_` from the TH to Aten (CUDA)
- [x] #24555 Migrate `elu_backward` from the TH to Aten (CUDA)
- [x] #24557 Migrate `equal` from the TH to Aten (CUDA)
- [x] #24558 Migrate `erf` and `erf_` from the TH to Aten (CUDA)
- [x] #24559 Migrate `erfc` and `erfc_` from the TH to Aten (CUDA)
- [x] #24561 Migrate `exp` and `exp_` from the TH to Aten (CUDA)
- [x] #24567 Migrate `gather` from the TH to Aten (CUDA)
- [x] #24570 Migrate `ger` from the TH to Aten (CUDA)
- [x] #24574 Migrate `hardtanh` and `hardtanh_` from the TH to Aten (CUDA)
- [x] #24575 Migrate `hardtanh_backward` from the TH to Aten (CUDA)
- [x] #24576 Migrate `index_add_` from the TH to Aten (CUDA)
- [x] #24578 Migrate `index_select` from the TH to Aten (CUDA)
- [x] #24583 Migrate `leaky_relu` and `leaky_relu_` from the TH to Aten (CUDA)
- [x] #24584 Migrate `leaky_relu_backward` from the TH to Aten (CUDA)
- [x] #33054 Migrate `masked_select` from TH to Aten (CUDA)
- [x] #49542 Migrate `masked_scatter` from TH to Aten (CUDA)
- [x] #49543  Migrate `masked_fill` from TH to Aten (CUDA)
- [x] #24594 Migrate `max` from the TH to Aten (CUDA)
- [x] #24595 Migrate `min` from the TH to Aten (CUDA)
- [x] #24596 Migrate `mm` from the TH to Aten (CUDA)
- [x] #24605 Migrate `mv` from the TH to Aten (CUDA)
- [x] #24611 Migrate `nonzero` from the TH to Aten (CUDA)
- [x] #24615 Migrate `remainder` and `remainder_` from the TH to Aten (CUDA)
- [x] #24619 Migrate `rrelu_with_noise_backward` from the TH to Aten (CUDA)
- [x] #24621 Migrate `scatter` and `scatter_` from the TH to Aten (CUDA)
- [x] #24622 Migrate `scatter_add_` from the TH to Aten (CUDA)
- [x] #24623 Migrate `set_` from the TH to Aten (CUDA)
- [x] #24631 Migrate `soft_margin_loss` from the TH to Aten (CUDA)
- [x] #24632 Migrate `soft_margin_loss_backward` from the TH to Aten (CUDA)
- [x] #24633 Migrate `softplus` from the TH to Aten (CUDA)
- [x] #24634 Migrate `softplus_backward` from the TH to Aten (CUDA)
- [x] #24635 Migrate `softshrink` from the TH to Aten (CUDA)
- [x] #24636 Migrate `softshrink_backward` from the TH to Aten (CUDA)
- [x] #24639 Migrate `std` from the TH to Aten (CUDA)
- [x] #24641 Migrate `tan` and `tan_` from the TH to Aten (CUDA)
- [x] #24642 Migrate `tanh` and `tanh_` from the TH to Aten (CUDA)
- [x] #24649 Migrate `trace` from the TH to Aten (CUDA)
- [x] #24652 Migrate `var` from the TH to Aten (CUDA)

### CPU Ops

- [x] #24679 Migrate `_addmm` and `_addmm_` from the TH to Aten (CPU)
- [x] #24666 Migrate `_addr` and `_addr_` from the TH to Aten (CPU)
- [x] #24667 Migrate `_cat` from the TH to Aten (CPU)
- [x] #24668 Migrate `_cumprod` from the TH to Aten (CPU)
- [x] #24669 Migrate `_cumsum` from the TH to Aten (CPU)
- [x] #24670 Migrate `_index_copy_` from the TH to Aten (CPU)
- [x] #24671 Migrate `_max` from the TH to Aten (CPU)
- [x] #24672 Migrate `_min` from the TH to Aten (CPU)
- [x] #24673 Migrate `_mode` from the TH to Aten (CPU)
- [x] #24674 Migrate `_multinomial_alias_draw` from the TH to Aten (CPU)
- [x] #24675 Migrate `_multinomial_alias_setup` from the TH to Aten (CPU)
- [x] #24676 Migrate `_std` from the TH to Aten (CPU)
- [x] #24677 Migrate `_var` from the TH to Aten (CPU)
- [x] #24678 Migrate `addbmm` and `addbmm_` from the TH to Aten (CPU)
- [x] #24679 Migrate `addmm` and `addmm_` from the TH to Aten (CPU)
- [x] #24680 Migrate `addmv` and `addmv_` from the TH to Aten (CPU)
- [x] #24681 Migrate `addr` and `addr_` from the TH to Aten (CPU)
- [x] #24682 Migrate `binary_cross_entropy` from the TH to Aten (CPU)
- [x] #24683 Migrate `binary_cross_entropy_backward` from the TH to Aten (CPU)
- [x] #24684 Migrate `cauchy_` from the TH to Aten (CPU)
- [x] #24685 Migrate `cholesky_inverse` from the TH to Aten (CPU)
- [x] #24687 Migrate `cumprod` from the TH to Aten (CPU)
- [x] #24688 Migrate `cumsum` from the TH to Aten (CPU)
- [x] #24689 Migrate `diag` from the TH to Aten (CPU)
- [x] #24691 Migrate `dist` from the TH to Aten (CPU)
- [x] #24692 Migrate `dot` from the TH to Aten (CPU)
- [x] #24693 Migrate `eig` from the TH to Aten (CPU)
- [x] #24694 Migrate `elu` and `elu_` from the TH to Aten (CPU)
- [x] #24695 Migrate `elu_backward` from the TH to Aten (CPU)
- [x] #24697 Migrate `equal` from the TH to Aten (CPU)
- [x] #24699 Migrate `exponential_` from the TH to Aten (CPU)
- [x] #24701 Migrate `fmod` and `fmod_` from the TH to Aten (CPU)
- [x] #24702 Migrate `gather` from the TH to Aten (CPU)
- [x] #24704 Migrate `geometric_` from the TH to Aten (CPU)
- [x] #24705 Migrate `geqrf` from the TH to Aten (CPU)
- [x] #24706 Migrate `ger` from the TH to Aten (CPU)
- [x] #24707 Migrate `glu` from the TH to Aten (CPU)
- [x] #24708 Migrate `glu_backward` from the TH to Aten (CPU)
- [x] #24710 Migrate `hardtanh` and `hardtanh_` from the TH to Aten (CPU)
- [x] #24711 Migrate `hardtanh_backward` from the TH to Aten (CPU)
- [x] #24712 Migrate `histc` from the TH to Aten (CPU)
- [x] #24713 Migrate `index_add_` from the TH to Aten (CPU)
- [x] #24714 Migrate `index_fill_` from the TH to Aten (CPU)
- [x] #24715 Migrate `index_select` from the TH to Aten (CPU)
- [x] #24720 Migrate `leaky_relu` and `leaky_relu_` from the TH to Aten (CPU)
- [x] #24721 Migrate `leaky_relu_backward` from the TH to Aten (CPU)
- [x] #24723 Migrate `log_normal_` from the TH to Aten (CPU)
- [x] #24724 Migrate `log_sigmoid_backward` from the TH to Aten (CPU)
- [x] #24725 Migrate `log_sigmoid_forward` from the TH to Aten (CPU)
- [x] #24726 Migrate `lstsq` from the TH to Aten (CPU)
- [x] #33053 Migrate `masked_select` from TH to Aten (CPU)
- [x] #49541  Migrate `masked_scatter` from TH to Aten (CPU)
- [x] #24728 Migrate `max` from the TH to Aten (CPU)
- [x] #24729 Migrate `min` from the TH to Aten (CPU)
- [x] #24730 Migrate `mm` from the TH to Aten (CPU)
- [x] #24731 Migrate `mode` from the TH to Aten (CPU)
- [x] #24739 Migrate `mv` from the TH to Aten (CPU)
- [x] #24745 Migrate `nonzero` from the TH to Aten (CPU)
- [x] #24746 Migrate `normal` and `normal_` from the TH to Aten (CPU)
- [x] #24747 Migrate `orgqr` from the TH to Aten (CPU)
- [x] #24748 Migrate `ormqr` from the TH to Aten (CPU)
- [x] #24751 Migrate `put_` from the TH to Aten (CPU)
- [x] #24752 Migrate `random_` from the TH to Aten (CPU)
- [x] #24753 Migrate `remainder` and `remainder_` from the TH to Aten (CPU)
- [x] #24754 Migrate `renorm` and `renorm_` from the TH to Aten (CPU)
- [x] #24755 Migrate `rrelu_with_noise` and `rrelu_with_noise_` from the TH to Aten (CPU)
- [x] #24756 Migrate `rrelu_with_noise_backward` from the TH to Aten (CPU)
- [x] #24757 Migrate `scatter` and `scatter_` from the TH to Aten (CPU)
- [x] #24758 Migrate `scatter_add_` from the TH to Aten (CPU)
- [x] #24759 Migrate `set_` from the TH to Aten (CPU)
- [x] #24760 Migrate `sigmoid_backward` from the TH to Aten (CPU)
- [x] #24764 Migrate `soft_margin_loss` from the TH to Aten (CPU)
- [x] #24765 Migrate `soft_margin_loss_backward` from the TH to Aten (CPU)
- [x] #24766 Migrate `softplus` from the TH to Aten (CPU)
- [x] #24767 Migrate `softplus_backward` from the TH to Aten (CPU)
- [x] #24768 Migrate `softshrink` from the TH to Aten (CPU)
- [x] #24769 Migrate `softshrink_backward` from the TH to Aten (CPU)
- [x] #24770 Migrate `sort` from the TH to Aten (CPU)
- [x] #24771 Migrate `std` from the TH to Aten (CPU)
- [x] #24772 Migrate `take` from the TH to Aten (CPU)
- [x] #24773 Migrate `tanh_backward` from the TH to Aten (CPU)
- [x] #24779 Migrate `trace` from the TH to Aten (CPU)
- [x] #24781 Migrate `uniform_` from the TH to Aten (CPU)
- [x] #24782 Migrate `var` from the TH to Aten (CPU)

### Pointwise bit-ops

- [x] #24508 Migrate `__and__` from the TH to Aten (CUDA)
- [x] #24509 Migrate `__iand__` from the TH to Aten (CUDA)
- [x] #24510 Migrate `__ilshift__` from the TH to Aten (CUDA)
- [x] #24511 Migrate `__ior__` from the TH to Aten (CUDA)
- [x] #24512 Migrate `__irshift__` from the TH to Aten (CUDA)
- [x] #24514 Migrate `__lshift__` from the TH to Aten (CUDA)
- [x] #24515 Migrate `__or__` from the TH to Aten (CUDA)
- [x] #24516 Migrate `__rshift__` from the TH to Aten (CUDA)
- [x] #24655 Migrate `__and__` from the TH to Aten (CPU)
- [x] #24656 Migrate `__iand__` from the TH to Aten (CPU)
- [x] #24657 Migrate `__ilshift__` from the TH to Aten (CPU)
- [x] #24658 Migrate `__ior__` from the TH to Aten (CPU)
- [x] #24659 Migrate `__irshift__` from the TH to Aten (CPU)
- [x] #24661 Migrate `__lshift__` from the TH to Aten (CPU)
- [x] #24662 Migrate `__or__` from the TH to Aten (CPU)
- [x] #24663 Migrate `__rshift__` from the TH to Aten (CPU)

### Completed (2019-11-20) 

- [x] #24606 Migrate `ne` and `ne_` from the TH to Aten (CUDA)
- [x] #24740 Migrate `ne` and `ne_` from the TH to Aten (CPU)
- [x] #24573 Migrate `gt` and `gt_` from the TH to Aten (CUDA)
- [x] #24709 Migrate `gt` and `gt_` from the TH to Aten (CPU)
- [x] #24593 Migrate `lt` and `lt_` from the TH to Aten (CUDA)
- [x] #24727 Migrate `lt` and `lt_` from the TH to Aten (CPU)
- [x] #24556 Migrate `eq` and `eq_` from the TH to Aten (CUDA)
- [x] #24696 Migrate `eq` and `eq_` from the TH to Aten (CPU)
- [x] #24568 Migrate `ge` and `ge_` from the TH to Aten (CUDA)
- [x] #24703 Migrate `ge` and `ge_` from the TH to Aten (CPU)
- [x] #24582 Migrate `le` and `le_` from the TH to Aten (CUDA)
- [x] #24719 Migrate `le` and `le_` from the TH to Aten (CPU)
- [x] #24660 Migrate `__ixor__` from the TH to Aten (CPU)
- [x] #24517 Migrate `__xor__` from the TH to Aten (CUDA)
- [x] #24664 Migrate `__xor__` from the TH to Aten (CPU)
- [x] #24513 Migrate `__ixor__` from the TH to Aten (CUDA)
- [x] #24716 Migrate `is_set_to` from the TH to Aten (CPU)
- [x] #24717 Migrate `l1_loss` from the TH to Aten (CPU)
- [x] #24718 Migrate `l1_loss_backward` from the TH to Aten (CPU)
- [x] #24722 Migrate `lgamma` and `lgamma_` from the TH to Aten (CPU)
- [x] #24732 Migrate `mse_loss` from the TH to Aten (CPU)
- [x] #24733 Migrate `mse_loss_backward` from the TH to Aten (CPU)
- [x] #24734 Migrate `multi_margin_loss` from the TH to Aten (CPU)
- [x] #24735 Migrate `multi_margin_loss_backward` from the TH to Aten (CPU)
- [x] #24736 Migrate `multilabel_margin_loss_backward` from the TH to Aten (CPU)
- [x] #24737 Migrate `multilabel_margin_loss_forward` from the TH to Aten (CPU)
- [x] #24738 Migrate `multinomial` from the TH to Aten (CPU)
- [x] #24749 Migrate `polygamma` and `polygamma_` from the TH to Aten (CPU)
- [x] #24750 Migrate `pow` and `pow_` from the TH to Aten (CPU)
- [x] #24741 Migrate `nll_loss2d_backward` from the TH to Aten (CPU)
- [x] #24742 Migrate `nll_loss2d_forward` from the TH to Aten (CPU)
- [x] #24743 Migrate `nll_loss_backward` from the TH to Aten (CPU)
- [x] #24744 Migrate `nll_loss_forward` from the TH to Aten (CPU)
- [x] #24783 Migrate `zero_` from the TH to Aten (CPU)
- [x] #24780 Migrate `unfold` from the TH to Aten (CPU)
- [x] #24774 Migrate `thnn_conv2d_backward` from the TH to Aten (CPU)
- [x] #24775 Migrate `thnn_conv2d_forward` from the TH to Aten (CPU)
- [x] #24776 Migrate `thnn_conv3d_backward` from the TH to Aten (CPU)
- [x] #24777 Migrate `thnn_conv3d_forward` from the TH to Aten (CPU)
- [x] #24778 Migrate `topk` from the TH to Aten (CPU)
- [x] #24761 Migrate `sign` and `sign_` from the TH to Aten (CPU)
- [x] #24762 Migrate `smooth_l1_loss` from the TH to Aten (CPU)
- [x] #24763 Migrate `smooth_l1_loss_backward` from the TH to Aten (CPU)
- [x] #24690 Migrate `digamma` and `digamma_` from the TH to Aten (CPU)
- [x] #24698 Migrate `erfinv` and `erfinv_` from the TH to Aten (CPU)
- [x] #24700 Migrate `fill_` from the TH to Aten (CPU)
- [x] #24686 Migrate `clamp` and `clamp_` from the TH to Aten (CPU)
- [x] #24650 Migrate `trunc` and `trunc_` from the TH to Aten (CUDA)
- [x] #24651 Migrate `unfold` from the TH to Aten (CUDA)
- [x] #24638 Migrate `sqrt` and `sqrt_` from the TH to Aten (CUDA)
- [x] #24626 Migrate `sign` and `sign_` from the TH to Aten (CUDA)
- [x] #24627 Migrate `sin` and `sin_` from the TH to Aten (CUDA)
- [x] #24628 Migrate `sinh` and `sinh_` from the TH to Aten (CUDA)
- [x] #24629 Migrate `smooth_l1_loss` from the TH to Aten (CUDA)
- [x] #24630 Migrate `smooth_l1_loss_backward` from the TH to Aten (CUDA)
- [x] #24624 Migrate `sigmoid` and `sigmoid_` from the TH to Aten (CUDA)
- [x] #24653 Migrate `zero_` from the TH to Aten (CUDA)
- [x] #24531 Migrate `abs` and `abs_` from the TH to Aten (CUDA)
- [x] #24532 Migrate `acos` and `acos_` from the TH to Aten (CUDA)
- [x] #24518 Migrate `_addmm` and `_addmm_` from the TH to Aten (CUDA)
- [x] #24537 Migrate `asin` and `asin_` from the TH to Aten (CUDA)
- [x] #24542 Migrate `ceil` and `ceil_` from the TH to Aten (CUDA)
- [x] #24550 Migrate `digamma` and `digamma_` from the TH to Aten (CUDA)
- [x] #24566 Migrate `frac` and `frac_` from the TH to Aten (CUDA)
- [x] #24562 Migrate `expm1` and `expm1_` from the TH to Aten (CUDA)
- [x] #24563 Migrate `fill_` from the TH to Aten (CUDA)
- [x] #24564 Migrate `floor` and `floor_` from the TH to Aten (CUDA)
- [x] #24560 Migrate `erfinv` and `erfinv_` from the TH to Aten (CUDA)
- [x] #24579 Migrate `is_set_to` from the TH to Aten (CUDA)
- [x] #24580 Migrate `l1_loss` from the TH to Aten (CUDA)
- [x] #24581 Migrate `l1_loss_backward` from the TH to Aten (CUDA)
- [x] #24585 Migrate `lgamma` and `lgamma_` from the TH to Aten (CUDA)
- [x] #24586 Migrate `log` and `log_` from the TH to Aten (CUDA)
- [x] #24587 Migrate `log10` and `log10_` from the TH to Aten (CUDA)
- [x] #24588 Migrate `log1p` and `log1p_` from the TH to Aten (CUDA)
- [x] #24589 Migrate `log2` and `log2_` from the TH to Aten (CUDA)
- [x] #24598 Migrate `mse_loss` from the TH to Aten (CUDA)
- [x] #24599 Migrate `mse_loss_backward` from the TH to Aten (CUDA)
- [x] #24604 Migrate `multinomial` from the TH to Aten (CUDA)
- [x] #24612 Migrate `polygamma` and `polygamma_` from the TH to Aten (CUDA)
- [x] #24613 Migrate `pow` and `pow_` from the TH to Aten (CUDA)
- [x] #24617 Migrate `round` and `round_` from the TH to Aten (CUDA)
- [x] #24620 Migrate `rsqrt` and `rsqrt_` from the TH to Aten (CUDA)

**Comment by SsnL** [comment]
So... can we have this one issue instead of opening 275 new ones? It makes the issue viewer unreadable.

**Comment by VitalyFedyunin** [comment]
Having separate issues helps to track who is working on what (for example #24758) in other case this issue will become unreadable. 

And sorry I forgot to mention, all auto-generated issues have label "topic: porting" so anyone can filter out them in issue viewers.

**Comment by ezyang** [comment]
@VitalyFedyunin Do you know why `masked_select` wasn't in this list? I was looking for its porting issue (because it's used in printing) and I don't think we have one

**Comment by ezyang** [comment]
I added it, but given that it was missing, I'm wondering if there are other ops we are missing.

**Comment by VitalyFedyunin** [comment]
Looks like I missed manually aliased operators from pytorch/aten/src/ATen/native/LegacyDefinitions.cpp

**Comment by anjali411** [comment]
> I added it, but given that it was missing, I'm wondering if there are other ops we are missing.

Mmm just created issues for `masked_scatter` and `masked_fill` which were also missing from the list.

**Comment by rgommers** [comment]
The last open checkboxes were all done already. 280/280 ported, let's declare victory here 🎉
