### ISSUE TITLE
[DRAFT] Channels Last (NHWC) support plan.

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#28619]
Release goals:

- Support ResNet50, AlexNet, ResNeXt and proof performance gain on mixed precision models + Volta GPUs.
- Unlock developers to extend channels last operators coverage.

Tasks:

- [ ] Change factory functions (`_like` and similars) to optionally preserve format (#27979) and land with docs.
- [ ] Switch factory functions to preserve memory format by default (BC breaking) and fix all call sites (link tracking issue).
- [ ] Fix TensorIterator to preserve memory format  (#28291).
- [ ] Land CudNN changes to support channels last (#23861).
- [ ] Land `adaptive_avg_pool2d` (CUDA) changes to support channels last (#24396).
- [ ] Add `torch.memory_format` support to the TorchScript (#28544).
- [ ] Add model developer document how to check if model propagates NHWC forward and backward. Add documentation how to debug if model loosing channels last.
- [ ] Add TorchVision transformer and loader PRs (need to avoid additional memory copies on loading).
- [ ] Add developer docs how to write NHWC operators (https://github.com/pytorch/pytorch/wiki/Writing-memory-format-aware-operators)
- [ ] Add dev docs how to check if operator support memory formats.
- [ ] Documentation describing what is channels last, overlapping tensors, dense tensors, contiguous and when tensor can be both.
- [ ] Add channels last support to `cuda.comm.scatter` and `cuda.comm.gather` (#28077)

**Comment by thuyen** [comment]
@VitalyFedyunin will this be part of 1.4?

**Comment by VitalyFedyunin** [comment]
Unfortunately not, as we met few problems with CudNN and NC11 tensors, but expect it in master first month of 2020.

**Comment by thuyen** [comment]
Got it. Thanks!

**Comment by ketjow4** [comment]
Hey, @VitalyFedyunin  what is current status? What are your plans?

**Comment by VitalyFedyunin** [comment]
It is done in master and you can try using channels last for mixed precision training (for example https://github.com/NVIDIA/apex/pull/668). Documentation updates will follow soon.

**Comment by ketjow4** [comment]
Thanks for update @VitalyFedyunin. Will I be able to train model using single precision with NHWC data layout ? I am asking as I search for possibility of converting pytroch model through onnx to tensorflow. Is there any list of supported operators for NHWC training?

**Comment by codeislife99** [comment]
Hi, Which pytorch version will this update be a part of ?

**Comment by VitalyFedyunin** [comment]
It is out with 1.5 you can read more here https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html

**Comment by hreso110100** [comment]
Hi, is it possible to use this feature without cuda ? @VitalyFedyunin

**Comment by michele-arrival** [comment]
will the functional interface support this?

**Comment by constroy** [comment]
`torch.reshape` fails to keep the memory format when copy occurs.
Shall we unify the behavior regardless of copying or viewing?

#51558
