### ISSUE TITLE
Codegen refactoring tracking

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#30405]
This is the master task for all known codegen issues. The current state of our codegen is hard to maintain, it has a fair amount of bugs, hacks and hard coded logic which is not documented anywhere and requires a lot of domain knowledge. 

Known Issues:

- [ ] TensorOptions. Logic around TensorOptions manipulations is probably the hardest and the most confusing part of the whole codegen. In order to add a new entry to TensorOptions, one would have to make a big set of changes in pretty much every code gen script. It has to be refactored and cleaned up. 

- [ ] Some of the generated python bindings are wrong. As an example, take a look at `THPVariable_empty_like` or`THPVariable_randn_like` in python_torch_functions.cpp. For one of the overloads, `requires_grad` will be ignored due to wrong arg index.
```
>>> a = torch.ones(2, 3, requires_grad=True)
>>> print(torch.rand_like(a).requires_grad)
False
```

- [ ] Fix `requires_grad` logic. Ideally, `requires_grad` has to be added to all function in native_functions.yaml that have TensorOptions in it. Its not the case right now so there are many places in code gen that add `requires_grad` on a fly which adds significant complexity to overall logic 

- [ ] Fix default values processing. As an example, take a look at `tril_indices` / `triu_indices`, both have special logic around code gen to respect the default value.

- [ ] Add high level documentation which will describe what is being used as an input, what scripts are producing what and why. Without knowledge transfer or prior experience it takes a while to figure it all out.

**Comment by izdeby** [comment]
FYI, @bhosmer, @eellison, @gchanan, @smessmer    
This are the biggest issues that i have found while working on the TensorOptions clean up. I plan to fix them all one by one and this is the master tracking issue.
Please, feel free to add something that might be missing and/or you are working on.

**Comment by bhosmer** [comment]
High-level view of what I'm currently working on in the codegen pipeline. First couple are short-term, the rest somewhat longer.

- `gen_python_functions.py` refactor. This will probably happen over several PRs, first one here: https://github.com/pytorch/pytorch/pull/29986 (will land following @izdeby TensorOptions work lands). 

- `gen_jit_dispatch.py` work. Should substantially simplify signature processing, following suggestions from @cpuhrsch. His sketch here https://github.com/pytorch/pytorch/pull/30059 points the way.

- remove `Declarations.yaml` codegen step, will require a different approach to legacy declarations

- ultimate goal is to merge eager and JIT binding infra, and shift as much complexity as possible out of codegen

**Comment by eellison** [comment]
Also related: https://github.com/pytorch/pytorch/issues/30526

**Comment by ezyang** [comment]
> As an example, take a look at THPVariable_empty_like orTHPVariable_randn_like in python_torch_functions.cpp.

I'm not convinced your example is wrong. You have:

```
>>> a = torch.ones(2, 3, requires_grad=True)
>>> print(torch.rand_like(a).requires_grad)
False
```

But I don't see why the `requires_grad=True` field here should propagate. `rands_like(a)` doesn't depend on the data of `a` at all, so there's no requires grad relationship here in the sense of, we need to record autograd history. And in general, we don't create leaf variables (aka parameters) unless the user explicitly asked for it, because in general, the user should ask for every trainable parameter. This is similar situation to `pin_memory`: `_like` functions have historically not respected if the input tensor was pinned or not. The contract for `_like` is just that it preserves device, layout, dtype and size.

**Comment by ezyang** [comment]
> Look into how TensorOptions behaves when dtype is not set and the call to .dtype() is made. you get the current default dtype, which is questionable. 

Do you have a proposal for how to structure the logic differently?

**Comment by fmassa** [comment]
If I were to write a new language binding to PyTorch (scala / rust / etc), would it make sense to use codegen for it?

If yes, would it make sense to refactor the codegen so that it might make it easier to add new language backends?

**Comment by gchanan** [comment]
> remove Declarations.yaml codegen step, will require a different approach to legacy declarations

@bhosmer: what does this mean exactly?

**Comment by izdeby** [comment]
Related issue: [Move options logic in _like functions from parsing layer to implementations](https://github.com/pytorch/pytorch/issues/28093#event-2890531784)

**Comment by bhosmer** [comment]
> > remove Declarations.yaml codegen step, will require a different approach to legacy declarations
> 
> @bhosmer: what does this mean exactly?

@gchanan this was my high level, nearly content-free summary of your idea that we simplify the main pipeline by no longer muxing the Declarations.yaml items through it. I don't have any concrete plans at the moment - not sure it's the highest priority since it doesn't so much make the current codegen more complicated as it does pin it to a particular strategy (where the right C++ local names are available, etc.)

**Comment by bhosmer** [comment]
> If I were to write a new language binding to PyTorch (scala / rust / etc), would it make sense to use codegen for it?

@fmassa Hi Francisco - the hope is that we can move to a single piece of machinery for unfolding bindings from ops, and that might be a codegen pipeline that's pretty different from today's (or potentially no codegen at all). So I'd say the best bet is to hold off until a new setup has stabilized (moving to it will be a multistep process, ofc).
