### ISSUE TITLE
TensorIterator unrolling and vectorized load for GPU loop

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31975]
# Introduction

Unrolling and vectorized memory access is beneficial for bandwidth bound kernels, and it is becoming more important. We need unrolling and vectorized memory access to achieve great performance.

# Current status of gpu loop

The current design of gpu loop (simplified) works as follows:

```c++
template<int nt, int vt, typename func_t>
__global__ void elementwise_kernel(int N, func_t f) {
  int tid = threadIdx.x;
  int nv = nt * vt;
  int idx = nv * blockIdx.x + tid;
  #pragma unroll
  for (int i = 0; i < vt; i++) {
    if (idx < N) {
      // inside f, the address of data is computed, the data is loaded,
      // the computation is done and data is stored back to memory.
      f(idx);
      idx += nt;
    }
  }
}

void gpu_kernel(TensorIterator& iter, const func_t& f) {
  elementwise_kernel<nt, vt, func_t><<<grid, block, 0, stream>>>(N, [=]GPU_LAMBDA(int idx) {
    arg0_t* out = (arg0_t*)(data[0] + strides[0] * idx);
    *out = f(data[1] + strides[1] * idx, data[2] + strides[2] * idx, ...);
  });
}

void add_kernel_cuda(TensorIterator& iter) {
  gpu_kernel(iter, []GPU_LAMBDA(thrust_t a, thrust_t b) -> thrust_t {
    return a + b;
  });
}
```

The schedule is controlled by `elementwise_kernel` while all the memory access is done inside a lambda that `elementwise_kernel` have no knowledge about. And inside the lambda, it does the fetch, compute and store of only a single element. Unfortunately, this design is not very friendly to implementing vectorized load. I am planning to refactor it as the following while doing the work:

```c++
__global__ void elementwise_kernel(func_t f, data, strides) {
  #pragma unroll
  compute addresses

  #pragma unroll
  data loading, maybe vectorize

  #pragma unroll
  compute f(...)

  #pragma unroll
  store results
}
```

this new design would allow us to easily control data loading and storing.

# The plan

- [x] **Step 0**: Move old code to a new namespace `legacy`, and all new code will go to `modern`. These two namespaces will coexist for a while and eventually, both of them will go away as we merge them. (#31974)
- [x] **Step 1**: Write new codes for the case of trivial 1d contiguous problem, supporting unroll. (#31974)
- [x] **Step 2**: Refactor the code in step 1 to do vectorized load and store (#32383).
- [x] **Step 3**: Get rid of unnecessary dynamic casting (#32755).
- [x] **Step 4**: Legacy code cleanup -- `gpu_kernel_with_index` (#32777).
- [x] **Step 5**: Migrate `torch.where` to TensorIterator (#32984).
- [x] **Step 6**: Support the case where arguments do not have the same dtype (#33553).
- [x] **Step 7**: Remove `gpu_kernel_with_index` (#33370).
- [x] **Step 8**: Template argument cleanup (#33308).
- [ ] **Step 9**: Make ELU great again (#33244).
- [ ] **Step ..N**: Not planned in detail yet 

cc @VitalyFedyunin @ngimel @mruberry

**Comment by zasdfgbnm** [comment]
reserved for myself

**Comment by zasdfgbnm** [comment]
reserved for myself

**Comment by zasdfgbnm** [comment]
reserved for myself

**Comment by zasdfgbnm** [comment]
reserved for myself

**Comment by pyotr777** [comment]
I am experiencing a huge slowdown of a CNN training on small mini-batch sizes caused by elementwise_kernels. Will the update @zasdfgbnm is working on fix this issue?

These kernels are called on optimizer updates: optimizer.zero_grad() and optimizer.step(). I suppose they are responsible for the model weight updates.

Below is the aggregated time of the CUDA kernels of one epoch of the CNN training. The first two kernels — number 0 and 1 — are elementwise_kernel. On smaller mini-batch sizes they take about a half of the epoch time. 
 
![logs_kernels_epochtime_range0-100](https://user-images.githubusercontent.com/485462/78657698-21ac6e00-7904-11ea-8e9a-9fe78a5bdff7.png)

**Comment by zasdfgbnm** [comment]
@pyotr777 Which PyTorch version are you using? The latest PyTorch should not have an `at::native::elementwise_kernel`, there should be only `at::native::legacy::elementwise_kernel`

**Comment by pyotr777** [comment]
@zasdfgbnm 
Its 1.4.0.

**Comment by zasdfgbnm** [comment]
@pyotr777 OK, could you try nightly build? If this is still a problem, could you open a separate issue for this? The problem you described does not seem to be related to this issue.

**Comment by pyotr777** [comment]
@zasdfgbnm OK, I'll do that.

**Comment by zasdfgbnm** [comment]
@pyotr777 Thanks!

**Comment by pyotr777** [comment]
Created a new issue: #36638 .

**Comment by zasdfgbnm** [comment]
fixed
