### ISSUE TITLE
TorchScript C++ API Tracking Issue

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#32511]
Things we need to clean up in the TorchScript C++ API

## 🚀 Feature
- [ ] torch::save and torch::load should work on both C++ serialized models and data created from torch.save/toch.load
- [ ] Simple constructors for Tuple, List, and Dict in the torch namespace `torch::Tuple(<vector of Ivalues>)`, `torch::List(std::vector<T>)`, etc. should work as expected
- [ ] Header file reorganization to make it clearer what is part of the public API (e.g. torch.h should contain declarations for things implemented in the torch:: namespace).

@suo @driazati

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
