### ISSUE TITLE
Autograd speed-up task tracker

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#3275]
This is to track the remaining items for speeding up autograd by moving the `Variable` functions to ATen/C++

### Variable

- [x] type conversions (e.g. `Variable.cuda()`)
- [x] contiguous has strange behavior (modifies Variable in-place) and some tests depend on this
- [x] indexing operations (`__getitem__`, `__setitem__`)
- [x] speed-up norm_backward
- [ ] fix set_
- [x] fix fill_
- [x] clamp
- [x] matmul
- [x] renorm
- [x] select
- [x] var & std
- [x] random-sampling (non-differentiable)

### NN functions:

- [ ] Embedding
- [x] PReLU
- [x] Upsample
- [x] ReplicationPad

### Low-priority Variable methods

At minimum they need to be implemented on `VariableType.cpp` as non-differentiable functions. `variable.py` can override the methods with the current differentiable versions.

- [x] cumprod
- [x] cumsum
- [x] prod

**Comment by colesbury** [comment]
This is done, at least from the performance perspective.
