### ISSUE TITLE
0.3 release checklist

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3649]
- [x] backport some of the recent master commits
  - some of them were marked 0.3 release blockers, went into master
- [x] finish 0.3 blockers
- [x] port over linker version script to the 0.3 branch
- [x] add linker version script for TH, THNN, THC, THCUNN, THD (right now only _C is covered and that's not enough).
- [x] install devtoolset3 inside the conda docker too (anaconda now moved over to gcc 7.xx which is not CUDA compatible
  - [x] adjust meta.yaml files to remove libgcc and gcc entries
- [x] fix the numpy version to be used when building binaries (See https://github.com/pytorch/pytorch/issues/2564)
  - [x] change conda meta.yaml
  - [x] change the manylinux shell script recipe
- [ ] (maybe) build static fPIC openmp and link against that instead (requires recompiling gcc from source)
  - this will fix the static TLS issues that people have been seeing, but it's a bit of a high-risk of being a rabbit-hole
- [x] change the manylinux docker image to have cudnn7 and nccl2 and cuda9
- [x] change the conda docker image to have cudnn7 and nccl2
- [x] change the hashes for `patchelf` commands in the [manywheel build script](https://github.com/pytorch/builder/blob/master/manywheel/build.sh#L124) for cudnn, nccl2 and openmp
- [x] add a cuda90 tracking feature for conda (similar to cuda75 and cuda80)
- [x] build final wheels that are manylinux1 compatible
- [x] build final conda packages (and stage them at `-c pytorch` for testing)
- [x] test final binaries against [community repos](https://github.com/pytorch/builder/tree/master/test_community_repos) and do basic smoke tests
- [x] do basic performance and memory regression testing
  - word language model
    - [x] speed
    - [x] memory
  - imagenet
    - [x] speed
    - [x] memory
  - https://github.com/pytorch/benchmark
    - [ ] speed
    - [ ] memory
- [x] manually test final binaries in CPU-only AWS instances
   - cuda75 wheels
   - cuda80 wheels
   - cuda90 wheels
   - cuda75 conda
   - cuda80 conda
   - cuda90 conda
- [x] manually test final binaries in GPU AWS instances with only NVIDIA driver installed
   - cuda75 wheels
   - cuda80 wheels
   - cuda90 wheels
   - cuda75 conda
   - cuda80 conda
   - cuda90 conda
- [x] Write release notes

**Comment by Stonesjtu** [comment]
Any notes (features, performance improvements) on the coming release?

**Comment by fmassa** [comment]
@Stonesjtu I believe release notes will come with the release, stay tuned!

**Comment by aluo-x** [comment]
Master branch is also building on Windows with [CUDA 8](https://github.com/pytorch/pytorch/issues/494#issuecomment-343822103), CPU only, and [CPU w/ MKL](https://github.com/pytorch/pytorch/issues/494#issuecomment-343647348). Any chance we'll see windows support 0.3.0?

**Comment by soumith** [comment]
sorry andrew, official windows support is planned for 0.4.0 only. Testing on a new OS takes a lot of time, building and getting it into a working state is not enough.

**Comment by aluo-x** [comment]
Good to know!
