### ISSUE TITLE
[JIT] to-backend follow-up issues

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#37841]
The purpose of this issue is to track follow-ups from #35833 that need to be addressed. The PR is already pretty large and I want to land it first and incrementally improve it. The list of follow-ups is:

- [x] move functions that are not supposed to be user-visible out of `torch/csrc/jit/backends/backend.h` and into `detail` namespace or different file (#38567)
- [x] remove the parameter that was added to `addAttribute` in `aten/src/ATen/core/jit_type.h` to allow `Any` type module attributes (#38893)
- [x] add serialization and deserialization support (#38893)
- [x] move non-templated code from `torch/csrc/jit/backends/backend.h` to a `.cpp` (#38567)
- [ ] move test backend to test code (#38837)
- [ ] add an additional test to make sure things work if the lowered module is a submodule of a regular scriptmodule
- [ ] figure out how to support type refinement for container types in the generated code for `execute`
- [x] generate the `LoweredModule` in the Python compilation unit, and properly mangle the class name to avoid strange behavior when there is more than one `LoweredModule` defined at a time (#38679)
- [ ] finalize the PyTorchBackendInterface API/naming for external sharing

cc @suo

**Comment by SplitInfinity** [comment]
cc: @suo 

If someone comes across this while oncall, please note that it does not need to be triaged or addressed at triage review.

**Comment by SplitInfinity** [comment]
Closing because I've created a GitHub project to track this as well as individual issues for all the followups.
