### ISSUE TITLE
NumPy-like Functionality Request Rollup

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#38349]
PyTorch often receives requests for [NumPy](https://numpy.org/)-like functionality. This issue is a "rollup" of these requests. It will be continue to be updated with additional requests and helpful links for implementing them.

Newer contributors, checkout the [Wiki](https://github.com/pytorch/pytorch/wiki) and read the [Contribution Guide](https://pytorch.org/docs/stable/community/contribution_guide.html) for help getting started. 

If one of these issues requires additional discussion then, to avoid cluttering this rollup, please create a new issue titled “Implementing [Request]”, label it with “module: numpy”, and start the more focused discussion there. 

**Functions (Updated for the PyTorch 1.8 release):**

- [ ] [divmod](https://numpy.org/doc/1.18/reference/generated/numpy.divmod.html?highlight=divmod#numpy.divmod) (reserved for onboarding)
- [x] [frexp](https://numpy.org/doc/stable/reference/generated/numpy.frexp.html#numpy.frexp)
- [x] [dsplit](https://numpy.org/doc/1.18/reference/generated/numpy.dsplit.html?highlight=dsplit#numpy.dsplit), [hsplit](https://numpy.org/doc/1.18/reference/generated/numpy.hsplit.html?highlight=hsplit#numpy.hsplit), and [vsplit](https://numpy.org/doc/1.18/reference/generated/numpy.vsplit.html?highlight=vsplit#numpy.vsplit)
- [ ] [block](https://numpy.org/doc/stable/reference/generated/numpy.block.html?highlight=block#numpy.block)
- [ ] [diag_indices](https://numpy.org/doc/stable/reference/generated/numpy.diag_indices.html?highlight=diag_indices#numpy.diag_indices)
- [x] [take_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html?highlight=take_along_axis#numpy.take_along_axis)
- [x] [histogram](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html?highlight=histogram#numpy.histogram)
- [ ] [histogram_bin_edges](https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html#numpy.histogram_bin_edges)
- [x] [isin](https://numpy.org/doc/stable/reference/generated/numpy.isin.html)(https://github.com/pytorch/pytorch/issues/3025) (reserved for bootcamp)
- [x] let clamp accept tensors (https://github.com/pytorch/pytorch/issues/2793)
- [x] [corrcoef](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html?highlight=corrcoef#numpy.corrcoef), requested in https://github.com/pytorch/pytorch/issues/1254

**Completed Functions**
- [x] [diff](https://numpy.org/doc/stable/reference/generated/numpy.diff.html?highlight=diff#numpy.diff), implemented by @soulitzer in https://github.com/pytorch/pytorch/pull/50569
- [x] [any](https://numpy.org/doc/stable/reference/generated/numpy.any.html) and [all](https://numpy.org/doc/stable/reference/generated/numpy.all.html) supporting all dtypes, implemented by @kshitij12345 in https://github.com/pytorch/pytorch/pull/44790
- [x] [broadcast_to](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html?highlight=broadcast_to#numpy.broadcast_to), implemented by @RockingJavaBean in https://github.com/pytorch/pytorch/pull/48997
- [x] [xlogy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.xlogy.html), see original issue https://github.com/pytorch/pytorch/issues/22656, implemented by @kshitij12345 in https://github.com/pytorch/pytorch/pull/48777
- [x] [floatpower](https://numpy.org/doc/stable/reference/generated/numpy.float_power.html?highlight=float_power#numpy.float_power), implemented by @Kiyosora in https://github.com/pytorch/pytorch/pull/44937
- [x] [msort](https://numpy.org/doc/stable/reference/generated/numpy.msort.html?highlight=msort#numpy.msort), added by @Kiyosora in https://github.com/pytorch/pytorch/pull/48440
- [x] [ldexp](https://numpy.org/doc/stable/reference/generated/numpy.ldexp.html?highlight=ldexp#numpy.ldexp), added by @ranman in https://github.com/pytorch/pytorch/pull/45370
- [x] [column_stack](https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html?highlight=column_stack) and [row_stack](https://numpy.org/doc/stable/reference/generated/numpy.ma.row_stack.html?highlight=row_stack), implemented by @RockingJavaBean in https://github.com/pytorch/pytorch/pull/46313
- [x] [kron](https://numpy.org/doc/stable/reference/generated/numpy.kron.html?highlight=kron#numpy.kron), implemented by @IvanYashchuk in https://github.com/pytorch/pytorch/pull/45358
- [x] [ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html?highlight=ravel#numpy.ravel), implemented by @ejguan in https://github.com/pytorch/pytorch/pull/46098
- [x] [swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html?highlight=swapaxes#numpy.swapaxes), implemented by @kshitij12345 in https://github.com/pytorch/pytorch/pull/46041
- [x] [tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html?highlight=tile#numpy.tile), implemented by @arbfay in https://github.com/pytorch/pytorch/pull/47974
- [x] [copysign](https://numpy.org/doc/stable/reference/generated/numpy.copysign.html?highlight=copysign#numpy.copysign), implemented by @ejguan in https://github.com/pytorch/pytorch/pull/46396
- [x] [maximum](https://numpy.org/doc/1.18/reference/generated/numpy.maximum.html?highlight=maximum#numpy.maximum), [minimum](https://numpy.org/doc/1.18/reference/generated/numpy.minimum.html) implemented by @RockingJavaBean in https://github.com/pytorch/pytorch/pull/42579
- [x]  [dstack](https://numpy.org/doc/1.18/reference/generated/numpy.dstack.html?highlight=dstack), [hstack](https://numpy.org/doc/1.18/reference/generated/numpy.hstack.html?highlight=hstack#numpy.hstack), [vstack](https://numpy.org/doc/1.18/reference/generated/numpy.vstack.html?highlight=vstack#numpy.vstack), implemented by @muthuArivoli in https://github.com/pytorch/pytorch/pull/42799
- [x] [arcosh](https://numpy.org/doc/1.18/reference/generated/numpy.arccosh.html?highlight=arccosh#numpy.arccosh), [arcsinh](https://numpy.org/doc/1.18/reference/generated/numpy.arcsinh.html?highlight=arcsinh#numpy.arcsinh), [arctanh](https://numpy.org/doc/1.18/reference/generated/numpy.arctanh.html?highlight=arctanh#numpy.arctanh), implemented by @krshrimali in https://github.com/pytorch/pytorch/pull/38388
- [x] [atleast_1d](https://numpy.org/doc/1.18/reference/generated/numpy.atleast_1d.html?highlight=atleast_1d#numpy.atleast_1d), [atleast_2d](https://numpy.org/doc/1.18/reference/generated/numpy.atleast_2d.html), [atleast_3d](https://numpy.org/doc/1.18/reference/generated/numpy.atleast_3d.html), implemented by @kshitij12345 in #41317 
- [x] [deg2rad](https://numpy.org/doc/1.18/reference/generated/numpy.deg2rad.html?highlight=deg2rad), [rad2deg](https://numpy.org/doc/1.18/reference/generated/numpy.rad2deg.html?highlight=rad2deg), implemented by @aayn in https://github.com/pytorch/pytorch/pull/38852
- [x] [fliplr](https://numpy.org/doc/1.18/reference/generated/numpy.fliplr.html?highlight=fliplr), [flipud](https://numpy.org/doc/1.18/reference/generated/numpy.flipud.html?highlight=flipud), implemented by @kshitij12345 in https://github.com/pytorch/pytorch/pull/38599
- [x] [isneginf](https://numpy.org/doc/1.18/reference/generated/numpy.isneginf.html?highlight=isneginf#numpy.isneginf), [isposinf](https://numpy.org/doc/1.18/reference/generated/numpy.isposinf.html?highlight=isposinf#numpy.isposinf), implemented by @RockingJavaBean in #41588
- [x] [isreal](https://numpy.org/doc/1.18/reference/generated/numpy.isreal.html?highlight=isreal#numpy.isreal), implemented by @Justin-Huber in #41298
- [x] [logaddexp](https://numpy.org/doc/1.18/reference/generated/numpy.logaddexp.html?highlight=logaddexp#numpy.logaddexp), [logaddexp2](https://numpy.org/doc/1.18/reference/generated/numpy.logaddexp2.html?highlight=logaddexp#numpy.logaddexp2), implemented by @cloudhan in #38384 
- [x] [signbit](https://numpy.org/doc/1.18/reference/generated/numpy.signbit.html?highlight=signbit#numpy.signbit), implemented by @Kiyosora in #41589
- [x] [count_nonzero](https://numpy.org/doc/1.18/reference/generated/numpy.count_nonzero.html?highlight=count_nonzero#numpy.count_nonzero), implemented by @kshitij12345 in #39992 
- [x] [gcd](https://numpy.org/doc/1.18/reference/generated/numpy.gcd.html?highlight=gcd#numpy.gcd), [lcm](https://numpy.org/doc/1.18/reference/generated/numpy.lcm.html?highlight=lcm#numpy.lcm), implemented by @aayn in #40651
- [x] [moveaxis](https://numpy.org/doc/1.18/reference/generated/numpy.moveaxis.html?highlight=moveaxis) (https://github.com/pytorch/pytorch/issues/36048), implemented by @kshitij12345 in #41480 (as movedim)
- [x] [quantile](https://numpy.org/doc/1.18/reference/generated/numpy.quantile.html?highlight=quantile#numpy.quantile), implemented by @heitorschueroff in #39417
- [x] [nansum](https://numpy.org/doc/stable/reference/generated/numpy.nansum.html?highlight=nansum#numpy.nansum), implemented by @kshitij12345 in https://github.com/pytorch/pytorch/pull/38628
- [x] [hypot](https://numpy.org/doc/1.18/reference/generated/numpy.hypot.html?highlight=hypot#numpy.hypot) (#22764), implemented by @muthuArivoli in https://github.com/pytorch/pytorch/pull/42291
- [x] [nextafter](https://numpy.org/doc/1.18/reference/generated/numpy.nextafter.html?highlight=nextafter#numpy.nextafter), implemented by @muthuArivoli in https://github.com/pytorch/pytorch/pull/42580

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @rgommers @heitorschueroff 
cc @aayn @n-gao

**Comment by kshitij12345** [comment]
Hi,

I'd like to work on `fliplr` and `flipud`

**Comment by rgommers** [comment]
@mruberry there's a number of functions in there that the NumPy devs consider mistakes or are outdated. We'd like to be able to deprecate those, but *backwards compat discussions*. Examples are `heaviside` (too trivial), `kaiser` and all other window functions (belongs in `scipy.signal`), `ptp` (unreadable, bad idea), `percentile` (`quantile` is almost identical but slightly better), `sinc` (belongs in `scipy.special`). All the `*stack` functions are kind of special cases of `concatenate` and `stack`, see https://github.com/numpy/numpy/issues/7183.

A lot of the other functions (e.g. `deg2rad`) are simply utilities that would maybe be good to have somewhere, but probably not in the main `torch` namespace.

We'll also have to deal with existing incompatibilies between pytorch and numpy functions/objects of the same name, e.g. mapping `axis` to `dim`, the behavior of `.view()` and probably many more little things.

Would it make sense to curate the above list of desired functions a little, and revisit the separate `torch.numpy` namespace (https://github.com/pytorch/pytorch/issues/2228#issuecomment-488808650) for adding the utility functions?

**Comment by mruberry** [comment]
Always great to hear from you, @rgommers! 

Let's follow-up offline.

**Comment by mruberry** [comment]
> Hi,
> 
> I'd like to work on `fliplr` and `flipud`

That's great! But no need to announce what you're working on ;) Go for it!

**Comment by carlosgmartin** [comment]
Should [`take`](https://numpy.org/doc/stable/reference/generated/numpy.take.html) be added to the list?

**Comment by carlosgmartin** [comment]
The following seems to work for [`quantile`](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html):

```python
import torch
import numpy as np
from pdb import set_trace

def take(a, indices, axis):
    return a[tuple(
        slice(a.shape[dim]) if dim != axis else indices 
        for dim in range(a.ndim)
    )]

def quantile(a, q, axis):
    i = q * (a.shape[axis] - 1)
    i_hi = torch.ceil(i).long()
    i_lo = torch.floor(i).long()
    w_hi = i - i_lo
    w_lo = 1 - w_hi
    sort = a.sort(axis).values
    v_hi = take(sort, i_hi, axis)
    v_lo = take(sort, i_lo, axis)
    return w_lo * v_lo + w_hi * v_hi

while True:
    a = torch.randn(4, 5, 6).float()
    q = torch.rand(size=())
    axis = torch.randint(a.ndim, size=())
    try:
        x = quantile(a, q, axis)
        y = torch.tensor(np.quantile(a, q, axis)).float()
        assert torch.allclose(x, y, atol=1e-6)
    except AssertionError:
        print(x)
        print(y)
        set_trace()
```

Note that `q` could potentially be a tensor rather than just a scalar.

**Comment by mruberry** [comment]
> The following seems to work for [`quantile`]...

Yes but we need a properly registered C++ implementation since PyTorch has both Python and C++ APIs.

**Comment by mruberry** [comment]
> Should [`take`](https://numpy.org/doc/stable/reference/generated/numpy.take.html) be added to the list?

"take" isn't a great candidate at the moment because we already have [torch.take](https://pytorch.org/docs/master/generated/torch.take.html?highlight=take#torch.take).

**Comment by kshitij12345** [comment]
@mruberry 
`outer` will just be an alias for `torch.ger` right?
```python
>>> import torch
>>> import numpy as np
>>> np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])
>>> torch.ger(torch.ones((5,)), torch.linspace(-2, 2, 5))
tensor([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]])
```

**Comment by carlosgmartin** [comment]
> "take" isn't a great candidate at the moment because we already have [torch.take](https://pytorch.org/docs/master/generated/torch.take.html?highlight=take#torch.take).

torch.take doesn't seem to take an axis like the numpy version.

**Comment by mruberry** [comment]
> `outer` will just be an alias for `torch.ger` right?

Good point! I'll remove it from the list since we'll be handling aliases later. Thanks @kshitij12345!

**Comment by mruberry** [comment]
> > "take" isn't a great candidate at the moment because we already have [torch.take](https://pytorch.org/docs/master/generated/torch.take.html?highlight=take#torch.take).
> 
> torch.take doesn't seem to take an axis like the numpy version.

Yes, sorry I should have elaborated that this list is intended for entirely new functions, not for functions that exist in PyTorch but don't have the same behavior as those functions in NumPy. Those are out of scope for this issue. (They're totally valid separate issues, however.)

**Comment by vadimkantorov** [comment]
One problem with special numpy-like `nan*` ops is that without an agreed and clearly pronounced principle, many other non-numpy ops may demand nan* versions as well: e.g. topk https://github.com/pytorch/pytorch/issues/16762

One problem about fliplr/flipud is that they assume about which dimensions they concern, if I understand well. But in PyTorch usecases, there can be more flexible choices (as opposed to NumPy): BCHW is more popular logic format, but if someone has BHWC logical format, then what will fliplr/flipud do?

**Comment by mruberry** [comment]
I don't think the behavior of fliplr and flipud is ambiguous. You are correct that their names suggest a certain perspective on the data, but that's typical of many functions. 

From my discussion with @rgommers there probably won't be many (any?) new `nan-` functions, but the existing ones are frequently used and have been requested.

**Comment by vadimkantorov** [comment]
About nan: an alternative way could be adding some nan-controlling option to regular torch.mean/sum/... and then redirecting these numpy nan* versions to use that option enabled. Like that, if we have pytorch (not numpy) functions wanting to support nan skipping, the interface would be the same (e.g. `skip_nan = True` or `nan_policy = 'skip'`) and no function nan* aliases will have to be created

**Comment by rgommers** [comment]
> From my discussion with @rgommers there probably won't be many (any?) new `nan-` functions

Dug up the most recent discussion on this with a summary of the feeling of the NumPy devs about this: https://github.com/numpy/numpy/issues/13198#issuecomment-585377178

**Comment by vadimkantorov** [comment]
Even if there won't be any new nan* functions in NumPy, my question is whether some new "API language element" should be created (e.g. like we have `dim=`, `out=` common arguments even for some functions when NumPy doesn't support `out=`). It seems that NumPy devs took decision to not create any new API conventions (like `nan_policy`), but PyTorch could decide otherwise. E.g. SciPy.Stats has `nan_policy` concept. (Both choices are valid I think, but a made choice should be explicitly pronounced I think in some new "NaN/Inf handling" docs section)

**Comment by rgommers** [comment]
> Another related: SciPy.Stats seems to have `nan_policy` concept 

SciPy has had that for some years, but it had some inconsistencies for a long time. Those are now ironed out, and a design spec PR was just submitted last week: https://github.com/scipy/scipy/pull/12069

> (not saying that any choice is much better than the other - just that the made choice should be hopefully made clear in some new "NaN/Inf handling" docs section)

Sounds reasonable. I would say though that it's mostly statistics related. For most functionality the standard nan/inf handling is fine. If you'd want to distinguish between "raise" and "propagate" consistently for many functions, a context manager (like `numpy.errstate`) would be better than a keyword imho.

**Comment by cloudhan** [comment]
@mruberry logaddexp2 has also been implemented in that pr

**Comment by vadimkantorov** [comment]
torch.where to support scalar args (supported by numpy and is quite useful): https://github.com/pytorch/pytorch/issues/9190

**Comment by vadimkantorov** [comment]
It would be good to support string values for dtype arguments all across PyTorch:
https://github.com/pytorch/pytorch/issues/40568

NumPy supports them.

PyTorch supports string values for devices, so string values for structured things like dtypes wouldn't be so new even for PyTorch.

**Comment by cloudhan** [comment]
IIRC, caffe2 supported string tensor, and was removed.

**Comment by vadimkantorov** [comment]
To be more clear, I mean suppoting sth like this:
```python
import torch
import numpy

numpy.array([3, 3], dtype = 'int32')
# array([3, 3], dtype=int32)

torch.tensor([3, 3], dtype = 'int32')
# TypeError: tensor(): argument 'dtype' must be torch.dtype, not str
```

**Comment by ezyang** [comment]
BTW, for the record, internally we still support tensors of strings, it is simply not exposed to the PyTorch frontend (for understandable reasons).

**Comment by vadimkantorov** [comment]
Feature request: packbits/unpackbits https://github.com/pytorch/pytorch/issues/32867

**Comment by vadimkantorov** [comment]
left_shift / right_shift (with out argument support): https://github.com/pytorch/pytorch/issues/41624

**Comment by vadimkantorov** [comment]
`xlogy` would also be very useful (and is present in scipy): https://github.com/pytorch/pytorch/issues/22656

**Comment by leockl** [comment]
Hi All,

Would be great if we could have `torch.linalg.eigh` to be analogous to `numpy.linalg.eigh`, in particular with the +ve/-ve signs of the eigenvalues when the eigenvalues are very very small and close to 0.

A more detailed description of this is here: [#41688](https://github.com/pytorch/pytorch/issues/41688)

**Comment by leockl** [comment]
Hi All, 

Would be great if we could have `torch.chunk` to match the behavior of that of `numpy.array_split`.

A more detailed description of this is here: [#9382](https://github.com/pytorch/pytorch/issues/9382)

*Ps: I think the initiative in this issue is fantastic! I have recently developed a Scikit-learn estimator and now I am wanting to make the estimator GPU accessible. I stumbled upon quite a few functions in PyTorch which doesn't behave similarly with Numpy, and this has put me off a little. I was thinking to make the switch to TF instead, but after seeing this issue, it has given me some confidence back with sticking with PyTorch. So definitely this initiative would have positive downstream impact on retaining people like myself in PyTorch.

**Comment by mruberry** [comment]
> Hi All,
> 
> Would be great if we could have `torch.chunk` to match the behavior of that of `numpy.array_split`.
> 
> A more detailed description of this is here: [#9382](https://github.com/pytorch/pytorch/issues/9382)
> 
> *Ps: I think the initiative in this issue is fantastic! I have recently developed a Scikit-learn estimator and now I am wanting to make the estimator GPU accessible. I stumbled upon quite a few functions in PyTorch which doesn't behave similarly with Numpy, and this has put me off a little. I was thinking to make the switch to TF instead, but after seeing this issue, it has given me some confidence back with sticking with PyTorch. So definitely this initiative would have positive downstream impact on retaining people like myself in PyTorch.

That's great to hear, @leockl. Would you detail the other functions you found that behaved differently?

**Comment by leockl** [comment]
Hi @mruberry.

There's one on `argmax` and `argmin` ([#22853](https://github.com/pytorch/pytorch/issues/22853)) which I think @kshitij12345 had put through a PR but it isn't successful (yet).

Another one (perhaps not directly related to Numpy) is `torch.multiprocessing.pool`. Since PyTorch have the same `multiprocessing.pool` module as the Python one, but the PyTorch one doesn't work or behave the same as the Python one. More details of this is here: [#42049](https://github.com/pytorch/pytorch/issues/42049)

Many thanks again.

**Comment by mruberry** [comment]
Thank you for the update, @leockl. I'll try to take a look at all these issues soon.

**Comment by vadimkantorov** [comment]
frombuffer/fromfile would be helpful. my related issues (mostly about ingesting byte arrays into PyTorch from different sources): https://github.com/pytorch/pytorch/issues/30387 https://github.com/pytorch/pytorch/issues/34651 https://github.com/pytorch/pytorch/issues/34646 https://github.com/pytorch/pytorch/issues/34649 https://github.com/pytorch/pytorch/issues/29013 https://github.com/pytorch/pytorch/issues/42159

**Comment by vadimkantorov** [comment]
Some common dtype attributes: kind, itemsize. Currently they're missing from both dtype and iinfo/finfo

**Comment by vadimkantorov** [comment]
tobytes and byteswap are also missing

**Comment by mruberry** [comment]
> tobytes and byteswap are also missing: https://github.com/vadimkantorov/torchwavfile/blob/master/torchwavfile.py#L11 have to do this as a workaround :(

How would tobytes work on CUDA?

**Comment by vadimkantorov** [comment]
> How would tobytes work on CUDA?

error out (like it now does if you call numpy)?

The usecase is interop with methods that use buffer interface and bytes interface (also a question is to what extent it's possible to prevent too early memory free. sometimes it may be useful to do some manual refcount increase and decrease). Examples of nasty workarounds in https://github.com/vadimkantorov/torchwav/blob/master/torchwave.py and https://github.com/vadimkantorov/torchwav/blob/master/torchwavfile.py

**Comment by vadimkantorov** [comment]
One more vote for `divmod`, given that the scalar version is already implemented in JIT as part of https://github.com/pytorch/pytorch/issues/18627#issue-427135521

**Comment by vadimkantorov** [comment]
A request for numpy.append (useful for collecting some metrics values in a torch tensor instead of python array). A simplistic impl can be like this:
```
# like numpy append https://numpy.org/doc/stable/reference/generated/numpy.append.html
def append(arr, values, factor = 1.5):
    if len(arr) > 0:
        assert arr.storage_offset() == 0 and factor >= 1
        numel = len(arr) + len(values)
        if numel > arr.storage().size():
            arr.resize_(int(numel * factor))
        arr.resize_(numel)
        arr[len(arr) - len(values):] = values
        return arr
    else:
        return values.clone()

if __name__ == '__main__':
    array = torch.tensor([])
    array = append(array, torch.as_tensor([1, 2, 3]))
    array = append(array, torch.as_tensor([4, 5, 6]))
    print(array)
```

**Comment by mruberry** [comment]
In that case you could just use cat?

**Comment by vadimkantorov** [comment]
It's a question about allocation. As you know, any dynamic array (like python's list or otherwise) doesn't just use cat and reallocate at every extend call. They usually reallocate assuming some growth factor (of range of 2), this lets to allocate fewer times, at the expense of over-allocating.

**Comment by mruberry** [comment]
I don't really see how that applies to append. It would allocate its output like anything else without additional changes to PyTorch's memory allocators to support some kind of hinting.

**Comment by vadimkantorov** [comment]
It depends on how you choose to implement append. My version pre-allocates larger buffers, so that following small appends do not lead to reallocations.

I have not proposed or discussed changes to allocators wrt to append-like functionality, so cannot comment about that.

**Comment by ezyang** [comment]
FWIW, Caffe2 had append too. It is a useful operation for certain use cases, although it is somewhat questionable whether or not these use cases should actually be done with tensors haha.

**Comment by vadimkantorov** [comment]
python may use two much memory for numbers, since it creates a full blown-object if I understand well... + sometimes the actuall source of values is another tensor, so without append it would lead to yet another copy

**Comment by mruberry** [comment]
I updated this issue with more NumPy functions it'd be great to have in PyTorch. This issue already describes **29** implementations from @aayn, @RockingJavaBean, @muthuArivoli, @krshrimali, @kshitij12345, @Justin-Huber, @cloudhan, @Kiyosora, and @heitorschueroff. Many other NumPy functions have been added besides these, too, and some existing functions have had their behavior updated, which is great progress on our goal of being more NumPy-compatible. There's still plenty of work left to be done, however, with **24** tasks in this issue alone.

**Comment by vadimkantorov** [comment]
feature request (probably turned up somewhere in issues, but a quick search did not found it): [numpy.diff](https://numpy.org/doc/stable/reference/generated/numpy.diff.html)

**Comment by matthewfeickert** [comment]
Hi @mruberry. As a follow up to Issue #35977, PR #39417 implemented `quantile` but only with a linear interpolation method. It would be great to have [all the interpolation methods supported by NumPy](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html), JAX, and TensorFlow: `linear`, `lower`, `higher`, `nearest`, `midpoint`.

**Comment by mruberry** [comment]
> Hi @mruberry. As a follow up to Issue #35977, PR #39417 implemented `quantile` but only with a linear interpolation method. It would be great to have [all the interpolation methods supported by NumPy](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html), JAX, and TensorFlow: `linear`, `lower`, `higher`, `nearest`, `midpoint`. (By the way thanks for all this nice work and it is great to see `quantile` in [`v1.7.0` today](https://github.com/pytorch/pytorch/releases/tag/v1.7.0)!)

I filed a new issue to track this request: https://github.com/pytorch/pytorch/issues/48523.

**Comment by sramakrishnan247** [comment]
@mruberry Hey, I am new here, I wanted to try something simple like divmod, do I just need to understand and implement at it and create a pull request directly?

**Comment by mruberry** [comment]
Hi @sramakrishnan247, it'd be great to see a PR. I would start by looking at the other PRs for this topic to get an idea for how a new operator is implemented. I would recommend your first function be frexp, not divmod, since divmod is a bit complicated.

**Comment by PandaBoi** [comment]
Hi @mruberry, 
I would like to take a shot at diag_indices, as a first contribution.. I had a doubt about the function, since it can be implemented without taking an input tensor, should I keep it that way? In the other functions I could not find another wherein no tensors were passed in as parameters. Would appreciate some help regarding this. Thanks!

**Comment by mruberry** [comment]
@PandaBoi You're correct, diag_indices does not take a tensor as input, and this does make it different than the other functions on the list. 

Other functions that don't take tensors as parameters include the tensor creation operations, like torch.randn and torch.ones, and other index-producing functions like torch.tril_indices and torch.triu_indices. The latter functions also take some kwargs, and of those kwargs I think only the device kwarg is especially interesting. An initial implementation of diag_indices could include that kwarg, but it's not necessary. 

Does that help?

**Comment by PandaBoi** [comment]
@mruberry definitely helped, I'll look into those functions and work on an initial implementation. Thanks!

**Comment by PandaBoi** [comment]
@mruberry

I've opened a draft PR (#50466) for corrcoef and pearsonr and had a few doubts I needed your help with, could you please have a look when you have some time?

**Comment by zhuzilin** [comment]
@PandaBoi Hi! As you are working on `corrcoef` at the moment, could I take a look at `diag_indices`? Thank you~

**Comment by PandaBoi** [comment]
@zhuzilin Hi!
Certainly, please go ahead.. You may find #50360 useful.

**Comment by alvgaona** [comment]
Hi, quick question. It seems to me that `historgram` is already implemented in [torch.histc](https://pytorch.org/docs/1.8.0/generated/torch.histc.html?highlight=histogram), isn't it?

**Comment by rgommers** [comment]
> Hi, quick question. It seems to me that `historgram` is already completed in [torch.histc](https://pytorch.org/docs/1.8.0/generated/torch.histc.html?highlight=histogram), isn't it?

The idea of this compatibility work is to end up with the same functionality and function signatures/semantics, so no - `torch.histc` may be a decent start (or not, not sure) but the aim is a new function.

Note that SciPy plans to start using Boost to base its binned histogram functionality on, and perhaps reintroduce `scipy.stats.histogram` - Boost is significantly faster than what NumPy has now.

**Comment by alvgaona** [comment]
Awesome, thanks @rgommers

**Comment by rgommers** [comment]
One thing I never noticed before, and that I don't find discussed in issues, is that pytorch doesn't have `nan`, `inf`, `pi` and `e` constants. At least the first three are used a lot. The test suite is full of `float('nan')` and `float('inf')` which is ugly. Doing `import math; nan = math.nan` would be the alternative (that'd be reasonable). Anyone know if not implementing these constants was a conscious decision?

**Comment by mruberry** [comment]
> One thing I never noticed before, and that I don't find discussed in issues, is that pytorch doesn't have `nan`, `inf`, `pi` and `e` constants. At least the first three are used a lot. The test suite is full of `float('nan')` and `float('inf')` which is ugly. Doing `import math; nan = math.nan` would be the alternative (that'd be reasonable). Anyone know if not implementing these constants was a conscious decision?

Per offline discussion, no it was. We can probably just add these.

**Comment by vadimkantorov** [comment]
torch functions for torch.add / torch.delete

**Comment by Kiyosora** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的邮件，请放心。

**Comment by mruberry** [comment]
Closing this issue. We've added the great majority of missing NumPy functions, and future requests can be handled as individual issues.

@vadimkantorov We have `torch.add()`, but would you like to file an issue requesting `torch.delete()`? `delete` is a tough name to reuse, however.

**Comment by vadimkantorov** [comment]
Oh, I think mistyped, I meant append / delete. Yeah, I'll create a separate issues for discussing these

**Comment by danijar** [comment]
@mruberry I just found this issue and was quite surprised that it's closed. It seems like even basic Numpy functions like `np.concatenate()` are not in the PyTorch namespace yet? Are there any plans to support a Numpy-like API? That's the default in JAX and TF2 has `tf.experimental.numpy` with fairly complete coverage. I'm happy to open a separate issue if this one was just to provide Numpy-like functionality rather than a Numpy-like API.

**Comment by danijar** [comment]
That's great to hear! I'm happy to file an issue. It would just be useful to see an overview of what's available and what's still missing, it could even be a spreadsheet. That way, I can see what I need to special case when converting a given code base from JAX to PT.
