### ISSUE TITLE
torch.fft tracking issue

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#42175]
Tracking issue for tasks related to the torch.fft namespace, analogous to NumPy's [numpy.fft namespace](https://numpy.org/doc/stable/reference/routines.fft.html?highlight=fft#module-numpy.fft) and SciPy's [scipy.fft namespace](https://docs.scipy.org/doc/scipy/reference/fft.html#module-scipy.fft).

PyTorch already has fft functions ([fft](https://pytorch.org/docs/master/generated/torch.fft.html?highlight=fft#torch.fft), [ifft](https://pytorch.org/docs/master/generated/torch.ifft.html?highlight=fft#torch.ifft), [rfft](https://pytorch.org/docs/master/generated/torch.rfft.html?highlight=fft#torch.rfft) , [irfft](https://pytorch.org/docs/master/generated/torch.irfft.html?highlight=fft#torch.irfft), [stft](https://pytorch.org/docs/master/generated/torch.stft.html?highlight=stft#torch.stft), [istft](https://pytorch.org/docs/master/generated/torch.istft.html?highlight=stft#torch.istft)), but they're inconsistent with NumPy and don't accept complex tensor inputs. The torch.fft namespace should be consistent with NumPy and SciPy where possible, plus provide a path towards removing PyTorch's existing fft functions in the 1.8 release (deprecating them in 1.7). 

While adding the torch.fft namespace infrastructure and deprecating PyTorch's current fft-related functions are the top priorities, PyTorch is also missing many helpful functions, listed below, which should (eventually) be added to the new namespace, too. 

**Tasks:**

- [ ] Write doc preamble to fft module
- [ ] Write blogpost about the torch.fft module
- [ ] Write tutorial
- [ ] Create forum group

**Completed:**
- [x] Fix erronenous stft() warning (see comment below) (fixed in #47601)
- [x] Remove torch.fft() (and torch.Tensor.fft() and torch.rfft() and torch.Tensor.rfft()) and import the torch.fft module by default (#48594)
- [x] Review fft architecture for (1) functions used are in ATen and (2) functions actually support complex values (so complex-specific kernels can be used) (New FFT operators in #46911 use complex throughout)
- [x] Rewrite `_fft_with_size` to handle transforming arbitrary dimensions without transposing/cloning (#46911 still requires cloning, but this is required for best performance)
- [x] Review operator performance
  - Related issues: https://github.com/pytorch/pytorch/issues/38413
- [x] Add OpInfo based tests
- [x] Implement torch function overrides for the fft module
- [x] Add support for out arguments
- [x] Implement torch.fft.fft2()
- [x] Implement torch.fft.iff2()
- [x] Implement torch.fft.rfft2()
- [x] Implement torch.fft.irfft2()
- [x] Investigate gradgrad and ensure `gradgradcheck` passes
- [x] stft crash (https://github.com/pytorch/pytorch/issues/30865)
- [x] Implement torch.fft.fft()
- [x] Implement torch.fft.ifft()
- [x] Implement torch.fft.rfft()
- [x] Implement torch.fft.irfft()
- [x] Update torch.stft() and torch.istft() to handle complex tensors (like librosa does) and document librosa-compat (not SciPy)
- [x] Create test_spectral_ops.py (https://github.com/pytorch/pytorch/pull/42157)
- [x] Create torch.fft namespace (https://github.com/pytorch/pytorch/pull/41911)
- [x] Implement torch.fft.fftn()
- [x] Implement torch.fft.ifftn()
- [x] Implement torch.fft.fftfreq()
- [x] Implement torch.fft.rfftfreq()
- [x] Implement torch.fft.fftshift()
- [x] Implement torch.fft.ifftshift()
- [x] Deprecate torch.fft()
- [x] Deprecate torch.ifft()
- [x] Deprecate torch.rfft()
- [x] Deprecate torch.irfft()
- [x] Deprecate torch.stft() and torch.istft() returning non-complex tensors mimicking complex tensors
- [x] https://github.com/pytorch/pytorch/issues/42213, pytorch istft runs slower than torchaudio istft

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @rgommers @peterbell10

**Comment by peterbell10** [comment]
A collection of my current thoughts on this.

## Top priority functions

The linked PR covers `fft`, `ifft`, `rfft` and `irfft`. These should be fully numpy compatible (except for using `dim` instead of `axis`).

>It may be easiest to start with forward for these and implement backward as separate follow-ups.

I haven't added tests for this yet, but I expect the current implementations to be differentiable because it still goes through `_fft_with_size` which has the derivative registered.

>Implement torch.stft() (is there a better NumPy or SciPy analogue for this and its inverse?)

There's no equivalent in NumPy or SciPy. The commit history reveals the current interface was created for compatibility with [`librosa.stft`](https://librosa.org/doc/latest/generated/librosa.stft.html) so I think it's reasonable to maintain compatibility there. To make it more NumPy-like we can add a `dim` argument, change the `normalized` argument into the `norm` mode string and instead of having a `onesided`  argument have two functions `stft` and `rstft`. `librosa` has none of those arguments so this shouldn't be a problem.

With that in mind, I suggest these signatures, putting the new arguments at the end of the `librosa` signature:
```
stft(Tensor self, int n_fft, int? hop_length=None, int? win_length=None,
     Tensor? window=None, int dim=-1, str? norm=None) -> Tensor

rstft(Tensor self, int n_fft, int? hop_length=None, int? win_length=None,
      Tensor? window=None, int dim=-1, str? norm=None) -> Tensor
```

## Multi-dim transforms

Wrapping `_fft_with_size` for multi-dim transforms will not be quite as simple since `_fft_with_size` only supports transforming up to 3 transform dimensions at a time.  This comes from a limitation of [`cuFFT`](https://docs.nvidia.com/cuda/cufft/index.html#data-layout)'s transforms, [mkl fft](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/fourier-transform-functions/fft-functions.html) goes up to 7. The simple route is to split transforms into batches of 3 dimensions at a time. Or, a deeper rewrite of `_fft_with_size` is needed.

Batching `_fft_with_size` will be quite expensive because `_fft` internally reshapes the arrays to squash the batch dimensions. So it will waste time copying around data. If there's a rush to  get this functionality in for the next release then I could start with a simple wrapper and move to a more performant rewrite after.

## Helper functions

`fftfreq`, `fftshift` are both quite handy and actually really simple. `fftfreq` is just `arange` + `mul`, `fftshift` is just a `roll`.

In `scipy.fft` we also have a [`next_fast_len`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.next_fast_len.html#scipy.fft.next_fast_len) helper which calculates the lowest multiple of the FFT implementation's prime radices above a target value. This is useful for convolution-like applications where zero-padding is acceptable. Though, cuFFT doesn't implement radix-11 transforms so in principle this is different between cuda and cpu tensors.

**Comment by rgommers** [comment]
> There's no equivalent in NumPy or SciPy.

@peterbell10 `scipy.signal` has `stft` and `istft` functions - it fits better than in `scipy.fft`, in the spectral analysis set of functions.

**Comment by peterbell10** [comment]
Thanks Ralf. It looks like the API there is somewhat similar but requires some translation:

n_fft -> nfft
window_length -> nperseg
hop_length -> overlap = nperseg - hoplength
pad_mode -> boundary
onesided -> return_onesided

The SciPy function also has some other functionality that pytorch doesn't have, like `detrend`, `padded` and `fs`. 

In that case we need to decide between maintaining `librosa` compat, or changing to the SciPy names.

**Comment by rgommers** [comment]
Alternatively, don't put `stft` and `istft` in `torch.fft`. Despite the last two letters of the function names meaning "Fourier Transform", these functions really are more similar to spectrogram, power spectral density, periodogram, etc. signal processing functionality than to regular Fourier transforms. And given that there's no equivalent in `numpy.fft` or `scipy.fft`, why add it here?

**Comment by mruberry** [comment]
Looks like there's two issues up for discussion:

- How do we support multidim transforms?
- What do we do with stft and istft? 

@peterbell10, maybe we should talk about the former issue on Slack?

As for stft and istft, let's talk about our options:

- "Max Compat"
  - keep torch.stft and torch.istft and document them as being consistent with librosa
  - add a signal namespace
  - create torch.signal.stft and torch.signal.istft consistent with SciPy
- "Fewer namespaces"
  - same as above except we create torch.fft.stft instead of torch.signal.stft

I'm not sure how much interest there is in other functions in the signal namespace, although @rgommers has pointed out that windowing functions like the Hann window are in scipy.signal.windows. NumPy also has windowing functions directly under its namespace (although is uses the wrong name for the Hann window) like Torch does. 

What are your thoughts? There is some potential for confusion with keeping both stft functions, but the signatures are distinct. Maybe calling torch.stft with SciPy-like arguments can not only throw an error, but redirect the user to the SciPy-compatible version?

**Comment by rgommers** [comment]
> I'm not sure how much interest there is in other functions in the signal namespace, 

I think `scipy.signal` is one of the less well maintained submodules in SciPy, and (maybe more importantly) it contains fairly high-level functionality. I would not expect that kind of functionality to be in PyTorch itself. My mental picture is that a few SciPy modules depend only on NumPy and BLAS/LAPACK, and those are the most important ones to have in PyTorch: `fft`, `linalg`, `sparse`, `special`.

Functionality that builds on top of that (e.g. `signal`, `optimize`, `stats`, `cluster`, `spatial`) is probably better kept separate. Now of course there's a few bits and pieces, like `stft` and `LBFGS`, that cover the same functionality as those SciPy modules. I'd suggest that's not a strong reason to then make another namespace to make them match.

**Comment by mruberry** [comment]
> > I'm not sure how much interest there is in other functions in the signal namespace,
> 
> I think `scipy.signal` is one of the less well maintained submodules in SciPy, and (maybe more importantly) it contains fairly high-level functionality. I would not expect that kind of functionality to be in PyTorch itself. My mental picture is that a few SciPy modules depend only on NumPy and BLAS/LAPACK, and those are the most important ones to have in PyTorch: `fft`, `linalg`, `sparse`, `special`.
> 
> Functionality that builds on top of that (e.g. `signal`, `optimize`, `stats`, `cluster`, `spatial`) is probably better kept separate. Now of course there's a few bits and pieces, like `stft` and `LBFGS`, that cover the same functionality as those SciPy modules. I'd suggest that's not a strong reason to then make another namespace to make them match.

Would you like to suggest a third option, then, is to update the librosa-compatible torch.stft and not implement a NumPy-compatible stft? Sounds consistent to me.

**Comment by rgommers** [comment]
> Would you like to suggest a third option, then, is to update the librosa-compatible torch.stft and not implement a NumPy-compatible stft? Sounds consistent to me.

Yes that seems best to me. Except I'm not sure if `stft` even needs an update? If you mean putting it into `torch.fft`, I see pros and cons to that. If you want to put it in, let's just say in the docstring "note: this function matches `librosa.stft` and differs from `scipy.signal.stft`"

**Comment by mruberry** [comment]
> > Would you like to suggest a third option, then, is to update the librosa-compatible torch.stft and not implement a NumPy-compatible stft? Sounds consistent to me.
> 
> Yes that seems best to me. Except I'm not sure if `stft` even needs an update? If you mean putting it into `torch.fft`, I see pros and cons to that. If you want to put it in, let's just say in the docstring "note: this function matches `librosa.stft` and differs from `scipy.signal.stft`"

Right, sorry, that was ambiguous. I was going to suggest we leave its name as is and keep its signature consistent with librosa but allow it to take and return complex tensors.

**Comment by peterbell10** [comment]
Quick question. `cuFFT` has some limited support for half precision FFTs (only for power of 2 lengths). But at the moment `ComplexHalf` doesn't seem to have any support in pytorch. I notice `c10` has some references to it and there is even a `torch.complex32` type accessible from python but I can't seem to create a tensor with that dtype. 

In #43011 I currently implement the SciPy behavior which is to promoting half inputs to single precision. If there are future plans for complex half then it be better to error out instead.

**Comment by ezyang** [comment]
We don't really support complex half right now, but in principle we could add support for it at some point in the future (probably CUDA only). You should plan as if, at some point in the future, we will add support for it.

**Comment by peterbell10** [comment]
Okay, all the transform in #43011 now raise an error for half and bfloat16.

**Comment by jacobjwebber** [comment]
Hi all, was going to make a new issue, but this seems an appropriate place
Using torch.stft() now returns a not-very-easy-to-understand warning.

```
     y, sr = librosa.load(vctk_example)
     y_torch = torch.from_numpy(y)
     stft = torch.stft(y_torch, 512, return_complex=True)
.....

python3.6/site-packages/torch/functional.py:517: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /opt/conda/conda-bld/pytorch_1604128358454/work/aten/src/ATen/native/SpectralOps.cpp:674.)
  normalized, onesided, return_complex)
```
Presumably this could be fixed by changing stft to point to the new fft module?

This is with today's nightly build 1.8.0.dev20201031

**Comment by peterbell10** [comment]
>Presumably this could be fixed by changing stft to point to the new fft module?

Yes, I forgot to update `stft` when I deprecated it. Thanks for bringing this up.

**Comment by mruberry** [comment]
> Hi all, was going to make a new issue, but this seems an appropriate place
> Using torch.stft() now returns a not-very-easy-to-understand warning.
> 
> ```
>      y, sr = librosa.load(vctk_example)
>      y_torch = torch.from_numpy(y)
>      stft = torch.stft(y_torch, 512, return_complex=True)
> .....
> 
> python3.6/site-packages/torch/functional.py:517: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /opt/conda/conda-bld/pytorch_1604128358454/work/aten/src/ATen/native/SpectralOps.cpp:674.)
>   normalized, onesided, return_complex)
> ```
> 
> Presumably this could be fixed by changing stft to point to the new fft module?
> 
> This is with today's nightly build 1.8.0.dev20201031

Thanks for reporting this issue. I'll add it to the tracker. We should fix this ASAP!

**Comment by wooseok-shin** [comment]
I'm going to use fast fourier transform module 'fft'.  so, updated the pytorch 1.8 1122 nightly version.
but, torch.fft.fft2 or torch.fft.fftshift function do not exist such as 'biltin_function_or_method' object has no attribute 'fft2'. 
I checked github pytorch/fft/__init__.py/
i could see that there was only a function name.
In this issue, it says that several functions have been added to completed but has it not been applied to nightly version yet?
then, could you tell me when it will be updated? Thank you.

**Comment by peterbell10** [comment]
@wooseok-shin while the `torch.fft` function still exists, you need to explicitly use `import torch.fft`.

**Comment by mruberry** [comment]
@wooseok-shin fyi this will change soonish in nightlies and in PyTorch 1.8 the module will be imported for you.

**Comment by peterbell10** [comment]
I've run some simple benchmarks comparing `torch.fft` transforms against `mkl_fft`, `numpy`, `scipy` and `cupy`. I haven't sampled a huge number of shapes because the benchmarks take a fairly long time to run, but do cover transforming over different dimensions which is interesting because the resulting performance depends a lot more on how batching is handled.

<details>
<summary>Simple benchmark code</summary>

```python
import torch
import numpy as np
import scipy.fft
import cupy
import mkl_fft._numpy_fft
import mkl
import itertools

shape = (40, 40, 100)
#shape = (42, 14, 18)
c = torch.rand(*shape, dtype=torch.cdouble)
cn = c.numpy()
cc = c.cuda()
r = torch.rand(*shape, dtype=torch.double)
rn = r.numpy()
rc = r.cuda()

operators = ['fft', 'ifft', 'rfft', 'irfft', 'fftn', 'ifftn', 'rfftn', 'irfftn', 'hfft', 'ihfft']
results = []
def add_result(name, operator, dim, times):
    results.append((name, operator, dim, times.best, times.average, times.stdev))

for op, dim in itertools.product(operators, (0, 1, 2)):
    torch_fn = getattr(torch.fft, op)
    numpy_fn = getattr(np.fft, op)
    scipy_fn = getattr(scipy.fft, op)
    mkl_fn = getattr(mkl_fft._numpy_fft, op, None)
    cupy_fn = getattr(cupy.fft, op)
    name = f'{op} dim={dim}'
    if op.startswith('rfft') or op.startswith('ihfft'):
        x, xn, xc = r, rn, rc
    else:
        x, xn, xc = c, cn, cc

    xcp = cupy.array(xn)
    if op.endswith('n'):
        x = x.movedim(dim, -1)
        xn = np.moveaxis(xn, dim, -1)
        xc = xc.movedim(dim, -1)
        xcp = cupy.moveaxis(xcp, dim, -1)
        dim_kwargs = axis_kwargs = dict()
    else:
        axis_kwargs = {'axis': dim}
        dim_kwargs = {'dim': dim}

    print(name, 'multi-threaded')
    torch.set_num_threads(8)
    t = %timeit -o torch_fn(x, **dim_kwargs)
    add_result('torch mulithreaded', op, dim, t)
    if mkl_fn is not None:
        mkl.set_num_threads(8)
        t = %timeit -o mkl_fn(xn, **axis_kwargs)
        add_result('mkl_fft multi threaded', op, dim, t)
    t = %timeit -o scipy_fn(xn, workers=8, **axis_kwargs)
    add_result('scipy multi threaded', op, dim, t)

    print(name, 'single threaded')
    torch.set_num_threads(1)
    t = %timeit -o torch_fn(x, **dim_kwargs)
    add_result('torch single threaded', op, dim, t)
    if mkl_fn is not None:
        mkl.set_num_threads(1)
        t = %timeit -o mkl_fn(xn, **axis_kwargs)
        add_result('mkl_fft single threaded', op, dim, t)
    t = %timeit -o numpy_fn(xn, **axis_kwargs)
    add_result('numpy', op, dim, t)
    t = %timeit -o scipy_fn(xn, **axis_kwargs)
    add_result('scipy single threaded', op, dim, t)

    print(name, 'cufft')
    t = %timeit -o torch_fn(xc, **dim_kwargs); torch.cuda.synchronize()
    add_result('torch cuda', op, dim, t)
    t = %timeit -o cupy_fn(xcp, **axis_kwargs); cupy.cuda.runtime.deviceSynchronize()
    add_result('cupy', op, dim, t)

```

The full results are available in some spread sheets but I'll sumarise here.
[fft-comparison-benchmarks.zip](https://github.com/pytorch/pytorch/files/5721529/fft-comparison-benchmarks.zip)


For cuda, `torch.fft.*` either performed similarly or as much as 2x faster than `cupy.fft.*`. That's pretty good considering we're both just calling cuFFT under the hood.

For single threaded CPU performance I compared against `mkl_fft`, `numpy` and scipy`.
- `numpy` was slower in all cases, at best around 1.5x slower than pytorch and at worst 3.9x slower. 
- `scipy` hovered around 1-1.5x slower in most cases. For the larger shaped tensor, `scipy` is around 15-20% faster at `ihfft` on all but the last dimension. This is perhaps not surprising though, as `scipy.fft` has custom kernels for `hfft` and `ihfft` whereas intel mkl doesn't.
- Perhaps most interesting is `mkl_fft`. For the smaller input shape, `mkl_fft is a few microseconds (around 10%) faster for `fft` and `ifft` with `dim=0` or `dim=-1`. I would attribute this to `mkl_fft` caching the transform descriptor between calls whereas torch.fft recreates them each time.  

</details>

**Comment by peterbell10** [comment]
I've run some simple benchmarks comparing `torch.fft` transforms against `mkl_fft`, `numpy`, `scipy` and `cupy`. I haven't sampled a huge number of shapes because the benchmarks take a fairly long time to run, but do cover transforming over different dimensions which is interesting because the resulting performance depends a lot more on how batching is handled.

<details>
<summary>Simple benchmark code</summary>

```python
import torch
import numpy as np
import scipy.fft
import cupy
import mkl_fft._numpy_fft
import mkl
import itertools

shape = (40, 40, 100)
#shape = (42, 14, 18)
c = torch.rand(*shape, dtype=torch.cdouble)
cn = c.numpy()
cc = c.cuda()
r = torch.rand(*shape, dtype=torch.double)
rn = r.numpy()
rc = r.cuda()

operators = ['fft', 'ifft', 'rfft', 'irfft', 'fftn', 'ifftn', 'rfftn', 'irfftn', 'hfft', 'ihfft']
results = []
def add_result(name, operator, dim, times):
    results.append((name, operator, dim, times.best, times.average, times.stdev))

for op, dim in itertools.product(operators, (0, 1, 2)):
    torch_fn = getattr(torch.fft, op)
    numpy_fn = getattr(np.fft, op)
    scipy_fn = getattr(scipy.fft, op)
    mkl_fn = getattr(mkl_fft._numpy_fft, op, None)
    cupy_fn = getattr(cupy.fft, op)
    name = f'{op} dim={dim}'
    if op.startswith('rfft') or op.startswith('ihfft'):
        x, xn, xc = r, rn, rc
    else:
        x, xn, xc = c, cn, cc

    xcp = cupy.array(xn)
    if op.endswith('n'):
        x = x.movedim(dim, -1)
        xn = np.moveaxis(xn, dim, -1)
        xc = xc.movedim(dim, -1)
        xcp = cupy.moveaxis(xcp, dim, -1)
        dim_kwargs = axis_kwargs = dict()
    else:
        axis_kwargs = {'axis': dim}
        dim_kwargs = {'dim': dim}

    print(name, 'multi-threaded')
    torch.set_num_threads(8)
    t = %timeit -o torch_fn(x, **dim_kwargs)
    add_result('torch mulithreaded', op, dim, t)
    if mkl_fn is not None:
        mkl.set_num_threads(8)
        t = %timeit -o mkl_fn(xn, **axis_kwargs)
        add_result('mkl_fft multi threaded', op, dim, t)
    t = %timeit -o scipy_fn(xn, workers=8, **axis_kwargs)
    add_result('scipy multi threaded', op, dim, t)

    print(name, 'single threaded')
    torch.set_num_threads(1)
    t = %timeit -o torch_fn(x, **dim_kwargs)
    add_result('torch single threaded', op, dim, t)
    if mkl_fn is not None:
        mkl.set_num_threads(1)
        t = %timeit -o mkl_fn(xn, **axis_kwargs)
        add_result('mkl_fft single threaded', op, dim, t)
    t = %timeit -o numpy_fn(xn, **axis_kwargs)
    add_result('numpy', op, dim, t)
    t = %timeit -o scipy_fn(xn, **axis_kwargs)
    add_result('scipy single threaded', op, dim, t)

    print(name, 'cufft')
    t = %timeit -o torch_fn(xc, **dim_kwargs); torch.cuda.synchronize()
    add_result('torch cuda', op, dim, t)
    t = %timeit -o cupy_fn(xcp, **axis_kwargs); cupy.cuda.runtime.deviceSynchronize()
    add_result('cupy', op, dim, t)

```

</details>



The full results are available in some spread sheets but I'll sumarise here.
[fft-comparison-benchmarks.zip](https://github.com/pytorch/pytorch/files/5721529/fft-comparison-benchmarks.zip)


For cuda, `torch.fft.*` either performed similarly or as much as 2x faster than `cupy.fft.*`. That's pretty good considering we're both just calling cuFFT under the hood.

For single threaded CPU performance I compared against `mkl_fft`, `numpy` and `scipy`.
- `numpy` was slower in all cases, at best around 1.5x slower than pytorch and at worst 3.9x slower. 
- `scipy` hovered around 1-1.5x slower in most cases. For the larger shaped tensor, `scipy` is around 15-20% faster at `ihfft` on all but the last dimension. This is perhaps not surprising though, as `scipy.fft` has custom kernels for `hfft` and `ihfft` whereas intel mkl doesn't.
- Perhaps most interesting is `mkl_fft`. `mkl_fft` is often a few microseconds (around 10% for the smaller tensor) faster for `fft` and `ifft` with `dim=0` or `dim=-1`. I would attribute this to `mkl_fft` caching the transform descriptor between calls whereas `torch.fft` recreates them each time. This significantly simplifies the code though, so may not be worth the extra microseconds.
  On the other hand, many `dim=1` transforms were 2-4x slower on `mkl_fft` than `torch.fft` so the way I'm handling batching is clearly good.

For multithreaded CPU performance, I only compare against `mkl_fft` and `scipy` since `numpy` doesn't support multithreading.
- `scipy` was up to 30% faster for the smaller single dimensional transform on `dim=1`. Probably because It doesn't require contiguous batch dimensions, so avoids an extra copy. However, this difference becomes negligible for multi-dimensional transforms or transforms over larger tensors. In most other cases, `torch.fft` was 2-3x faster.
- `mkl_fft` is again unsurprisingly similar in the easy cases. It does still get a slight advantage from descriptor caching though. I tested with 8 threads and at that level plan creation took up to 40% of the transform time for the smaller tensor, but still was only a few microseconds of overhead. 
  However, on the harder cases `torch.fft` can actually be much faster than `mkl_fft`. I see 4-6x faster for the larger tensor on `rfftn` and `irfftn` e.g. in one case `mkl_fft` takes 1.9 ms and `torch.fft` takes only 0.3 ms to do the same transform.

**Comment by mruberry** [comment]
These results sound great, @peterbell10! Is there more for performance you'd like to do, or do you think we should declare victory here?

**Comment by peterbell10** [comment]
I'm very happy with the results here. Beating `mkl_fft` and `cupy` at all, let alone by such a large margin in some cases, is more than I was really expecting given we're using the same FFT libraries under the hood.

**Comment by mruberry** [comment]
Although we're still working on a blog post and documentation can always be improved, I believe this issue has addressed its principal goal: creating the torch.fft analogous to NumPy's fft module. Great work @peterbell10! Going forward I think we'll track fft-related issues independently or we should start a new tracker with a new goal.

**Comment by vadimkantorov** [comment]
Is it okay that old rfft supported onesided argument, and the new one only implements onesided=True. For new code, it's not a problem, but for porting it can cause some rewriting troubles

**Comment by mruberry** [comment]
> Is it okay that old rfft supported onesided argument, and the new one only implements onesided=True. For new code, it's not a problem, but for porting it can cause some rewriting troubles. At least the docs should have a mini porting guide

That's a good point. Would you comment on this issue? https://github.com/pytorch/pytorch/issues/49637. That way it'll be clearer how impactful creating such a guide would be.
