### ISSUE TITLE
torch.sparse improvements - tracking issue

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#44634]
This tracking is meant to list the main improvements we'll be focusing on for sparse tensors, and then mapping them to the releases they should land in. _Please note: these are estimates and indicate current prioritization and require effort - don't rely on this, things may still shift around._

The fill-value proposal (https://github.com/pytorch/rfcs/pull/8) has a good description of the different interpretations of sparse tensors: linear algebra (where unspecified values are assumed to be 0), graph algorithms (where sparse structure indicates nodes/edges), and calculus (where non-zero fill values are needed). _The description of application-level use cases for each of those interpretations is still TODO_.

**~1.7~ 1.8 release**

Sparse documentation updates:

- [x] gh-44635: review and update all content on https://pytorch.org/docs/stable/sparse.html --> PR gh-44635
- [ ] Then update the _"This API is in beta, ..."_ warning at the top of the docs. Feature classification may still be "beta", but API should be stable. Add performance-related note instead.
- [ ] Add an [overview using tables](https://github.com/Quansight-Labs/rfcs/blob/pearu/rfc0005/RFC0003-sparse-roadmap/SparseSupportState.md#nnactivation-functions) of _all_ operators in PyTorch, and show whether they support sparse tensors on CPU, on CUDA, and have autograd support.

**1.8 release**

- [ ] CSR/GCS format (see ~https://github.com/pytorch/rfcs/pull/4, gh-44190~, https://github.com/pytorch/rfcs/pull/13, gh-50937, )
- [x] Performance benchmarks for matrix-matrix and matrix-vector ops (dense-sparse, sparse-sparse, and compare to dense-dense) (see gh-51647)
- [x] Benchmarking framework for sparse that's easy to extend when sparse support is added to new operators (see gh-48397)
- [ ] Sparse test infrastructure improvements (see [here for details](https://github.com/pytorch/pytorch/pull/43330#issuecomment-691210906)) - PR gh-49158
- [ ] Add sparse tensor support for all element-wise functions that map 0 to 0 (this is low-hanging fruit)
- [x] https://github.com/pytorch/pytorch/issues/45113
- [ ] https://github.com/pytorch/pytorch/issues/45897
- [ ] https://github.com/pytorch/pytorch/issues/45996
- [ ] https://github.com/pytorch/pytorch/issues/14945
- [ ] Create public API to replace use of `_indices`, `_values`, `_nnz`. See gh-45695.

**1.9 release**

- [ ] fill-value support in COO and GCS sparse tensors (see https://github.com/pytorch/rfcs/pull/8)
- [ ] extend fill-value support to all functions currently supporting sparse

**To (re)assess**

- [ ] Block sparse tensors, gh-9222

**Relevant but blocked**

- [ ] Sparse-Dense elementwise Multiplication, gh-3158

cc @ezyang @gchanan @zou3519 @vincentqb @aocsa @nikitaved @pearu @v0dro @mruberry

**Comment by ngimel** [comment]
I'd suggest adding https://github.com/pytorch/pytorch/issues/14945 to 1.8, performance of `sparse_coo_tensor` call is very bad, we should either fix it or expose unsafe version to python, or, preferably, both.

**Comment by rgommers** [comment]
> I suggest adding #14945 to 1.8, performance of `sparse_coo_tensor` call is very bad, we should either fix it or expose unsafe version to python, or, preferably, both.

Added to the list, and cleared stale assignee so someone else can pick it up.

**Comment by pearu** [comment]
Suggest adding https://github.com/pytorch/pytorch/pull/45695 to 1.8, the PR is about replacing `_indices()` with `indices(coalesce=False)` and introducing `nse` method.

**Comment by pearu** [comment]
Re removing "This API is in beta, ..." statement from the docs: IIUC, the API consists of methods for (i) creating tensors with sparse layout and (ii) accessing format-specific data of a tensor. For COO tensors we have (i) `torch.sparse_coo_tensor` and (ii) `torch.Tensor.{values, indices}`. For other formats (to appear, like GCS), there may be ambiguities with this API, especially, with the (ii) part. So, I think the API needs to remain beta until we have a plan (if and) how PyTorch can be extended to support other storage formats.

**Comment by ngimel** [comment]
For sparse test gaps, see #48807 - no tests for `coalesce` for different dtypes, add_out is tested for bfloat16 specifically instead of a general tests for dtypes https://github.com/pytorch/pytorch/pull/48807/files#diff-bf009aed03d333c6a63253630fed4465ba5f7e025029fe2a22919759c38beb6dL1305

**Comment by rgommers** [comment]
> For sparse test gaps, see #48807 - ...

Cc @vfdev-5, who is looking at structural sparse testing improvements.

**Comment by aocsa** [comment]
And I am working on benchmarking utils  for sparse tensors here, https://github.com/pytorch/pytorch/pull/48397
