### ISSUE TITLE
Autogradpp issue masterthread

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#4619]
- [x] #3971 Index tensor by scalar
- [ ] #3965 at::cat to take in lists of variables
- [x] #3847 Implement .relu on variables
- [x] Find a way to do all the max/min operations without returning a tuple. Instead of `std::get<0>(tensor.max())`, I want to be able to call `tensor.max()`, can be renamed to `maxv` or something...
- [x] Variable.detach_() doesn't do what I think it does, after a var.detach_(), var.defined() won't be true, whereas I expect it to do the autograd detach.
- [ ] Hide or rename TensorList and VariableList in ATen headers, it's too easy for people to use it without knowing that it doesn't have ownership semantics and create strange bugs in their code that are hard to debug.
- [ ] engine.backwards should have an option to disable rethrowing exceptions so we can get a good stack trace on the C++ side. Most errors redirect to [this line](https://github.com/pytorch/pytorch/blob/b37aa2bf0e1d0fc62a7a924c0b50fe06870c1bce/torch/csrc/autograd/engine.cpp#L358), which is not informative.
- [x] ~~Cannot easily take the max of a Tensor and a float. I'm not sure the right way to do it, but I do it with `at::max(tensor, tensor.type().ones({1}) * scalar);`~~ at::clamp_max(tensor, scalar) works
- [ ] #6285
- [ ] #6286
- [ ] #6287
- [x] #6288

**Comment by apaszke** [comment]
Regarding `tensor.max()` I think a better way would be to auto-generate "named-tuples" in C++ (i.e. you can still do `std::get<0>(tensor.max())` OR `tensor.max().values` (we'd generate a struct with two fields that also supports the `get` interface)

**Comment by goldsborough** [comment]
I just took a shot at renaming `TensorList` to simply `ArrayRef<Tensor>`, but it's a pretty deep change in the codegen that doesn't make the resulting code more enjoyable than before. It's not something we really advertise in the public API, and if you look for the definition you'll find `typedef ArrayRef<Tensor> TensorList;` which indicates it's a reference

**Comment by goldsborough** [comment]
For the last point: I think you want `tensor.clamp_max(scalar)`?

**Comment by ebetica** [comment]
Yes, thanks for pointing that out!

**Comment by ebetica** [comment]
@goldsborough @Kaixhin We have a few more issues:

- [ ] AutoGPU is compiled with WITH_CUDA. Instead, it should be in an auto_gpu.cpp file so we do not have to set this macro while compiling it...
- [ ] @ezyang says when you're on device 1 and try to do operations that's valid with device 0 tensors, it will fail. I think the expected behavior is to do the operation and put the result tensor on device 0?
- [ ] Also, a small nit is that there's no toDevice in ATen.

**Comment by goldsborough** [comment]
You mean https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/auto_gpu.h? It looks like it should compile without CUDA -- is that not the case?

I've noticed there's no `toDevice`. @ezyang @colesbury is there a reason why `toDevice` does not exist?

**Comment by gchanan** [comment]
I'm adding better device handling in python currently; we may want to push that stuff to down to ATen if we think it makes sense.

**Comment by gchanan** [comment]
I also don't know what this means:

> says when you're on device 1 and try to do operations that's valid with device 0 tensors, it will fail. I think the expected behavior is to do the operation and put the result tensor on device 0?

can you give a specific example?

**Comment by ebetica** [comment]
@gchanan I think what Ed meant is something like

```c++
at::Tensor x, y;
{
  AutoGPU autogpu(0);
  x = at::CUDA(at::kFloat).randn({100});
  y = at::CUDA(at::kFloat).randn({100});
}
{
  AutoGPU autogpu(1);
  auto z = x * y; // What happens here? Error | Copy z to GPU 1 | keep z on GPU 0
}
```

I'm not sure what the best solution is here.

@goldsborough 

If a third party lib includes auto_gpu.h without doing a `#define WITH_CUDA`, then they try to use it, the things in auto_gpu.h wrapped with `WITH_CUDA` will not compile and it won't work. The solution I can see is to split it out into a .cpp so CUDA is baked into the pytorch .so.

**Comment by gchanan** [comment]
Oh, the issue with the code above is that ATen doesn't have AutoGPU; the above works in PyTorch because we AutoGPU(x) before we call into ATen.

**Comment by goldsborough** [comment]
I see, yes we can move the CUDA parts into a cpp file.

**Comment by goldsborough** [comment]
Btw, I'm not sure it's benefical to dump all issues related to PyTorch C++ into this "master issue". It'd be better to create a `cpp` label and file separate issues. Otherwise our discussions get mixed up, like right now

**Comment by ebetica** [comment]
@gchanan We import Pytorch's autogpu. The equivalent is there if you use cudaSetDevice. The functionality of doing an op for tensors on a different GPU than you are on seems unspecified, and will current error out according to @ezyang, whereas if I'm writing a model, I'd rather probably it be one of the latter two options.

**Comment by ebetica** [comment]
Should C++ also have the same treatment for the max_pool functions?
