### ISSUE TITLE
Tensor expressions type promotion for torch.sin is incorrect after #45733

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#46458]
https://github.com/pytorch/pytorch/pull/45733 adds int->float type promotion to torch.sin(), which is consistent with NumPy's sin() function. Since TE implements its own type promotion, that type promotion is now inconsistent with ATen's. The correct behavior is to promote integer inputs to torch.sin() to the default scalar type before the computation. 

cc @gmagogsfm

**Comment by wconstab** [comment]
@mruberry can you be more specific, are you saying that the TE implementation should promote int to float following numpy, or something else (how to determine the correct 'default scalar type')?

**Comment by gchanan** [comment]
it should promote to the default dtype.  In python land that's `torch.get_default_dtype()`, in C++ it's `at::get_default_dtype()`.

**Comment by gmagogsfm** [comment]
@Krovatkin Is this something you can help look at? Thanks

**Comment by kshitij12345** [comment]
Currently diverging ops
* [ ] `torch.sin` Reference PR #45733 
* [ ] `torch.cos` Reference PR #46706 
* [ ] `torch.tan` Reference PR #46706

**Comment by Krovatkin** [comment]
cc: @ZolotukhinM

**Comment by bertmaher** [comment]
It'd be cool if there were some way to automatically keep fusers' type promotion rules in sync with operators'.  I don't see any straightforward path to that but I'd be interested in ideas.

**Comment by eellison** [comment]
I'm still surprised as to why this failed exactly. We should be using the types from the profiled run, which are kept in sync with the type promotion rules of operators

**Comment by bertmaher** [comment]
It looked to me like the root cause is that tensorexpr doesn't know to cast the `sin` input, so it tries to do `sin((char)...)` and that, I assume, fails to compile.

**Comment by kshitij12345** [comment]
> It looked to me like the root cause is that tensorexpr doesn't know to cast the sin input, so it tries to do sin((char)...) and that, I assume, fails to compile.

Yes that is the case but since `sin(char)` matches both `sin(double)` and `sin(float)` compiler error with ambiguous overload.
https://www.godbolt.org/z/bdvK76

**Comment by bertmaher** [comment]
> > It looked to me like the root cause is that tensorexpr doesn't know to cast the sin input, so it tries to do sin((char)...) and that, I assume, fails to compile.
> 
> Yes that is the case but since `sin(char)` matches both `sin(double)` and `sin(float)` compiler error with ambiguous overload.
> https://www.godbolt.org/z/bdvK76

Oh, I see now, nvcc automatically gives you `float` and `double` overloads but not integer types.  I was assuming this was the cpp standard `sin` which does have an integer overload.  Anyways, fix is easy, should have it up in a few minutes.
