### ISSUE TITLE
Linear algebra GPU backend tracking issue [magma/cusolver/cublas]

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#47953]
## Linear algebra GPU backend tracking issue [magma/cusolver/cublas]

Currently, most GPU linear algebra operators are using MAGMA as their backends. There are only a few linear algebra operators using cusolver/cublas backends. For performance reason, we would like to migrate bad-performed MAGMA linear algebra operator to cusolver/cublas backends if they have a better performance.

This issue is used to track which linear algebra operators currently do **not** use MAGMA as its GPU backend by default, and also track a list of known bad-performed MAGMA operators that could be benefited by cusolver/cublas. Feel free to modify the list and link to this issue if you are aware of any operators.

We welcome contributions to add cusolver/cublas backends to these bad-performed MAGMA operators. Please make sure you add benchmark for your PR, and add heuristics that dispatch the operator to different backends if necessary.

(This issue doesn't track CPU backends.)

### Operators that currently use non-MAGMA backends

For simplicity, we use `b` for batch size, `n` for matrix size. A two-dimensional tensor is considered a batch size 1 matrix.

`torch.inverse` 

- When magma is linked in the build (99.99% cases)
  - `b <= 2`: cusolver
  - `b > 2`: magma
- When magma is not linked in the build (rare case, usually if you build from source without magma lib)
  - `b <= 8` or `n >= 512`: cusolver
  - otherwise: cublas

see 
- https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/MiscUtils.h#L118-L121
- https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/BatchLinearAlgebra.cu#L1231-L1241
- https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu#L49

last updated 1c7c612af049ef4328beb5505ad595a004835a0f, Nov 13, 2020

### Known operators that may have a slow performance with MAGMA

- [ ] torch.svd

### See also
- Linear Algebra tracking issue #42666
- Add cusolver to build, rewrite MAGMA inverse with cusolver #42403

cc @ptrblck @ngimel @vishwakftw @mruberry @IvanYashchuk

**Comment by vishwakftw** [comment]
Cross-posting an issue I created a year ago: https://github.com/pytorch/pytorch/issues/23940

**Comment by heitorschueroff** [comment]
It's worth noting that many batched MAGMA operations are doing illegal memory accesses in some cases (see https://github.com/pytorch/pytorch/issues/26996). I'm currently investigating this but it's another thing to keep in mind besides performance when deciding which ops to transition to cusolver/cublas.

**Comment by IvanYashchuk** [comment]
PyTorch currently uses MAGMA as a backend for most of the linear algebra functions (cuSOLVER is used for `torch.inverse`, and PR for `torch.svd` is in progress).
I've gone through the source code of many functions that PyTorch uses here is the summary.

Excerpt from MAGMA's documentation:
> There are two types of LAPACK-style interfaces. The first one, referred to as the CPU interface, takes the input and produces the result in the CPU's memory. The second, referred to as the GPU interface, takes the input and produces the result in the GPU's memory. In both cases, a hybrid CPU/GPU algorithm is used.
Here is the list of MAGMA functions used in PyTorch that internally transfer the data between GPU and CPU and partially or fully compute the result on CPU.

If the algorithm is "hybrid" CPU-GPU data transfer is performed possibly multiple times and some parts (or all) of the computation are performed on CPU.

Many (maybe all) batched routines seem to be GPU native and not hybrid. It leads to an interesting situation where expanding the input matrix to have the 1xNxN shape greatly improves performance (see for example [the second table](https://github.com/pytorch/pytorch/pull/50269#issuecomment-756704407)).

Maybe single matrix routines should be replaced by the batched ones. However, the source code for `magma_zgetrf_batched` contains an interesting warning
```cpp
if ( m >  2048 || n > 2048 ) {
#ifndef MAGMA_NOWARNING
printf("WARNING batched routines are designed for small sizes. It might be better to use the\n"
       "Native/Hybrid classical routines if you want good performance.\n");
#endif
}
```
Based on this warning maybe all inputs that are smaller than 2048x2048 should use the batched variants. Of course, it should be decided case by case.

All single matrix functions are "hybrid" and internally copy data from GPU, do some computation, and send the data back to GPU. "Some computation" in most of the cases is just calling LAPACK. Some routines are implemented using a blocked algorithm when for some blocks computations on GPU are performed and for the last one or only block calling LAPACK.

`magmaSolve`:
`magma_zgesv_gpu` just calls `magma_zgetrf_gpu` + `magma_zgetrs_gpu`

`magmaLu`:
`magma_zgetrf_gpu` calls `lapackf77_zgetrf`

`magmaLuSolve`:
`magma_zgetrs_gpu`  calls `lapackf77_zlaswp`, `magma_ztrsv` (`cublasZtrsv`), `magma_ztrsm` (`cublasZtrsm`).

`magmaLuNoPiv`:
`magma_zgetrf_nopiv_gpu` just calls `magma_zgetrf_nopiv` (CPU interface version), so there is no point using `magma_zgetrf_nopiv_gpu`.

`magmaGetri`:
`magma_zgetri_gpu` calls `magma_ztrtri_gpu`.
\
`magma_ztrtri_gpu` calls `lapackf77_ztrtri`, `magma_ztrmm` (cublasZtrmm), magma_ztrsm (cublasZtrsm)

`magmaCholeskySolve`:
`magma_zpotrs_gpu` just calls `magma_ztrsv` (`cublasZtrsv`), `magma_ztrsm` (`cublasZtrsm`)

magmaCholesky:
`magma_zpotrf_gpu` which calls Hybrid `magma_zpotrf_LL_expert_gpu`.
diagonal blocks are transferred to CPU and `lapackf77_zpotrf` is used.
For off-diagonal blocks `magma_zherk`, `magma_zgemm`, `magma_ztrsm` are used which are cuBLAS wrappers.

`magmaTriangularSolve`:
`magma_dtrsm` which is just a `cublasZtrsm` wrapper

`magmaGeqrf`:
`magma_zgeqrf_gpu` calls `lapackf77_zgeqrf`, `lapackf77_zlarft` ("for the last or only block" so for small sizes) and `magma_zlarfb_gpu` which uses `magma_zgemm`, `magma_ztrmm`, `magma_zgemm` (cuBLAS wrappers)

`magmaOrgqr`:
`magma_zungqr_gpu` which calls `lapackf77_zungqr` ("for the last or only block" so for small sizes) and `magma_zlarfb_gpu` which uses `magma_zgemm`, `magma_ztrmm`, `magma_zgemm` (cuBLAS wrappers)

`magmaSymeig`:
`magma_zheevd_gpu` calls `lapackf77_zheevd`.
Here is an indicator for which sizes it always calls LAPACK bringing no value over our LAPACK wrappers
```cpp
/* If matrix is very small, then just call LAPACK on CPU, no need for GPU */
if (n <= 128) {
```
calls `magma_zhetrd2_gpu` which calls `lapackf77_zhetrd`, `magma_zlatrd2 `(CPU routine), `magma_zher2k` (which is `cublasZher2k`).
`magma_zhetrd2_gpu` has a condition
```
// use LAPACK for n < 3000
```
Requires an eigenvalues array to live on CPU, forcing PyTorch to transfer data.

`magmaEig`: 
uses `magma_dgeev`, which requires the input and output data to be on the CPU, forcing PyTorch to transfer data.
[Internally it copies blocks to the GPU during certain operations such as the Hessenberg factorization, while other operations like the QR iteration are done entirely on the CPU.](https://icl.cs.utk.edu/magma/forum/viewtopic.php?t=445)

`magmaSvd`:
similarly to `magmaEig` uses CPU routine `magma_dgesdd`, which forces PyTorch to transfer data.

Functions that do not take `magma_queue` argument (so create and destroy `cublasHandle` for each call if cublas is used):
`magmaSolve`, `magmaLu`, `magmaGetri`, `magmaCholeskySolve`, `magmaCholesky`,
`magmaGeqrf`, `magmaOrgqr`, `magmaSymeig`, `magmaLuSolve`

Functions that have only the CPU interface available:
`magmaEig`, `magmaSvd`

`magma_getrf_gpu` (`magmaLu`, `magmaSolve`) and `magma_potrf_gpu` (`magmaCholesky`)
have two modes implemented in MAGMA: `MagmaNative` (GPU only) and `MagmaHybrid` (mix of GPU+CPU). PyTorch calls the `MagmaHybrid` versions.
To call the GPU only version `magma_getrf_native` and `magma_potrf_native` have to be used.

**Comment by v0dro** [comment]
I'd like to take up the points below `torch.lu/lu_solve`. Can @xwang233 please add my handle to the commit?

**Comment by xwang233** [comment]
@v0dro , added. Thank you.

**Comment by xwang233** [comment]
### PyTorch 1.9
For PyTorch 1.9 we're focusing on improving linear algebra performance on GPU and avoiding cross-device synchronizations.
The performance improvements will be achieved with:

* Replacing MAGMA with cuSOLVER

    Almost all MAGMA single matrix functions are "hybrid" and internally copy data from GPU, do some computation on CPU, and send the processed data back to GPU. This makes it very slow for small matrices. We would like to reduce the use of such functions and therefore replace all "hybrid" MAGMA functions with analogues from cuSOLVER. In addition all MAGMA functions that do not take the `magma_queue` argument should also be replaced (they create and destroy cuBLAS handle internally for each call, destruction of cuBLAS handle causes device synchronization #50068).
    MAGMA's batched variants perform the computations only on GPU, but many of them may include undesirable synchronous CUDA calls (for e.g. `cudaMalloc/cudaFree`).

* Adding "unsafe" variants that do not check for error codes

    Almost all linear algebra routines have `info` argument to store error codes indicating whether the operation finished successfully. Most batched MAGMA functions and all cuSOLVER functions accept `info` array residing in GPU memory.
    Currently when we check the values of `info` array residing on GPU we inevitably cause cross-device synchronization.
    The goal here to create necessary backend functions and Python interface will be tweaked later. A tentative proposal is to add an additional kwarg `info=` taking a tensor and filling it in-place with error codes, possibly reusing the storage.

* Avoiding unnecessary copies and work duplication

    It's a great opportunity to revisit existing implementations and fix some obvious flaws. Running the profiling tools might reveal other non-obvious problems.

All cuSOLVER replacements will be in effect only with CUDA version >= 10.1.243 [#45452].
While implementing additional cuSOLVER variants we should think how to organise the code better to allow clear and easy dispatch to MAGMA or cuSOLVER. Every PR should include information on the measured performance differences between cuSOLVER and MAGMA and possibly profiling results to make sure the synchronous calls are avoided as much as possible.

For other discussions on switching MAGMA backend see #4689, #22573, #23940.

MAGMA includes "testing" programs allowing easy benchmarking for inputs of different size ([example link](http://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=1946&p=5249&hilit=slow&sid=c3c17bc0e5d3e3e5a70efe254f851520#p5249)).

A list of tasks enumerated by operator (ordered by priority):

- [ ] `torch.linalg.qr` (@IvanYashchuk )

    Problems: Current implementation of QR decomposition calls the `geqrf` operation twice which is inefficient.
    Both `magmaGeqrf` and `magmaOrgqr` do not take `magma_queue` argument. They are "hybrid" functions. There is no specialized batched version of these routines in MAGMA. Therefore the decision is to add a cuSOLVER dispatch.
    - [ ] Implement `apply_geqrf`, in-place function calling `cusolverDnXgeqrf` (64-bit API).
    - [ ] Implement `apply_geqrf_batched`, calling `cublas<t>geqrfBatched`.
        - [ ] Compare for which inputs a for loop of `cusolverDnXgeqrf` is better than the `Batched` variant.
    - [ ] Combine `apply_geqrf` and `apply_orgqr_cusolver` (`cusolverDn<t>orgqr`) from [#51348](https://github.com/pytorch/pytorch/pull/51348)
    to implement `apply_qr` function.
    - [ ] Implement the necessary dispatch logic for `torch.linalg.qr`.
    - [ ] Ensure that there is no device synchronization due to checking the value of `info`. `info` indicates only invalid arguments to cuSOLVER call, so it should be checked only for the debug build.
    Related functions:
    - [x] `torch.orgqr`
        - PR in progress: https://github.com/pytorch/pytorch/pull/51348
    - [ ] `torch.geqrf` (Requires ATen port or deprecation)
    - [ ] `torch.ormqr` (Requires ATen port or deprecation)

- [ ] `torch.linalg.cholesky` (@xwang233 )

  PR: https://github.com/pytorch/pytorch/pull/53104

    Problems: `magmaCholesky` is a hybrid MAGMA function; it doesn't take `magma_queue` argument. `magmaCholeskyBatched` takes `magma_queue` argument but internally creates 4 more `magma_queue`s, it seems like it's not GPU native function and includes CPU allocations and computation.
    - [x] Implement `apply_cholesky_single`, in-place function calling `cusolverDnXpotrf` (64-bit API).
    - [ ] Implement `apply_cholesky_batched`, in-place function calling `cusolverDn<t>potrfBatched`.
      `cusolverDn<t>potrfBatched` currently has some nan output issue, we will switch to using it after it's fixed
        - [ ] Compare for which inputs a for loop of `cusolverDnXpotrf` is better than `cusolverDn<t>potrfBatched`.
    - [ ] Implement the necessary dispatch logic for `torch.linalg.cholesky`.
    cuSOLVER is used currently only for single matrix input.
    - [x] `torch.cholesky` (batched) #41394 #48996 (MAGMA backend fixed in #50957)

- [ ] `torch.linalg.eigh/eigvalsh` (@IvanYashchuk)

    PR: https://github.com/pytorch/pytorch/pull/53040

    Problems: `magmaSymeig` requires eigenvalues array to reside in CPU memory, forcing PyTorch to transfer GPU tensor to CPU; it doesn't take `magma_queue` argument. There is no specialized batched version in MAGMA.
    - [x] Implement `apply_syevd_single`, calling `cusolverDnXsyevd` (64-bit API).
    - [x] Implement `apply_syevj_single`, calling `cusolverDn<t>syevj`.
        - [x] Compare for which inputs `cusolverDn<t>syevj` is better than `cusolverDnXsyevd`. See https://github.com/pytorch/pytorch/pull/53040#issuecomment-788264724
    - [x] Implement `apply_syevj_batched`, calling `cusolverDn<t>syevjBatched`.
        - [x] Compare for which inputs a for loop of `cusolverDn<t>syevj` is better than `cusolverDn<t>syevjBatched`. See https://github.com/pytorch/pytorch/pull/53040#issuecomment-788264724
        `syevjBatched` is not used yet, because there is a bug in cuSOLVER (see https://github.com/pytorch/pytorch/issues/53879).
    - [x] Implement the necessary dispatch logic for `torch.linalg.eigh/eigvalsh`.
If cuSOLVER is available then it will be used exclusively. `syevj` routine is used only for float32 dtype and matrix sizes 32x32 - 512x512, for all other cases `syevd` is used.
    - [ ] Implement enums to choose the algorithm (divide-and-conquer (`syevd`) or Jacobi (`syevj`)).

- [ ] `torch.lu/lu_solve` (@v0dro )

    Problems: `magmaLu/LuSolve` are hybrid MAGMA functions; don't take `magma_queue` argument. `magmaLu/LuSolveBatched` include `cudaMalloc/cudaFree` calls.
    - [ ] Implement `apply_lu_single`, calling `cusolverDnXgetrf` (64-bit API).
    - [ ] Implement `apply_lu_solve_single`, calling `cusolverDnXgetrs` (64-bit API).
    - [ ] Implement `apply_lu_batched`, calling `cublas<t>getrfBatched`.
    - [ ] Implement `apply_lu_solve_batched`, calling `cublas<t>getrsBatched`.
    - [ ] Compare for which inputs a for loop of `cusolverDnXgetrf/getrs` is better than `Batched` variants.
    - [ ] Implement the necessary dispatch logic for `torch.lu/lu_solve` based on performance benchmarks.
    - [ ] torch.lu/torch.lu_solve (batched) throws CUDA error: invalid configuration error #36921

- [ ] `torch.linalg.solve` (@IvanYashchuk)

    Problems: `magmaSolve` is a hybrid MAGMA function; doesn't take `magma_queue` argument. `magmaSolveBatched` includes `cudaMalloc/cudaFree` calls. `magmaSolve` is calling the same operations as `magmaLu`+`magmaLuSolve`.
    - [ ] Implement `torch.linalg.solve` in terms of calls to new cuSOLVER-based `apply_lu`+`apply_lu_solve`.

- [ ] `torch.linalg.lstsq` (@ivanyashchuk)

    Problems: `magma_zgels_gpu` just calls `geqrf` + `geqrs` operations. All issues of MAGMA's `geqrf` carry over here.
    Only an overdetermined case is supported (m > n).
    - [ ] Implement `apply_gels` using `cusolverDn<t1><t2>gels` (m > n case) (only CUDA 11+).
    Note that `cusolverDn<t1><t2>gels` supports `tensorfloat`, `bfloat` and `half` precisions to be used internally.
    - [ ] Implement lstsq solver using QR decomposition ("gels" driver).
    - [ ] Implement the m < n case using SVD ("gelsd" driver).
    - [ ] Implement `apply_gels_batched`, calling `cublas<t>gelsBatched`.
    PR is progress: https://github.com/pytorch/pytorch/pull/54725
    - [ ] Compare for which inputs a for loop of `cusolverDn<t1><t2>gels` is better than the `Batched` variant.
    - [ ] Implement the necessary dispatch logic for `torch.linalg.lstsq`.

- [ ] `torch.cholesky_solve` (@xwang233 )

    PR in progress: https://github.com/pytorch/pytorch/pull/54315

    Problems: `magmaCholeskySolve` is a hybrid MAGMA function; it doesn't take `magma_queue` argument. `magmaCholeskySolveBatched` internally calls `cudaMalloc/Free` twice.
    - [ ] Implement `apply_cholesky_solve_single`, in-place function calling `cusolverDnXpotrs` (64-bit API).
    - [ ] Implement `apply_cholesky_solve_batched`, in-place function calling `cusolverDn<t>potrsBatched`. Note that only `nrhs=1` is supported.
        - [ ] Compare for which inputs batched MAGMA function is better than `cusolverDn<t>potrsBatched`.
    - [ ] Implement the necessary dispatch logic for `torch.cholesky_solve`.
    - [ ] `info` from `potrs` only shows which input parameter is wrong, no need to perform the error check (if we are sure everything is implemented correctly).

- [ ] `torch.cholesky_inverse` (@xwang233 )

    Issues: `apply_cholesky_inverse` calls batched `apply_cholesky_solve` so all issues carry over here. Performance results comparing against CPU https://github.com/pytorch/pytorch/pull/50269#issuecomment-762963088
    - [ ] Implement the necessary dispatch logic for `torch.cholesky_inverse` to call cuSOLVER-based `cholesky_solve`.

- [x] `torch.triangular_solve` (@IvanYashchuk)

    Problems: `magma_dtrsm` just calls cuBLAS `trsm`.
    - [x] Replace `magma_dtrsm` with corresponding call to cuBLAS.
    - [x] Implement `apply_triangular_solve_batched`, calling `cublas<t>trsmBatched`.
    Performance comparison: https://github.com/pytorch/pytorch/pull/53147#issuecomment-789276910
    PR in progress: https://github.com/pytorch/pytorch/pull/53147

- [ ] `torch.linalg.eig/eigvals` (@ivanyashchuk)

    Problems: `magmaEig` is a hybrid MAGMA function; it doesn't take `magma_queue` argument. There is no specialized batched version in MAGMA. There is no GPU interface variant (no function that takes inputs residing on GPU, however internally GPU is used in computations).
    There is no support for non-symmetric eigenvalue solver in cuSOLVER.
    This is the worst function in the list.

Implement a variant without error code checking (`_no_info`, or `_ex`): (@IvanYashchuk)
- [ ] `torch.linalg.inv`
See https://github.com/pytorch/pytorch/issues/25095, https://github.com/pytorch/pytorch/pull/52046#issuecomment-777390137
- [ ] `torch.linalg.cholesky`
See https://github.com/pytorch/pytorch/issues/34272, https://github.com/pytorch/pytorch/issues/47608
- [ ] `torch.linalg.svd`
- [ ] `torch.linalg.lstsq`
- [ ] `torch.linalg.solve`
- [ ] `torch.lu/lu_solve`
- [ ] `torch.linalg.eigh/eigvalsh`

If you are planning to work on the specific task please put your name next to the task or leave a comment below.

**Comment by IvanYashchuk** [comment]
@xwang233 are you suggesting that it's better to keep the list of tasks in a separate issue?
I think the comment can be easily lost that's why the list of tasks was in the issue description.

**Comment by secondspass** [comment]
Out of curiosity, is the goal to remove the MAGMA dependency entirely? Right now magma needs to be built for a pytorch source build so in the future we won't have to do that?

**Comment by IvanYashchuk** [comment]
There are (batched) functions where MAGMA is faster than cuSOLVER and there are also functions that are available in MAGMA and not in cuSOLVER (for example `torch.linalg.eig`).
Right now it's possible to build PyTorch without MAGMA (`USE_MAGMA=0`) and still get the majority of functions from `torch.linalg` working. So there are currently no plans on removing the MAGMA dependency from official builds, but if you'd like to build PyTorch yourself without it, you're free to do so.
