### ISSUE TITLE
release 0.3.1 checklist

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#4821]
- [x] cherry-pick needed fixes (see https://github.com/pytorch/pytorch/pulls?q=is%3Apr+is%3Aclosed+label%3A0.3.1 for a list)
- [x] add warning code to deprecate old gpus: https://github.com/pytorch/pytorch/issues/4841
- [x] Update dockerfiles to cudnn 7005, cuda 9.1
   - build magma-cuda91
- [x] build wheels
  - [x] linux
  - [x] osx
- [x] build conda binaries
  - [x] linux
  - [x] osx
- [x] write release notes
- [x] sanity checks / smoke tests
- [x] test community repos
- [x] push docs
  - [x] update versions.html
  - [x] sed the version name
- [x] update website commands
   [x] add old wheel links to "old versions" page

**Comment by lanpa** [comment]
May I suggest #4524 and #4558 ?

**Comment by lantiga** [comment]
I backported scopes to `v0.3.1` (https://github.com/lantiga/pytorch/tree/scopes_0.3.1_backport), but I've still got one test failing with the ONNX pass. Will fix asap.

**Comment by lantiga** [comment]
Done /cc @soumith

**Comment by ezyang** [comment]
Might be good to grab some ONNX fixes if we haven't already; c.f. #5146
