### ISSUE TITLE
Operator and module tests in PyTorch 1.10 tracker

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#50006]
This issue tracks work related to improving PyTorch's test suite. 

**Deprecations**

- [ ] Remove assertEqualIgnoreTypes (see https://github.com/pytorch/pytorch/issues/38095)

**Test Suites needing updates**
- [ ] test_binary_ufuncs.py
  - [ ] needs structured "forward testing" analogous to test_unary_ufuncs.py
  - [ ] needs automated type promotion testing
- [ ] test_reductions.py
  - [ ] needs structured "forward testing" analogous to test_unary_ufuncs.py  (https://github.com/pytorch/pytorch/issues/49746)

**OpInfo-related improvements**
- [ ] Fix ops failing test_out

**General Framework Improvements**
- [ ] Re-run failing CUDA tests with CUDA launch blocking (https://github.com/pytorch/pytorch/issues/49023)
- [ ] Add an option to run only tests for a specific device type (https://github.com/pytorch/pytorch/issues/44159)
- [ ] Debug and fix test suite memory issues (https://github.com/pytorch/pytorch/issues/43677)

**NN Module Testing**
- [x] Add "ModuleInfos" analogous to OpInfos to facilitate systemic testing
- [ ] Refactor test_nn.py to be fewer than 10k lines (https://github.com/pytorch/pytorch/issues/42847)
- [ ] Reduce the time taken by test_ReplicationPad3d (https://github.com/pytorch/pytorch/issues/38190)
- [ ] Reduce the time taken by test_LocalResponseNorm_3d_custom_params (https://github.com/pytorch/pytorch/issues/38189)
- [ ] Reduce the time taken by test_interpolate_nearest_scale_3d (https://github.com/pytorch/pytorch/issues/38188)
- [ ] Review convolution testing (https://github.com/pytorch/pytorch/issues/6135)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
Closing this issue in favor of individual issues.
