### ISSUE TITLE
NumPy Compatibility tracking issue

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#50344]
This issue is a roll-up of NumPy Compatibility-related discussion, requests and issues.

PyTorch has a goal of being familiar to NumPy and SciPy users, and interoperating with libraries that work with NumPy-compatible tensors. Some "sub-trackers" for this tracker are https://github.com/pytorch/pytorch/issues/38349, where requests for functions in the numpy namespace are tracked, https://github.com/pytorch/pytorch/issues/42175, where the development of a NumPy-compatible fft module is tracked, and https://github.com/pytorch/pytorch/issues/42666, where the development of a NumPy-compatible linalg module is tracked. Unlike those more detailed trackers, this one is intended for significant cross-cutting tasks, not individual functions or bugs.

**Module Compatibility**
- [ ] Implement torch.fft, compatible with np.fft (https://github.com/pytorch/pytorch/issues/42175)
- [ ] Implement torch.linalg, compatible with np.linalg (https://github.com/pytorch/pytorch/issues/42666)
- [ ] Implement "missing" functions in the NumPy namespace (https://github.com/pytorch/pytorch/issues/38349)
- [ ] Implement torch.special for existing PyTorch functions analogous to scipy.special functions

**Doc Improvements**
- [ ] Create a NumPy Compatibility note (https://github.com/pytorch/pytorch/issues/48628)
- [ ] RFC: Update PyTorch function documentation to identify the corresponding NumPy function (https://github.com/pytorch/pytorch/issues/50343)
