### ISSUE TITLE
Tracking issue for pytest-related improvements

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#52984]
xref https://github.com/pytorch/pytorch/issues/11578#issuecomment-787485279 for the current status on using `pytest`.

- [ ] improve the pytest output on test failures (probably through settings in a `pytest.ini` in the root of the repo):
    - [ ] make it not print docstrings (gh-3791)
    - [ ] make tracebacks shorter (`--tb=short` is probably about right, see [the pytest docs](https://docs.pytest.org/en/stable/usage.html?highlight=traceback#modifying-python-traceback-printing))
    - [ ] address the issue where `pytest` suppresses `stderr` on startup (gh-39503, will likely also address gh-46276). 
- [ ] resolve open test running issues
    - [ ] `distributed` tests:
        - [ ] gh-41337, "distributed tests fail with pytest"
        - [ ] gh-46272, "`test_distributed_*` does not work with `run_test.py -i` option"
    - [ ] gh-39523, "[JIT] Cannot directly run tests in `test_module_interface`"
- [ ] ensure `pytest` is installed in all CI jobs. `hypothesis` is a hard test dependency, so just make sure to treat `pytest` the same as `hypothesis` and that should be enough.
- [ ] Compare `unittest` and `pytest` runs, ensuring the number of tests run matches (or differences make sense) and that test time is equivalent or better with `pytest`.
- [ ] Improve documentation
    - [ ] Write some docs on how to integrate `pytest`-based tests into `test/run_test.py` and on how to start using `pytest` features in existing test files (only if there's a good reason to do so of course).
    - [ ] Update https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#unit-testing

**Comment by mruberry** [comment]
A few more questions (cc @malfet)

- Can we use pytest in our internal tooling?
- Are there any pytest features that don't compose with our own test framework for instantiating test variants? (parameterize, subtest...?)
- What due diligence do we need to do with our partners who also run PyTorch's test suite?

**Comment by walterddr** [comment]
partial answer - AFAIK we already ran some pytest internally, although it might need some tweak on buck targets

**Comment by rgommers** [comment]
> What due diligence do we need to do with our partners who also run PyTorch's test suite?

When we changed `hypothesis` to a hard dependency, nothing was needed here. What kind of partners or special cases are you thinking about?

**Comment by mruberry** [comment]
> > What due diligence do we need to do with our partners who also run PyTorch's test suite?
> 
> When we changed `hypothesis` to a hard dependency, nothing was needed here. What kind of partners or special cases are you thinking about?

NVIDIA and the PyTorch/XLA project, for example. I don't think switching to pytest is likely to be an issue for them but we might as well find out in advance.

**Comment by ezyang** [comment]
I recently wanted to use pytest to run larger portions of the test suite and I ran into a number of problems:

* Many test files just fail during collection (I have a PR coming to fix this)
* Many test files have side effects as part of simply running the top level Python module, and then those side effects leak into other tests

**Comment by ezyang** [comment]
cc @iramazanli

**Comment by mruberry** [comment]
Some thoughts from our offline meeting:

- if we make pytest work well, what's to stop it from regressing? Would a pytest build be feasible? Is there some other way we can validate pytest works properly?
- NumPy also struggles with generating readable names for tests involving tensors as inputs, so the appeal of parameterize or subtest might be more limited than initially thought
- to avoid requiring pytest or unittest, we could look at implementing our own parameterize; there are some tests that would benefit from this
- an update to the Developer FAQ explaining how we generate the cross product of device and dtype might be helpful
- the benefit of running CI in unittest vs pytest was ???, if we want to switch the CI to pytest and not just make pytest a good experience for developers we should be clearer about the difference we expect to see
- one pytest feature of interest for developers is running tests in parallel, but our tests are not safe to run in parallel: can we do something to improve that situation?

**Comment by ezyang** [comment]
The reason I want to run pytest, personally, is three features:

1. The `-k` flag lets me regex for specific tests to run
2. pytest can run multiple test files, which is very helpful if I'm working on a big cross-cutting change (e.g., adding a new device)
3. The `--sw` flag lets me run the test suite until it fails, fix that problem, *and then pick up where I left off* (without uselessly rerunning tests that previously passed and are unlikely to have broken)

**Comment by jeffdaily** [comment]
> * one pytest feature of interest for developers is running tests in parallel, but our tests are not safe to run in parallel: can we do something to improve that situation?

I just looked into `--run-parallel` the last few days.  I had started a draft PR to do the work of using it, but it quickly demonstrated that this feature wasn't ready.  But there are at least some good commits in there that get us closer if someone was curious #53426.

I did an initial perf study of just test_autograd.py.  It shows that adding parallelism for CPU tests is not helpful, probably because the CPU is itself the compute device so you're not really enabling better resource utilization.  GPU test performance, on the other hand, improved quite well.  But that would mean perhaps adding a GPU-specific `--run-parallel-gpu` option.  But this also implies a better separation of the CPU and GPU tests.

CPU | sec
-- | --
1 | (missing, sorry)
2 | 253
4 | 225
8 | 251
16 | 250
32 | 233
64 | 234

GPU | sec 
-- | --
1 | 2572
2 | 1385
4 | 745

**Comment by zou3519** [comment]
Regarding parameterize:

I prototyped [a parameterize](https://github.com/zou3519/functorch/blob/a466cd1b8c1a5bebd2a5113d26942d2720bf7ffb/test/common.py#L6-L53) that (mostly) composes with PyTorch's testing suite because I wanted to use it for some testing. AFAIK there are a few concerns with using pytest's parameterize:
- It might not compose with PyTorch's testing suite (I haven't verified this)
- It doesn't generate readable names
- we don't want to take a dependency on pytest (My two cents are that pytest is really useful, especially for [the reasons](https://github.com/pytorch/pytorch/issues/52984#issuecomment-795947019) that @ezyang enumerated above)

The parameterize prototype is interesting because (1) I think we can make it compose fully with PyTorch's testing suite and (2)  it [requires the user to pass names](https://github.com/zou3519/functorch/blob/a466cd1b8c1a5bebd2a5113d26942d2720bf7ffb/test/common.py#L14-L15) rather than autogenerate them, alleviating the unreadable autogenerated test problem
