### ISSUE TITLE
Tracker: torch.testing

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#53618]
This issue tracks tasks related to the creation of a torch.testing module. The goals of this module are:

- to be compatible with [NumPy's testing module](https://numpy.org/doc/stable/reference/routines.testing.html)
- to support libraries built on PyTorch running their tests using a variety of test runners (e.g. unittest, pytest, ...)
- to facilitate writing tests in PyTorch's own test suite
- to expose useful components of PyTorch's test generation framework (if any)

This issue is related to but distinct from https://github.com/pytorch/pytorch/issues/50006, which tracks improvements to PyTorch's own test suite, and not the development of a public torch.testing module.

**Tasks**

- [x] Update make_tensor with support for broader ranges and document as part of torch.testing
- [ ] Expose available device types in torch.testing
- [ ] Determine which functions (if any) from NumPy's testing module should appear in torch.testing
- [ ] Identify which other common test suite methods, if any, should be ported to torch.testing (e.g., testing for warnings, decorators for memory requirements, ...) (and update this [developer wiki article](https://github.com/pytorch/pytorch/wiki/Writing-operator-tests-in-PyTorch-1.9#common-test-utilities) to point to them)
- [ ] Determine if components of PyTorch's test generation framework can be usefully exposed as part of torch.testing
- [ ] Update PyTorch's own test suite to use the components in torch.testing

cc @NicolasHug

**Comment by mruberry** [comment]
Update from offline meeting:

- @pmeier and @mattip prepared a gist https://gist.github.com/pmeier/6adf155f46f0e342abb812dbf4219aea
- we identified 4 functions to add to torch.testing: assert_tensor_{equal, allclose}, assert_{equal, allclose}
- one challenge with reconciling PyTorch's assert equal behavior vs. NumPy's is that PyTorch compares complex tensors differently than NumPy
- we want want to be sure to continue supporting comparisons between sparse and quantized tensors, too
- we want to continue supporting scalar x scalar comparisons and comparisons between Python datastructures like dicts that contain scalars and/or tensors
- we intend to implement torch.testing exclusively in Python (at least for now)
- PyTorch's assertEqual also supports several kwargs for controlling dtype and device comparisons, it's not yet clear how these should be handled (and maybe a new one for comparing strides should be added!)
- one option to unblock development is to implement the most restrictive behavior and not support complex in an initial PR, then add complex support and kwargs for controlling comparisons later
- tests for torch.testing functions should be added to test_testing.py
- we probably want to refactor PyTorch's existing assertEqual and _compareTensors functions (see code snippet)

https://github.com/pytorch/pytorch/blob/5658ab5f778ca999521e7a98a9572251c56f2aaf/torch/testing/_internal/common_utils.py#L1014

- we likely want to continue populating default atol and rtol based on the dtype of the objects being compared
- we should review our coercion behavior vs. NumPy's. In particular, is 1 == [1] == tensor(1)?
