### ISSUE TITLE
Tracker: Better testing support for non-native device types

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#53849]
PyTorch's test framework aims to be extensible with new device dtypes, whether they're native device types (CPU, CUDA, meta) or non-native (e.g. XLA). This tracking issue is for tasks related to improving this extensibility.

**Tasks**

- [x] Add a @skipXLA decorator. Tests currently use @onlyOnCPUAndCUDA to skip XLA, but this also skips other device types, like meta. We should consider removing the @onlyOnCPUAndCUDA decorator.
- [x] Require @dtypes be specified when a more specific dtypes decorator, like @dtypesIfCUDA, is used. This will prevent the test suite from trying to run tests with no dtypes for a particular device.
- [x] Update assertion checking to be relaxed for non-native device types. For example, requiring only that the non-native device type throws an exception vs. a particular exception with a particular message.
- [ ] Promote the NOT_IMPL pattern implemented in https://github.com/pytorch/pytorch/pull/53682 to make it easier for device types to programmatically skips tests they don't support.

cc @mruberry @VitalyFedyunin @walterddr @ezyang @JackCaoG

**Comment by mruberry** [comment]
Closing this as the last issue has been mooted
