### ISSUE TITLE
[JIT] Shape Analysis Small Features Tracking Issue

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#54606]
## 🚀  Feature 

Soon, I am going to post a RFC about shape analysis so keep your ears peeled on that... Before then, creating a meta-issue of small off the main path fixes that will help.

Cleanup Passes return boolean to indicate if they successfully made a change
- [x] Constant Propagation (@eellison )
- [x] CommonSubexpression Elimination (@krovatkin)
- [x] RemoveListMutation (@penguinwu) 
- [x] PeepholeOptimizeListIdioms (@penguinwu )
- [x] UnrollConstantLoops (@penguinwu )

Cleanup Passes Lazily Initialize AliasDb when it is first needed 
- [x] Constant Propagation (@eellison )
- [x] RemoveListMutation (@penguinwu )
- [x ] CommonSubexpression Elimination (@krovatkin)
- [ ] EliminateDeadCode (maybe do this one a bit later)(@desertfire)

Cleanup Passes Only Call EliminateDeadCode If they successfully made a change 
- [x] Constant Propagation (@eellison )

Other Misc:
- [x] Separate Out non-Tensor (Scalar Peephole Optimizations?) As a Separate Pass so we dont need to invoke Tensor optimizations as part of the Peephole, and add in that `v: Bool == Value *; v == v` -> True and `v != v` -> False(@eellison )
- [x] Add Verbosity Option to type.cpp to dump symbolic shapes (@penguinwu)
- [x] In OptimizeListIdioms add handling for `assert len(x) == 4; ... y = len(x)`, return True if pass made a change successfuly (@eellison ) 
- [x] add pass that will infer output of `y if x == 1 else x` to be `x` if `y == 1`, and `assert x == 4; y = x + x` (this ones a little trickier and not immediately needed, consult with me before starting maybe) (@eellison )

cc @gmagogsfm

**Comment by eellison** [comment]
Example PR for cleanup passes: https://github.com/pytorch/pytorch/pull/54640

**Comment by eellison** [comment]
@Krovatkin @penguinwu  I think `Separate Out non-Tensor...` and `OptimizeListIdioms add ...` are two good starter tasks

**Comment by eellison** [comment]
Please message me if you have any questions as your are implementing !

**Comment by penguinwu** [comment]
`EliminateDeadCode` is also often called as part of cleanup after a transformation. With a bool indicating change, we may guard some of the invocations of `EliminateDeadCode` as well (e.g., UnrollLoops in loop_unrolling.cpp).
