### ISSUE TITLE
[Tracking] Remove unneeded BC duplicates from native_functions.yaml

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#55941]
This issue is for tracking duplicate `native_functions.yaml` entries that were added for BC purposes and removing them once it's safe to do so.

- [ ]  [upsample_*](https://github.com/pytorch/pytorch/blob/85b97e449dabb5703cb09effb58f8e4d21afd5f9/aten/src/ATen/native/native_functions.yaml#L7882)
- [ ] [batch_norm_*](https://github.com/pytorch/pytorch/blob/85b97e449dabb5703cb09effb58f8e4d21afd5f9/aten/src/ATen/native/native_functions.yaml#L2703)
- [ ] [quantile*](https://github.com/pytorch/pytorch/blob/85b97e449dabb5703cb09effb58f8e4d21afd5f9/aten/src/ATen/native/native_functions.yaml#L6076-L6077)
