### ISSUE TITLE
Compiler warnings tracking task

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#55952]
PyTorch outputs a bunch of compile warnings which make it hard to sift through build logs. This task lists them out and their status

## External

- [ ] onnx (this is fixed on master, need to update the submodule)
```
[2805/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/serialization/export.cpp.o
In file included from ../third_party/onnx/onnx/defs/shape_inference.h:4,
                 from ../third_party/onnx/onnx/defs/schema.h:24,
                 from ../third_party/onnx/onnx/checker.h:7,
                 from ../torch/csrc/jit/serialization/export.cpp:20:
../third_party/onnx/onnx/proto_utils.h: In instantiation of ‘bool onnx_torch::ParseProtoFromBytes(Proto*, const char*, size_t) [with Proto = onnx_torch::ModelProto; size_t = long unsigned int]’:
../torch/csrc/jit/serialization/export.cpp:952:77:   required from here
../third_party/onnx/onnx/proto_utils.h:34:34: warning: ‘void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)’ is deprecated: Please use the single parameter version of SetTotalBytesLimit(). The second parameter is ignored. [-Wdeprecated-declarations]
   coded_stream.SetTotalBytesLimit((2048LL << 20) - 1, 512LL << 20);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:23,
                 from third_party/onnx/onnx/onnx-ml.pb.h:2,
                 from ../third_party/onnx/onnx/onnx_pb.h:50,
                 from ../torch/csrc/jit/serialization/onnx.h:3,
                 from ../torch/csrc/jit/serialization/export.cpp:17:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:397:8: note: declared here
   void SetTotalBytesLimit(int total_bytes_limit, int) {
        ^~~~~~~~~~~~~~~~~~
```

- [ ] pthreadpool (once https://github.com/Maratyszcza/pthreadpool/pull/15 lands, we can add a macro to ignore these: #55950)

```
[959/3019] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vscaleextexp/gen/avx512f-p5-scalef-x144.c.o
In file included from ../third_party/XNNPACK/include/xnnpack.h:15:0,
                 from ../third_party/XNNPACK/src/xnnpack/params.h:15,
                 from ../third_party/XNNPACK/src/xnnpack/vscaleextexp.h:11,
                 from ../third_party/XNNPACK/src/f32-vscaleextexp/gen/avx512f-p5-scalef-x144.c:16:
../third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_3d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_4d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Internal

- [ ] `tensor_flatten.cpp`

```
[2756/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/utils/tensor_flatten.cpp.o
In file included from ../torch/csrc/utils/tensor_flatten.cpp:1:
../torch/csrc/utils/tensor_flatten.h: In member function ‘at::DeprecatedTypeProperties& torch::utils::TensorGroup::type()’:
../torch/csrc/utils/tensor_flatten.h:44:28: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: 
Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replaceme
nt. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), 
use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     return tensors[0].type();
                            ^
In file included from ../aten/src/ATen/Tensor.h:3,
                 from ../aten/src/ATen/Context.h:4,
                 from ../aten/src/ATen/ATen.h:9,
                 from ../torch/csrc/utils/tensor_flatten.h:5,
                 from ../torch/csrc/utils/tensor_flatten.cpp:1:
aten/src/ATen/core/TensorBody.h:334:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
../torch/csrc/utils/tensor_flatten.cpp: In function ‘std::vector<torch::utils::TensorGroup> torch::utils::take_tensors(at::Te
nsorList, size_t, bool)’:
../torch/csrc/utils/tensor_flatten.cpp:31:43: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated
: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replace
ment. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type()
, use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     auto& type_group = groups[tensor.type().id()];
                                           ^
In file included from ../aten/src/ATen/Tensor.h:3,
                 from ../aten/src/ATen/Context.h:4,
                 from ../aten/src/ATen/ATen.h:9,
                 from ../torch/csrc/utils/tensor_flatten.h:5,
                 from ../torch/csrc/utils/tensor_flatten.cpp:1:
aten/src/ATen/core/TensorBody.h:334:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
```

- [ ] `QuantizedLinear.cpp`

```
[2355/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/QuantizedLinear.cpp.o
../aten/src/ATen/native/QuantizedLinear.cpp: In function ‘at::Tensor at::native::fbgemm_linear_int8_weight_fp32_activation(co
nst at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const c10::Scalar&, const c10::Scalar&, const at::T
ensor&)’:
../aten/src/ATen/native/QuantizedLinear.cpp:113:69: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = 
fbgemm::PackBMatrix<signed char>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_sc
ript_custom_classes.html [-Wdeprecated-declarations]
       cpp_custom_type_hack::cast<fbgemm::PackBMatrix<int8_t>>(packed);
                                                                     ^
In file included from ../aten/src/ATen/native/QuantizedLinear.cpp:14:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/QuantizedLinear.cpp:113:69: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = 
fbgemm::PackBMatrix<signed char>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_sc
ript_custom_classes.html [-Wdeprecated-declarations]
       cpp_custom_type_hack::cast<fbgemm::PackBMatrix<int8_t>>(packed);
                                                                     ^
In file included from ../aten/src/ATen/native/QuantizedLinear.cpp:14:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/QuantizedLinear.cpp: In function ‘at::Tensor at::native::fbgemm_pack_quantized_matrix(const at::Tenso
r&)’:
../aten/src/ATen/native/QuantizedLinear.cpp:298:71: warning: ‘at::Tensor at::cpp_custom_type_hack::create(std::unique_ptr<_Tp
>, c10::TensorOptions) [with T = fbgemm::PackBMatrix<signed char>]’ is deprecated: Use custom classes instead: https://pytorc
h.org/tutorials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
   return cpp_custom_type_hack::create(std::move(ptr), weight.options());
                                                                       ^
In file included from ../aten/src/ATen/native/QuantizedLinear.cpp:14:
../aten/src/ATen/cpp_custom_type_hack.h:83:8: note: declared here
 Tensor create(std::unique_ptr<T> ptr, TensorOptions options) {
        ^~~~~~
../aten/src/ATen/native/QuantizedLinear.cpp:298:71: warning: ‘at::Tensor at::cpp_custom_type_hack::create(std::unique_ptr<_Tp
>, c10::TensorOptions) [with T = fbgemm::PackBMatrix<signed char>]’ is deprecated: Use custom classes instead: https://pytorc
h.org/tutorials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
   return cpp_custom_type_hack::create(std::move(ptr), weight.options());
                                                                       ^
In file included from ../aten/src/ATen/native/QuantizedLinear.cpp:14:
../aten/src/ATen/cpp_custom_type_hack.h:83:8: note: declared here
 Tensor create(std::unique_ptr<T> ptr, TensorOptions options) {
        ^~~~~~
../aten/src/ATen/native/QuantizedLinear.cpp: In function ‘at::Tensor at::native::fbgemm_pack_gemm_matrix_fp16(const at::Tenso
r&)’:
../aten/src/ATen/native/QuantizedLinear.cpp:386:54: warning: ‘at::Tensor at::cpp_custom_type_hack::create(std::unique_ptr<_Tp
>, c10::TensorOptions) [with T = c10::intrusive_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: http
s://pytorch.org/tutorials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
       std::move(unique_ptr_wrapper), weight.options());
                                                      ^
In file included from ../aten/src/ATen/native/QuantizedLinear.cpp:14:
../aten/src/ATen/cpp_custom_type_hack.h:83:8: note: declared here
 Tensor create(std::unique_ptr<T> ptr, TensorOptions options) {
        ^~~~~~
../aten/src/ATen/native/QuantizedLinear.cpp:386:54: warning: ‘at::Tensor at::cpp_custom_type_hack::create(std::unique_ptr<_Tp
>, c10::TensorOptions) [with T = c10::intrusive_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: http
s://pytorch.org/tutorials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
       std::move(unique_ptr_wrapper), weight.options());
```

 - [ ] `RNN.cpp`

```
[2410/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/RNN.cpp.o
../aten/src/ATen/native/RNN.cpp: In function ‘c10::List<c10::intrusive_ptr<at::native::{anonymous}::CellParamsBase> > at::nat
ive::{anonymous}::gather_quantized_params_dynamic(c10::List<at::Tensor>)’:
../aten/src/ATen/native/RNN.cpp:596:47: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = c10::intrusi
ve_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_scri
pt_custom_classes.html [-Wdeprecated-declarations]
             static_cast<at::Tensor>(params[i]));
                                               ^
In file included from ../aten/src/ATen/native/RNN.cpp:6:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/RNN.cpp:596:47: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = c10::intrusi
ve_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_scri
pt_custom_classes.html [-Wdeprecated-declarations]
             static_cast<at::Tensor>(params[i]));
                                               ^
In file included from ../aten/src/ATen/native/RNN.cpp:6:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/RNN.cpp:599:51: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = c10::intrusi
ve_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_scri
pt_custom_classes.html [-Wdeprecated-declarations]
             static_cast<at::Tensor>(params[i + 1]));
                                                   ^
In file included from ../aten/src/ATen/native/RNN.cpp:6:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/RNN.cpp:599:51: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor&) [with T = c10::intrusi
ve_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tutorials/advanced/torch_scri
pt_custom_classes.html [-Wdeprecated-declarations]
             static_cast<at::Tensor>(params[i + 1]));
                                                   ^
In file included from ../aten/src/ATen/native/RNN.cpp:6:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
```

- [ ] `qlinear_unpack.cpp`

```
[2436/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp.o
../aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp: In static member function ‘static std::tuple<at::Tensor, c10::optio
nal<at::Tensor> > at::native::{anonymous}::QLinearUnpackWeightInt8Legacy::run(const at::Tensor&)’:
../aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp:113:73: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor
&) [with T = c10::intrusive_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tuto
rials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
                c10::intrusive_ptr<LinearPackedParamsBase>>(packed_weight)
                                                                         ^
In file included from ../aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp:2:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
../aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp:113:73: warning: ‘T& at::cpp_custom_type_hack::cast(const at::Tensor
&) [with T = c10::intrusive_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes instead: https://pytorch.org/tuto
rials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
                c10::intrusive_ptr<LinearPackedParamsBase>>(packed_weight)
                                                                         ^
In file included from ../aten/src/ATen/native/quantized/cpu/qlinear_unpack.cpp:2:
../aten/src/ATen/cpp_custom_type_hack.h:69:4: note: declared here
 T& cast(const Tensor& packed) {
    ^~~~
```

- [ ] `qlinear_prepack.cpp`

```
[2438/3029] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp.o
../aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp: In static member function ‘static at::Tensor at::native::{anonymou
s}::QLinearPackWeightInt8Legacy::run(at::Tensor, c10::optional<at::Tensor>)’:
../aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp:273:70: warning: ‘at::Tensor at::cpp_custom_type_hack::create(std::
unique_ptr<_Tp>, c10::TensorOptions) [with T = c10::intrusive_ptr<LinearPackedParamsBase>]’ is deprecated: Use custom classes
 instead: https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html [-Wdeprecated-declarations]
       return cpp_custom_type_hack::create(std::move(wrapped), options);
                                                                      ^
In file included from ../aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp:2:
../aten/src/ATen/cpp_custom_type_hack.h:83:8: note: declared here
 Tensor create(std::unique_ptr<T> ptr, TensorOptions options) {
        ^~~~~~
```

**Comment by skyline75489** [comment]
wait, am I the only one seeing all the warnings in #55034? :/

**Comment by driazati** [comment]
Not at all, I didn't mean this to be a complete list (and it definitely isn't right now), there's probably a bunch of things missing
