### ISSUE TITLE
Migrate build/test jobs from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#57686]
# Feature Parity

Migration Progress Burndown
https://metrics.pytorch.org/d/gJaYvuInk/circleci-migration-progress?orgId=1

## Feature Parity to match CircleCI

- [x] cancel redundant workflows #54689 @janeyx99
- [x] check and rename all `*_py3_*` without a python subversion #57770 @samestep
- [x] `tools/print_test_stats.py` #57647 @samestep
- [x] docker base image building / pushing (reference PR for CircleCI: https://github.com/pytorch/pytorch/pull/40950) #58299 @samestep
- [x] sharding (tracking issue): https://github.com/pytorch/pytorch/issues/59401
- [x] periodic jobs: #61003, #61732, #61774 @janeyx99
- [x] SSH access to FB users @seemethere
- [ ] Jump to error (i.e. either parse test result's xml or grep error pattern) from lengthy logs
- [ ] GitHub label dispatch management (and consolidate the usage of `ci/*` and `ciflow/*` labels
- [ ] Ephemeral runners for isolated runner infrastructure (important to lower the infra flakiness)
- [ ] Mac/iOS support
- [ ] Partnership login and control over GitHub runners (e.g. conducting self-serving releases)

## Feature Advantage in GHA
- [x] Squid proxy for network stability inside AWS runners
- [x] Faster and no-cost ECR docker registry data transfer
- [x] CIFlow only works for GHA for now 
- [x] AMIs to bake many dependencies into the runners instead of setup for every CI 

## Jobs may need to stay in CircleCI/Jenkins before new updates
- [ ] binary jobs
- [ ] nightly jobs
- [ ] release jobs
- [ ] LTS jobs
- [ ] Jenkins AMD/ROCM jobs
- [ ] SSH debugging support for non-FB users (due to the access limitation of GHA runners, and currently it's gated by VPN)

# Jobs to migrate

Format
```
- GHA job name
  - CircleCI job name
  - PR <@author> (if any)
```

- [ ] pytorch-ios-12.0.0-arm64
  - pytorch_ios_12_0_0_arm64_build
- [ ] pytorch-ios-12.0.0-arm64-custom
  - pytorch_ios_12_0_0_arm64_custom_build
- [ ] pytorch-ios-12.0.0-arm64-lite-interpreter
  - pytorch_ios_12_0_0_arm64_lite_interpreter_build
- [ ] pytorch-ios-12.0.0-arm64-metal
  - pytorch_ios_12_0_0_arm64_metal_build
- [ ] pytorch-ios-12.0.0-x86_64
  - pytorch_ios_12_0_0_x86_64_build
- [ ] pytorch-ios-12.0.0-x86_64-lite-interpreter
  - pytorch_ios_12_0_0_x86_64_lite_interpreter_build
- [x] pytorch-bazel
  - docker-pytorch-linux-xenial-py3.6-gcc7 • pytorch_bazel_build • pytorch_bazel_test
  - #61039 @rsemenov
- [ ] pytorch-linux-bionic-py3.6-clang9-noarch
  - docker-pytorch-linux-bionic-py3.6-clang9 • pytorch_linux_bionic_py3_6_clang9_noarch_build • pytorch_linux_bionic_py3_6_clang9_noarch_test
  - #60889 @driazati
- [x] pytorch-linux-bionic-py3.8-gcc9-coverage
  - docker-pytorch-linux-bionic-py3.8-gcc9 • pytorch_linux_bionic_py3_8_gcc9_coverage_build • pytorch_linux_bionic_py3_8_gcc9_coverage_test1 • pytorch_linux_bionic_py3_8_gcc9_coverage_test2
  - #61050 @imaginary-person
- [ ] pytorch-linux-bionic-rocm3.9-py3.6
  - docker-pytorch-linux-bionic-rocm3.9-py3.6 • pytorch_linux_bionic_rocm3_9_py3_6_build
  - #60889 @driazati
- [ ] pytorch-linux-backward-compatibility-check
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_linux_backward_compatibility_check_test
- [ ] pytorch-linux-xenial-py3.6-clang5-android-ndk-r19c-x86_32
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
- [ ] pytorch-linux-xenial-py3.6-clang5-android-ndk-r19c-x86_64
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
- [ ] pytorch-linux-xenial-py3.6-clang5-android-ndk-r19c-arm-v7a
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
- [ ] pytorch-linux-xenial-py3.6-clang5-android-ndk-r19c-arm-v8a
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
- [ ] pytorch-linux-xenial-py3.6-clang5-asan
  - docker-pytorch-linux-xenial-py3-clang5-asan • pytorch_linux_xenial_py3_clang5_asan_build • pytorch_linux_xenial_py3_clang5_asan_test1 • pytorch_linux_xenial_py3_clang5_asan_test2
  - #60889 @driazati
- [ ] pytorch-linux-xenial-py3.6-clang5-mobile
  - docker-pytorch-linux-xenial-py3-clang5-asan • pytorch_linux_xenial_py3_clang5_mobile_build
- [ ] pytorch-linux-xenial-py3.6-clang5-mobile-code-analysis
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_mobile_code_analysis
- [ ] pytorch-linux-xenial-py3.6-clang5-mobile-custom-dynamic
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_mobile_custom_build_dynamic
- [ ] pytorch-linux-xenial-py3.6-clang5-mobile-custom-static
  - docker-pytorch-linux-xenial-py3-clang5-android-ndk-r19c • pytorch_linux_xenial_py3_clang5_mobile_custom_build_static
- [ ] pytorch-linux-xenial-py3.6-clang7-onnx
  - docker-pytorch-linux-xenial-py3-clang7-onnx • pytorch_linux_xenial_py3_clang7_onnx_build • pytorch_linux_xenial_py3_clang7_onnx_ort_test1 • pytorch_linux_xenial_py3_clang7_onnx_ort_test2
  - #60889 @driazati
- [ ] pytorch-cpp-doc
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_cpp_doc_build
- [x] pytorch-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_python_doc_build
  - #57371 @zhouzhuojie
- [ ] pytorch-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_python_doc_build • pytorch_python_doc_push
- [ ] pytorch-doc-test
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_doc_test
- [x] pytorch-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_linux_xenial_py3_6_gcc5_4_test
  - #56280 @seemethere
- [x] pytorch-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_linux_xenial_py3_6_gcc5_4_build • pytorch_linux_xenial_py3_6_gcc5_4_jit_legacy_test
  - https://github.com/pytorch/pytorch/pull/65106 @seemethere
- [ ] pytorch-linux-xenial-py3.6-gcc7
  - docker-pytorch-linux-xenial-py3.6-gcc7 • pytorch_linux_xenial_py3_6_gcc7_build • pytorch_linux_xenial_py3_6_gcc7_test
  - #60889 @driazati
- [ ] pytorch-parallelnative-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_parallelnative_linux_xenial_py3_6_gcc5_4_build • pytorch_parallelnative_linux_xenial_py3_6_gcc5_4_test
  - #60889 @driazati
- [ ] pytorch-paralleltbb-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_paralleltbb_linux_xenial_py3_6_gcc5_4_build • pytorch_paralleltbb_linux_xenial_py3_6_gcc5_4_test
  - #60889 @driazati
- [ ] pytorch-pure_torch-linux-xenial-py3.6-gcc5.4
  - docker-pytorch-linux-xenial-py3.6-gcc5.4 • pytorch_pure_torch_linux_xenial_py3_6_gcc5_4_build
  - #60889 @driazati
- [ ] pytorch-vulkan-linux-bionic-py3.6-clang9
  - docker-pytorch-linux-bionic-py3.6-clang9 • pytorch_vulkan_linux_bionic_py3_6_clang9_build • pytorch_vulkan_linux_bionic_py3_6_clang9_test
  - #60889 @driazati
- [ ] pytorch-xla-linux-bionic-py3.6-clang9
  - docker-pytorch-linux-bionic-py3.6-clang9 • pytorch_xla_linux_bionic_py3_6_clang9_build • pytorch_xla_linux_bionic_py3_6_clang9_test
  - #60889 @driazati
- [x] pytorch-linux-bionic-cuda10.2-cudnn7-py3.9-gcc7
  - docker-pytorch-linux-bionic-cuda10.2-cudnn7-py3.9-gcc7 • pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_build • pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_test1 • pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_test2
  - #60204 @samestep
- [x] pytorch-libtorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_libtorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build
  - #61774 @janeyx99
- [x] pytorch-libtorch-linux-xenial-cuda11.1-cudnn8-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda11.1-cudnn8-py3-gcc7 • pytorch_libtorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_build
  - #61774 @janeyx99
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test1 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2
  - #56494 @seemethere
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_jit_legacy_test
  - #61055 @samestep
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_multigpu_test
  - #60221 @samestep
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_nogpu_NO_AVX_test
  - #61055 @samestep
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_nogpu_NO_AVX2_test
  - #61055 @samestep
- [x] pytorch-linux-xenial-cuda10.2-cudnn7-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7 • pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build • pytorch_linux_xenial_cuda10_2_cudnn7_py3_slow_test
  - #61055 @samestep
- [x] pytorch-linux-xenial-cuda11.1-cudnn8-py3.6-gcc7
  - docker-pytorch-linux-xenial-cuda11.1-cudnn8-py3-gcc7 • pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_build • pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1 • pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test2
  - #60196 @samestep
- [ ] pytorch-macos-10.13-py3.7
  - pytorch_macos_10_13_py3_build • pytorch_macos_10_13_py3_test • pytorch_macos_10_13_py3_lite_interpreter_build_test
- [ ] pytorch-macos-10.15-py3.8
  - pytorch_macos_10_15_py3_build
  - #57474 @driazati
- [ ] pytorch-windows-vs2019-py36-cpu
  - pytorch_windows_vs2019_py36_cpu_build • pytorch_windows_vs2019_py36_cpu_test1 • pytorch_windows_vs2019_py36_cpu_test2
- [ ] pytorch-windows-vs2019-py36-cuda10.1
  - pytorch_windows_vs2019_py36_cuda10.1_build • pytorch_windows_vs2019_py36_cuda10.1_test1 • pytorch_windows_vs2019_py36_cuda10.1_test2
- [ ] pytorch-windows-vs2019-py36-cuda10.1-on-cpu
  - pytorch_windows_vs2019_py36_cuda10.1_build • pytorch_windows_vs2019_py36_cuda10.1_on_cpu_test1
- [ ] pytorch-windows-vs2019-py36-cuda11.1
  - pytorch_windows_vs2019_py36_cuda11.1_build • pytorch_windows_vs2019_py36_cuda11.1_test1 • pytorch_windows_vs2019_py36_cuda11.1_test2

----

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
suggestion: can we rename all the `py3` jobs with actual sub version of python?
So far I can only parse that out from the logs (in circle) and apparently
* macos_10_13_py3 is actually py3.7
* macos_10_15_py3 is actually py3.8
* *_linux_xenial_py3* without a sub version are all running py3.6

**Comment by samestep** [comment]
@walterddr would you like me to edit the checklist so that instead of just showing an abbreviated version of the Circle job name, it instead shows the Circle job name on the left, and on the right it shows what GHA job name we're replacing it with?

**Comment by driazati** [comment]
> samestep can you please suggest how to proceed with above task

@harishsdev this issue is to track something that we’re doing internally and isn’t really suitable for contributions, but check out the list [here](https://github.com/pytorch/pytorch/contribute) for a list of issues that need help

**Comment by malfet** [comment]
>  can you please suggest how to proceed with above task

@harishsdev thank you for your interest in improving PyTorch. If you have a contribution in mind please do not hesitate to submit a PR for it. Unless you are already familiar with codebase, I would advice you to start by looking at one of the issues marked as [good first time issues](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by samestep** [comment]
> suggestion: can we rename all the `py3` jobs with actual sub version of python?

- https://github.com/pytorch/pytorch/pull/57474/files#r627713647

**Comment by samestep** [comment]
> * `*_linux_xenial_py3*` without a sub version are all running py3.6

@walterddr Is this true for the `_linux_xenial_cuda*_*_cudnn*_py3_*` jobs as well?

**Comment by seemethere** [comment]
Added a tracking issue for sharding: https://github.com/pytorch/pytorch/issues/59401

**Comment by imaginary-person** [comment]
Enabling GHA runners for `pytorch-linux-bionic-py3.8-gcc9-coverage` in #56992.

**Comment by imaginary-person** [comment]
Hello, what do errors such as this one mean? - `RuntimeWarning: Duplicate test case test_abs_angle_complex_to_float_cpu_complex128 in suite TestUnaryUfuncsCPU called from test_unary_ufuncs`?

Thanks!

**Comment by ezyang** [comment]
^- @janeyx99

**Comment by janeyx99** [comment]
> Hello, what do errors such as this one mean? - `RuntimeWarning: Duplicate test case test_abs_angle_complex_to_float_cpu_complex128 in suite TestUnaryUfuncsCPU called from test_unary_ufuncs`?
> 
> Thanks!

This happens when the same test case (in this case TestUnaryUfuncsCPU.test_abs_angle_complex_to_float_cpu_complex128) is reported to have run more than once during CI. This warning occurs when we process our test reports and find duplicates when trying to separate test cases by their test modules, suites, and test case names. We typically expect each test case to only be run once per CI run, though there are some exceptions (for example with distributed tests) that we account for [here](https://github.com/pytorch/pytorch/blob/d3ae3e07aa736d52ff62630d506a15ce8025dcb1/tools/print_test_stats.py#L632).

**Comment by suo** [comment]
Looks like GHA infra failure: https://github.com/pytorch/pytorch/runs/3499529304

**Comment by suo** [comment]
A number of issues with windows build logging (reference example https://github.com/pytorch/pytorch/pull/63918/checks?check_run_id=3424926066)
1. Logs start at the beginning. Failures are always at the bottom. Can we start at the bottom?
2. Logs are truncated at some point. Since failures are always at the bottom, this eliminates any information about the job failure from the main web UI. Can we truncate the beginning instead of end (basically run `tail` instead of `head` on the log)?
3. (nit) the message that tells me to download the full log at the bottom contains a gear symbol that doesn't exist on the web page.
4. (serious) when I download the raw log with "view raw logs"—*this log is truncated as well*. This is a serious issue as it eliminates the signal entirely from any easily accessible place. I can download all artifacts, unzip, and root around, but this is a faintly ridiculous thing to have to do to see my build failures.

**Comment by suo** [comment]
Seems to be a GHA infra failure: https://github.com/pytorch/pytorch/runs/3507620758

**Comment by malfet** [comment]
@suo, please use https://github.com/pytorch/pytorch/issues/61604 to report migration issues, this one is to track migration progress (will copy your 3 comments to that issue and delete them here)

We should probably review the checkboxes, especially ones that are marked done but associated with the open issues

**Comment by seemethere** [comment]
https://github.com/pytorch/pytorch/pull/65728 should remove the need to explicitly remove docker configurations if / when we remove their dependent jobs

**Comment by seemethere** [comment]
This should already mostly be done, removing the need for the umbrella issue, closing...
