### ISSUE TITLE
JIT Script Meta-Issue

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#6008]
This issue tracks the sub-tasks that we need to do to make progress on the JIT script frontend and related code.

- [x] Add expand nodes to point-wise operators generated by @script #6011 (@apaszke)
- [x] Implement derivatives for all point-wise operaters #6012 (@bddppq)
- [x] TorchScript import/export using the ONNX protobuf format #6013 (@lantiga)
- [x] Add torch.jit.const to allow for more features in script mode. #6024 (@zdevito)
- [x] Handling of 'void' returns #6064 (@apaszke)
- [ ] Develop a strategy for writing leak tests for pytorch #6010 (@goldsborough)
- [x] Switch autograd::Function's apply to pass tensors by value using rvalue references, and make sure all tensor lists get moved into it. #6006
- [ ] Clean up the extra copies that occur in the execution engine and other places #6007
- [x] Change inline resolution order so modules can be defined in arbitrary order #6015
- [x] Support constant-sized tuples in the compiler:
  - Differentiating `tensor.chunk` gives error #6075 
  - `torch.cat` doesn't work #6074 
- [x] Support tuples as inputs/outputs to our methods #6153
- [x] [jit][script] Develop a plan for annotating static types for script methods #6246 
- [x] [JIT][script] Script functions should be callable/inlineable from traced methods #6572
- [x] Implement 'to' on ScriptModules #7354
- [x] Implement `train` on ScriptModules #7396
- [x] Allow passing tuples as arguments to a ScriptModule  #7403
- [x] PythonOp may introduce requires_grad #7438

Low priority:
- [x] @ op not supported #6049
- [x] Allow passing in Python numbers as arguments #6073 
- [x] Support shape inference of ops with integral constant arguments #6139

**Comment by vfdev-5** [comment]
> Implement 'to' on ScriptModules #7354

Can a minimal fix be just the adding of `to` into the whitelist ?
https://github.com/pytorch/pytorch/blob/656b565a0f53d9f24547b060bd27aa67ebb89b88/torch/jit/__init__.py#L1262-L1270

**Comment by vfdev-5** [comment]
@zdevito can I send a PR with simple adding of `to` into the list and test ?

**Comment by zdevito** [comment]
sure!

**Comment by eellison** [comment]
Since this is an old-issue and all but two issues of it have been closed I'm going to close this. Re-open if you think it is still relevant. Remaining two issues:

https://github.com/pytorch/pytorch/issues/6007
https://github.com/pytorch/pytorch/issues/6010
