### ISSUE TITLE
Improvement to CUDA mem leak check

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#60182]
In #60023, we stop running CUDA mem leak check on PRs to reduce TTS. This has immediate effect on CI. However there are several follow ups we can improve upon:
- [ ] Honor explicit annotation to run CUDAMemoryLeakCheck on test method, (see: #59805)
- [ ] Support optional GITHUB CI label to enable check on per test method (Currently we support running it via ci/master label, but it also launches a whole bunch of extra CI jobs)
  - [ ] document it [here](https://github.com/pytorch/pytorch/wiki/Writing-tests-in-PyTorch-1.9)! 
- [ ] Further drive down CI cost by only run CUDAMemoryLeakCheck on the newest CUDA version for master CI

Additionally,
- [ ] Investigate if we can run CUDAMemoryLeakCheck on a per TestCase class by default (see: #59808)
- [ ] Investigate if we can skip gc.collect() during CUDAMemoryLeakCheck (see: #59804)

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
If we do add another flag to the test suite let's be sure to document it here: https://github.com/pytorch/pytorch/wiki/Writing-tests-in-PyTorch-1.9

**Comment by ZainRizvi** [comment]
Closing since test parallelism has significantly limited what CUDA memory leak checks are possible
