### ISSUE TITLE
Reductions Tracking Issue

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#61417]
# Reductions Tracking Issue
This issue is for tracking and organizing tasks related to reduction operators.

_Note that some of the tasks below need further discussion before we decide to commit to them._

## API
Reduction operators should follow the Python Array API Standard including performing appropriate broadcasting and type promotion. They should be compatible with NumPy where possible. And they should support reducing over multiple dimensions and the out parameter.

**Support reducing over multiple dimensions**
- [ ] https://github.com/pytorch/pytorch/issues/56586
- [ ] https://github.com/pytorch/pytorch/issues/53900

**Python Array API Standard**
- [ ] https://github.com/pytorch/pytorch/issues/58745
- [ ] https://github.com/pytorch/pytorch/issues/50342
- [ ] https://github.com/pytorch/pytorch/issues/45833
- [ ] https://github.com/pytorch/pytorch/issues/35529

**NumPy compatibility**
- [ ] https://github.com/pytorch/pytorch/issues/50010
- [ ] https://github.com/pytorch/pytorch/issues/32570
- [ ] https://github.com/pytorch/pytorch/issues/29137
- [ ] https://github.com/pytorch/pytorch/issues/19149

**Allow specifying a range for dimensions to reduce over**
- [ ] https://github.com/pytorch/pytorch/issues/54766
- [ ] https://github.com/pytorch/pytorch/issues/32288

**Scalar and empty tensors**
- [ ] https://github.com/pytorch/pytorch/issues/46999
- [ ] https://github.com/pytorch/pytorch/issues/28380

**Function requests and API extensions**
- [ ] https://github.com/pytorch/pytorch/issues/35641
- [ ] https://github.com/pytorch/pytorch/issues/32998
- [ ] https://github.com/pytorch/pytorch/issues/24041
- [ ] https://github.com/pytorch/pytorch/issues/21987
- [ ] https://github.com/pytorch/pytorch/issues/18904

## Testing
Reduction operators have additional structure than other operators such as dim and keepdim parameters which can be exploited to automate testing of many features. To do so, we can create a ReductionInfo subclass of OpInfo and update `test_reductions.py` to follow the OpInfo pattern. Some example of tests that can be automated are ensuring reduction operators support reducing over multiple dimensions, reducing over nonzero dimensions of empty tensors, and even testing for correctness by providing a reference implementation such as a NumPy equivalent operator.

- [ ] https://github.com/pytorch/pytorch/issues/49746
- [ ] https://github.com/pytorch/pytorch/issues/59550
- [ ] https://github.com/pytorch/pytorch/issues/59415
- [ ] https://github.com/pytorch/pytorch/issues/53704

## Bugs

- [ ] https://github.com/pytorch/pytorch/issues/56132
- [ ] https://github.com/pytorch/pytorch/issues/50382
- [ ] https://github.com/pytorch/pytorch/issues/46225
- [ ] https://github.com/pytorch/pytorch/issues/28993
- [ ] https://github.com/pytorch/pytorch/issues/23159

## Performance

- [ ] https://github.com/pytorch/pytorch/issues/51509
- [ ] https://github.com/pytorch/pytorch/issues/51450
- [ ] https://github.com/pytorch/pytorch/issues/40570
- [ ] https://github.com/pytorch/pytorch/issues/31837
- [ ] https://github.com/pytorch/pytorch/issues/16617

## Miscellaneous 

- [ ] https://github.com/pytorch/pytorch/issues/56764
- [ ] https://github.com/pytorch/pytorch/issues/53095
- [ ] https://github.com/pytorch/pytorch/issues/41793
- [ ] https://github.com/pytorch/pytorch/issues/32097
- [ ] https://github.com/pytorch/pytorch/issues/29758
- [ ] https://github.com/pytorch/pytorch/issues/27312
- [ ] https://github.com/pytorch/pytorch/issues/25775
