### ISSUE TITLE
`make_tensor` tracking issue

### ISSUE THREAD

**Issue by krshrimali** [pytorch/pytorch#61758]
This issue tracks progress and features related to `make_tensor`. This is in the direction of exposing it to the users, and hence a tracker to invite discussions/inputs as well as document progress.

## Features Tracker

* [ ] Fix inputs `low/high` given: don't clamp to default values when given valid values. (being pursued in #61108)
* [ ] Investigate tensor generation strategy. (being pursued in #61108)
* [ ] Generic `exclude_values` and `include_values` for tensor generation.
* [ ] Add `include_percent` like argument to populate the output with given percent of `include_values` from the 3rd task.
* [ ] Add `include_lhs` (default True) and `include_rhs` (default False) to the function.
* [ ] Document `make_tensor`

## Description

`make_tensor` is planned (and expected) to go public to the user API in coming releases. The idea behind `make_tensor` is to allow generation of tensors with random (currently: uniformly distributed) values for given `dtype` and `device`. Keeping the user's requirements in mind as well as the extensive use of `make_tensor` in the PyTorch test suite, this issue is supposed to document the progress as well as invite discussions on the features listed above.

cc: @mruberry @pmeier

**Comment by anjali411** [comment]
@krshrimali @mruberry do we plan to include this in 1.10 release?

**Comment by pmeier** [comment]
@anjali411 Yes, this is the tentatively plan.
