### ISSUE TITLE
C10 Tracking Issue

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6325]
Coding:
- [ ] Modularize ATen cmakes, so we can start pulling small parts (e.g., the CUDA allocator) into Caffe2 without grabbing all of ATen. https://github.com/pytorch/pytorch/pull/6188 @ezyang
- [ ] Create a shared header-only library for PyTorch and Caffe2, to put things like ArrayRef, optional (and SmallVector, when it exists)

Prototyping:
- [x] Benchmark core overheads of vtable/hashtable/multi dispatch @zdevito  https://github.com/zdevito/pytorch/pull/24/files (conclusion: hash table overhead is negligible for our use case)
- [X] Class design for operator library @smessmer https://fb.quip.com/cMmnAnDCVBGK
- [ ] Design for the dispatcher @smessmer
- [ ] Benchmark caching allocator in Caffe2 to see what the overhead is @ajtulloch 
- [ ] Decouple Caffe2 from protobuf implementation @dzhulgakov 
- [X] Prototype the operator library class design @ezyang (going to Caffe2Backend) https://github.com/ezyang/pytorch/

Specification:
- [ ] Go through each design point on "Library Interface" and close high level design decisions on all of them. (These are: Naming granularity, Operator inputs/arguments, Language bindings, Broadcasting, Scalars v. 0-dim, Size zero tensors, Sparse, Mixed device operators, Autograd hooks, Gradient definitions)

**Workstream: Caffe2 to templateless tensor representation.** Given the design we are going for in C10, the delta from Caffe2's Tensor to C10 Tensor is much greater than ATen's Tensor to C10 Tensor (C10's outward facing API is basically the same as ATen's). So we need to do some refactoring to reimplement Caffe2's Tensor to be implemented on top of C10 tensor. @ezyang has assigned himself to this but this might be an appropriate thing for someone on the Caffe2 side to look at.
- [ ] Create a C10 static library, include this from Caffe2 library
- [ ] Put in C10 tensor class design into this library.
- [ ] Reimplement Caffe2's Tensor class in terms of the C10 tensor class. We have two choices: (1) codemode all of Caffe2 to do the new Tensor type or (2) have a backwards compatible wrapper that preserves the template wrapper. **One key piece of leverage** is that we will use **virtual dispatch in the implementation classes** to bootstrap various methods which would need to be done with the multiple dispatcher, but we don't have a multiple dispatcher yet.

**Comment by thuyen** [comment]
@ezyang Can we update this? ETA for c10?

**Comment by ezyang** [comment]
This is all done!
