### ISSUE TITLE
Migrate `gcc5` and `xla` CircleCI workflows to GHA

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#64026]
## Context

Those jobs utilize optional rebase-on-latest-trunk optional logic, which is executed after docker hash selection, which causes hard to debug failures, like this one: https://app.circleci.com/pipelines/github/pytorch/pytorch/370441/workflows/a846ca71-bf8c-47b2-821e-4f3cf97b5527/jobs/15628095

For more details about how its currently done for the job, see 
https://github.com/pytorch/pytorch/blob/fbe7133b5842a55589e097c8b045ceb08cb346b2/.circleci/verbatim-sources/commands.yml#L109

## Tasks (from @seemethere)
- [ ] Migrate dependent jobs of `pytorch_linux_xenial_py3_6_gcc5_4_build`
  - [x] `pytorch_cpp_doc_build`: https://github.com/pytorch/pytorch/pull/64044
  - [x] `pytorch_doc_test`: https://github.com/pytorch/pytorch/pull/64201
  - [x] `pytorch_linux_backward_compatibility_check_test`: https://github.com/pytorch/pytorch/pull/64204
  - [ ] `pytorch_doc_push`
- [ ] Migrate `xla` workflows https://github.com/pytorch/pytorch/pull/64218
- [ ] Remove both `gcc5` and `xla` workflows from `.circleci/config.yml`
  - [ ] Removing `doc_test`, `backwards_compat`: https://github.com/pytorch/pytorch/pull/64222

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Migrating XLA here: https://github.com/pytorch/pytorch/pull/64218

**Comment by seemethere** [comment]
So I actually just realized this but XLA is just a testing configuration on top of our clang9 builds, I've updated #64218 to migrate all of our clang9 builds outside of vulkan (including xla)

**Comment by malfet** [comment]
Done, closing
