### ISSUE TITLE
[Meta] CI infra flakiness tracker and status update

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#64390]
# Meta thread of tracking CI infra flakiness

If you believe you see CI infra flakiness (not caused by the PRs), please help surface some of the string pattern that **Dr.CI comments** reports. Here's an incomplete list of we believe that the underlying CI infra has issues:

Tracking issues:

- [ ] `rm: cannot remove sccache.log`
  - [x] PR merged. https://github.com/pytorch/pytorch/pull/64388 
- [ ] `github checkout left dirty`
  - [ ] Issue created: https://github.com/pytorch/pytorch/issues/63613
- [ ] `github checkout submodule failed`
  -  [x] PR merged. https://github.com/pytorch/pytorch/pull/64120
  -  [x] Dr.CI flaky keywords added 
- [ ] `cannot cd` or `Permission denied`
  - [ ] Issue created: https://github.com/pytorch/pytorch/issues/64217
- [x] `CUDA installation failed` on windows
  - [x] PR merged for CircleCI. https://github.com/pytorch/builder/pull/832 
  - [x] Issue created for GHA. https://github.com/pytorch/test-infra/issues/101 

<details>
<summary>
Dr.CI comments query pattern
</summary>

```
WITH pr_errors AS (
    SELECT
        pr_url,
        MAX(ds) AS ds,
        MAX(CASE WHEN new_comment_body LIKE '%git repository checkout dirty%' THEN 1 ELSE 0 END)
            AS infra_git_checkout_dirty,
        MAX(CASE WHEN new_comment_body LIKE '%<sup>Checkout PyTorch</sup>%' THEN 1 ELSE 0 END)
            AS infra_git_checkout_flaky,
        MAX(CASE WHEN new_comment_body LIKE '%rm: cannot remove%' THEN 1 ELSE 0 END)
            AS infra_rm_error,
        MAX(CASE WHEN new_comment_body LIKE '% Permission denied%' THEN 1 ELSE 0 END)
            AS infra_permission_denied,
        MAX(CASE WHEN new_comment_body LIKE '%cd: can''t cd%' THEN 1 ELSE 0 END)
            AS infra_cd_error,
        MAX(CASE WHEN new_comment_body LIKE '%CUDA installation failed%' THEN 1 ELSE 0 END)
            AS infra_cuda_install_error,
        MAX(CASE WHEN new_comment_body LIKE '%Lint /%' THEN 1 ELSE 0 END) AS lint,
        MAX(
            CASE
                WHEN new_comment_body LIKE '%pr/pytorch-linux-bionic-rocm4.2-py3.6%' THEN 1
                ELSE 0
            END
        ) AS rocm

    FROM scuba_opensource_dr_ci_comments
    WHERE
        ds > '2021-06-01'
        AND new_comment_body NOT LIKE '%Looks good so far! There are no failures yet.%'
        AND new_comment_body NOT LIKE '%was recently pushed. Waiting for builds...%'
    GROUP BY
        1
    ORDER BY
        2 DESC
)

SELECT
    ds,
    SUM(infra_git_checkout_dirty) AS infra_git_checkout_dirty,
    SUM(infra_git_checkout_flaky) AS infra_git_checkout_flaky,
    SUM(infra_rm_error) AS infra_rm_error,
    SUM(infra_permission_denied) AS infra_permission_denied,
    SUM(infra_cd_error) AS infra_cd_error,
    SUM(infra_cuda_install_error) AS infra_cuda_install_error,
    SUM(lint) AS lint,
    SUM(rocm) AS rocm
FROM pr_errors
GROUP BY
    1
ORDER BY
    1 DESC
```
</details>

----

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Closing, redundant with CI Stability tracker. @janeyx99 to link

**Comment by janeyx99** [comment]
^ Stability tracker can be found https://github.com/pytorch/pytorch/issues/65439
