### ISSUE TITLE
Dr. CI Issue/Feature Tracker

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#65485]
This issue will track the ongoing problems and feature requests we have for Dr. CI. Please add relevant details and links when you add to this issue. 

## Externalizing Dr. CI
We plan on externalizing Dr. CI functionality, starting with the comment part. Note that there are two main parts to the comment:
- [x] Helpful links
   - HUD PR view link
   - Docs build links
   - Help/Feedback/OH link 
- [x] Failure classifications
   - Header tells you # failures, # pending
   - Unknown failures
   - Upstream failures
   - Flaky failures

## Feature Requests from before
- [ ] Have Dr. CI detect errors in annotations as well

cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Examples: 
- Windows failure classified as flaky, but was a real breakage https://github.com/pytorch/pytorch/pull/65376#issuecomment-923348489
- Distributed failure was broken on master, but was not classified as known failure: https://fburl.com/i0kx72lw (you'll have to figure out which Dr. CI comment version on that PR is the right one)

**Comment by janeyx99** [comment]
Completed as of 5/12:

Fixed issues:
- [x] Windows failure classified as flaky, but was a real breakage https://github.com/pytorch/pytorch/pull/65376#issuecomment-923348489 -- Fixed by @seemethere: deleted old rule that marked build extension errors as flaky. https://www.internalfb.com/intern/opensource/dr_ci/rule/679759222915658/
- [x] 9/24/21: Removed outdated test rules with no recent runs with patterns: 
    ```FAIL: test_bitwise_type, TestONNXRuntime_opset7::test_vgg FAILED, RuntimeError: test_quantized_nn_mods failed! Received signal: SIGSEGV, AssertionError: 1024 not less than or equal to 1e-05 : __main__.TestAutogradDeviceTypeCUDA.test_logdet_1x1_cuda, FAIL: test_EmbeddingBag_per_sample_weights_and_no_offsets_cuda, FAIL: test_EmbeddingBag_per_sample_weights_and_no_offsets_cuda, FAIL: test_DistributedDataParallel_SyncBatchNorm_Diff_Input_Sizes_Running_Value (__main__.TestDistBackend), ERROR: test_tracing_multiple_methods (__main__.TestScript), FAIL: test_proper_exit (__main__.TestDataLoader), FAIL: test_triangular_solve, ERROR collecting test session, ERROR: test_proper_exit (__main__.TestDataLoader)```
- [x] 9/24/21: Removed retry functionality from all rules for test cases

Current issues -- deprioritizing as it hasn't mattered in a while:
- Distributed failure was broken on master, but was not classified as known failure: https://fburl.com/i0kx72lw (you'll have to figure out which Dr. CI comment version on that PR is the right one)

Feature requests (rolled up into externalizing Dr. CI)
- Have Dr. CI detect error messages in Actions Annotations and retry workflows based on those
- @seemethere: I wish there was an easy way to give it the log link and then dr. ci would tell you [which rule] it matched.

**Comment by ZainRizvi** [comment]
This seems to be done
