### ISSUE TITLE
Miniconda3 installation fails for Windows if previously installed (and in use)

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#65579]
## 🐛 Bug

Been noticing Miniconda3 installation issues on our Windows GHA runners, I believe this might be related to processes still being atttached to the `Miniconda3` directory when attempting to do the following lines:

https://github.com/pytorch/pytorch/blob/d07b2cb4ec10a056b9808af5907345af125f7d6e/.jenkins/pytorch/win-test-helpers/installation-helpers/install_miniconda3.bat#L7-L9

<details>
<summary> Full logs </summary>

Link: https://github.com/pytorch/pytorch/runs/3691401383

```
IF EXIST C:\Jenkins\Miniconda3 (rd /s /q C:\Jenkins\Miniconda3  )  
 curl --retry 3 -k repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe --output C:\actions-runner\_work\pytorch\pytorch\pytorch-1267024631\build\win_tmp\Miniconda3-latest-Windows-x86_64.exe  
 C:\actions-runner\_work\pytorch\pytorch\pytorch-1267024631\build\win_tmp\Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /AddToPath=0 /D=C:\Jenkins\Miniconda3 
) 
C:\Jenkins\Miniconda3\DLLs\libffi-7.dll - Access is denied.
C:\Jenkins\Miniconda3\DLLs\pyexpat.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\select.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\unicodedata.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_asyncio.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_bz2.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_ctypes.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_decimal.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_hashlib.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_lzma.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_multiprocessing.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_overlapped.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_queue.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_socket.pyd - Access is denied.
C:\Jenkins\Miniconda3\DLLs\_ssl.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\llvmlite\binding\llvmlite.dll - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\mkl\_mklinit.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\mkl\_py_mkl_service.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\core\runtime\_nrt_python.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\core\typeconv\_typeconv.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\cuda\cudadrv\_extras.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\EXPERI~1\jitclass\_box.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\mviewbuf.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\np\ufunc\_internal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\_devicearray.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\_dispatcher.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\_dynfunc.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numba\_helperlib.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\core\_multiarray_tests.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\core\_multiarray_umath.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\fft\_pocketfft_internal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\linalg\lapack_lite.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\linalg\_umath_linalg.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\bit_generator.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\mtrand.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_bounded_integers.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_common.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_generator.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_mt19937.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_pcg64.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_philox.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\numpy\random\_sfc64.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\psutil\_psutil_windows.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\cython_blas.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\cython_lapack.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_decomp_update.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_fblas.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_flapack.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_flinalg.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_matfuncs_sqrtm_triu.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\linalg\_solve_toeplitz.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_flow.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_matching.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_min_spanning_tree.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_reordering.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_shortest_path.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_tools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\csgraph\_traversal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\_csparsetools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\sparse\_sparsetools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\special\specfun.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\special\_comb.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\special\_ellip_harm_2.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\special\_ufuncs.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\special\_ufuncs_cxx.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\scipy\_lib\_ccallback_c.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\win32\pywintypes38.dll - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\win32\win32api.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\win32\_win32sysloader.pyd - Access is denied.
C:\Jenkins\Miniconda3\Lib\SITE-P~1\yaml\_yaml.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\1033\ifcore_msg.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\1033\irc_msg.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\libcrypto-1_1-x64.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\libifcoremd.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\libiomp5md.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\libmmd.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\libssl-1_1-x64.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\mkl_avx512.1.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\mkl_core.1.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\mkl_intel_thread.1.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\mkl_rt.1.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\mkl_vml_avx512.1.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\pythoncom38.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\svml_dispmd.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\tbbmalloc.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\uv.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\yaml.dll - Access is denied.
C:\Jenkins\Miniconda3\Library\bin\zlib.dll - Access is denied.
C:\Jenkins\Miniconda3\msvcp140.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ICC_RT~1.0-H\Library\bin\1033\ifcore_msg.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ICC_RT~1.0-H\Library\bin\1033\irc_msg.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ICC_RT~1.0-H\Library\bin\libifcoremd.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ICC_RT~1.0-H\Library\bin\libmmd.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ICC_RT~1.0-H\Library\bin\svml_dispmd.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\INTEL-~1.0-H\Library\bin\libiomp5md.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\LIBUV-~1.0-H\Library\bin\uv.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\LLVMLI~1.0-P\Lib\SITE-P~1\llvmlite\binding\llvmlite.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-20~1.0-H\Library\bin\mkl_avx512.1.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-20~1.0-H\Library\bin\mkl_core.1.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-20~1.0-H\Library\bin\mkl_intel_thread.1.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-20~1.0-H\Library\bin\mkl_rt.1.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-20~1.0-H\Library\bin\mkl_vml_avx512.1.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-SE~1.0-P\Lib\SITE-P~1\mkl\_mklinit.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\MKL-SE~1.0-P\Lib\SITE-P~1\mkl\_py_mkl_service.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\core\runtime\_nrt_python.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\core\typeconv\_typeconv.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\cuda\cudadrv\_extras.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\EXPERI~1\jitclass\_box.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\mviewbuf.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\np\ufunc\_internal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\_devicearray.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\_dispatcher.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\_dynfunc.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMBA-~1.1-P\Lib\SITE-P~1\numba\_helperlib.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\core\_multiarray_tests.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\core\_multiarray_umath.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\fft\_pocketfft_internal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\linalg\lapack_lite.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\linalg\_umath_linalg.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\bit_generator.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\mtrand.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_bounded_integers.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_common.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_generator.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_mt19937.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_pcg64.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_philox.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\NUMPY-~2.3-P\Lib\SITE-P~1\numpy\random\_sfc64.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\OPENSS~2.1L-\Library\bin\libcrypto-1_1-x64.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\OPENSS~2.1L-\Library\bin\libssl-1_1-x64.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\libffi-7.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\pyexpat.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\select.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\unicodedata.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_asyncio.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_bz2.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_decimal.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_hashlib.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_lzma.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_multiprocessing.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_overlapped.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_queue.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_socket.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\DLLs\_ssl.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\python.exe - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\python3.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYTHON~1.11-\python38.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYWIN3~2\Lib\SITE-P~1\win32\pywintypes38.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYWIN3~2\Lib\SITE-P~1\win32\win32api.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYWIN3~2\Lib\SITE-P~1\win32\_win32sysloader.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYWIN3~2\Library\bin\pythoncom38.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\PYYAML~1.1-P\Lib\SITE-P~1\yaml\_yaml.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\cython_blas.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\cython_lapack.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_decomp_update.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_fblas.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_flapack.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_flinalg.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_matfuncs_sqrtm_triu.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\linalg\_solve_toeplitz.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_flow.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_matching.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_min_spanning_tree.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_reordering.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_shortest_path.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_tools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\csgraph\_traversal.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\_csparsetools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\sparse\_sparsetools.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\special\specfun.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\special\_comb.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\special\_ellip_harm_2.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\special\_ufuncs.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\special\_ufuncs_cxx.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\SCIPY-~1.2-P\Lib\SITE-P~1\scipy\_lib\_ccallback_c.cp38-win_amd64.pyd - Access is denied.
C:\Jenkins\Miniconda3\pkgs\TBB-20~1.3-H\Library\bin\tbbmalloc.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\VS2015~1.290\msvcp140.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\VS2015~1.290\vcruntime140.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\YAML-0~1.5-H\Library\bin\yaml.dll - Access is denied.
C:\Jenkins\Miniconda3\pkgs\ZLIB-1~1.11-\Library\bin\zlib.dll - Access is denied.
C:\Jenkins\Miniconda3\python.exe - Access is denied.
C:\Jenkins\Miniconda3\python3.dll - Access is denied.
C:\Jenkins\Miniconda3\python38.dll - Access is denied.
C:\Jenkins\Miniconda3\vcruntime140.dll - Access is denied.
```

</details>

Basically when attempting to do the `rd` call it's getting an error that fails out the rest of the job.

Currently Windows builds are dependent on this Miniconda3 directory being clean since we do a `python setup.py install`, but I suggest we move the windows builds to do the same `bdist_wheel` setup that we do in our linux builds to mitigate the need to pull directly from the `Miniconda3` directory altogether.

https://github.com/pytorch/pytorch/blob/d07b2cb4ec10a056b9808af5907345af125f7d6e/.jenkins/pytorch/win-test-helpers/build_pytorch.bat#L123-L135

# Tasks

- [ ] Move windows to use bdist_wheel instead of pulling artifacts directly from the miniconda install 
  - [ ] https://github.com/pytorch/pytorch/pull/65587
- [ ] Don't install miniconda3 if already installed
  - [ ] https://github.com/pytorch/pytorch/pull/65587
- [ ] Move miniconda3 installation to AMI

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
In the mean time I'm going to be adding a Dr. CI rule for this particular error with 

> `'conda' is not recognized as an internal or external command`

Link to Dr. CI rule: https://www.internalfb.com/intern/opensource/dr_ci/rule/4870195389661483/

**Comment by seemethere** [comment]
Created https://github.com/pytorch/pytorch/pull/65587 to move windows builds to use `bdist_wheel` instead of `python setup.py install`

**Comment by seemethere** [comment]
This is resolved by ephemeral runners, closing.
