### ISSUE TITLE
PyTorch CI TTS Tracker

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#68543]
One of PyTorch Dev Infra's goals is to maintain acceptable time-to-signal for PyTorch PR CI. This is an investment on better developer experience for all who contribute to PyTorch. In this tracker, we will track tasks that we can do to cut down TTS without impacting test coverage.

### Decrease checkout time
- [ ] do not checkout submodules for some of the workflows (which should speed it up 10x)
- [ ] Automate stale branch deletion (more branches = more checkout time)
- [ ] Set fetch-depth to not 0 https://github.com/pytorch/pytorch-canary/issues/58 
- [ ] Somehow cache submodules/repo across the runs

### Shard More Jobs
- [x] https://github.com/pytorch/pytorch/issues/72368

### Do More Research
- [ ] Look through revert data and see if there are jobs that could be removed from PRs without inducing more reverts

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Completed as of 2/28
- [x] #68796
- [x] https://github.com/pytorch/pytorch/issues/72371
- [x] ASAN tests #68261
- [x] MacOS tests #68260

**Comment by ZainRizvi** [comment]
Closing tracker since we aren't using it
