### ISSUE TITLE
Tracker: Jiterator improvements

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#69463]
Jiterator TODOs:

- [x] Support float16 and bfloat16 (can be tested by jiterating i0) #70157
- [x] Support complex64 and complex128 (can be tested by jiterating tanh backward or sgn) #71577
- [x] Support scalar inputs (can be testing by jiterating maximum for integer inputs) #69861
- [x] Caching mechanism to be able to reuse compiled kernels in the different processes (e.g. on multiple runs of the same script)
- [ ] if more popular and perf sensitive operations are moved to jiterator, we can invest in kernel improvements, e.g. faster float <-> low precision conversion needed for amp, faster broadcast addition etc. 
- [x] support for functors that have state. Currently we are calling functions, thus cannot support functors that require runtime state (as opposed to the constants that can be hardcoded at compile time), such as `threshold` or addition/subtraction with `alpha`

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by mruberry** [comment]
cc @zasdfgbnm -- I heard you might be looking into supporting complex jit inputs and computation?

**Comment by zasdfgbnm** [comment]
Yes, I had a conversation with @csarofeen about making `complex.h` standalone (don't include other pytorch headers)

**Comment by ngimel** [comment]
@zasdfgbnm this would also require switching to libcudacxx, like in #66469?

**Comment by ezyang** [comment]
A suggestion for another improvement: at least internally at FB, which should be able to collect telemetry about how popular particular variants of kernels are. It would be nice to somehow work this into the "jiterate or no jiterate" decision in a way that makes it easier for people to see (e.g., maintaining a list of "here is what we think should be jiterated next"). 

For bonus points, figure out how to make this an opt in telemetry system for open source users.
