### ISSUE TITLE
Rerun Red on Trunk

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#76708]
Our trunk health is red more than we like. The redness is sometimes due to “bad” commits that introduce broken functionality and sometimes due to flaky tests and other times due to infrastructure flakiness. This task will be attempting to stamp out infrastructure flakiness with the power of retries! On the high level, for every red X on the HUD, we would like to retry them just in case they’re flaky.

However, there are some constraints for when we would like to retry a workflow job:
- We want to be able to retry only a subset of the workflow jobs. This is because some of our runners are more available than others and retrying everything will strain our queuing times. 
- Whether we retry should be customizable based on which step failed. For example, if the test step failed, we would not want to retry as the error is most likely a flaky test issue or a legitimate failure.
- This bullet may be a little redundant, but we would like to be able to customize the above items overtime. In other words, we want to gradually allow this retry functionality on more jobs when we have more machines, OR we decide that there are more steps we want to exclude. This will allow us to have a rollout or rollback plan.

**Goal**: A workflow retry functionality that will retry failed jobs on trunk depending on specified conditions.

**Resources**:
- GitHub Actions triggers: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows 
- GH CLI tools for rerunning jobs: https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs 

**Milestones**:
- [ ] Write functionality to return what jobs to rerun for a given commit
- [ ] Use the functionality in a GHA to rerun Lint jobs and Linux CPU jobs
- [ ] Expand the functionality to other jobs

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Did we decide not to do this?

**Comment by janeyx99** [comment]
Closing as this is not in our roadmap

**Comment by janeyx99** [comment]
We can do this, but we would need to allow this feature for PRs as well. cc @malfet
