### ISSUE TITLE
Tracker: Slow gradcheck failures possibly indicating incorrect gradients

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#80411]
### 🐛 Describe the bug

For a very long time, most tests are being [skipped](https://ossci-raw-job-status.s3.amazonaws.com/log/7032407678) by slow gradcheck:
At least the following are failing in slow gradcheck (There are probably a lot more, but we can't see those right now because the test is timing out): 

- [ ] test_fn_fwgrad_bwgrad___rmod___cuda_float64 (non-differentiable points encountered when sample inputs are large)
- [ ] test_fn_fwgrad_bwgrad__masked_prod_cuda_complex128
- [ ] test_fn_fwgrad_bwgrad__masked_prod_cuda_float64
- [ ] test_fn_fwgrad_bwgrad_cat_cuda_complex128
- [ ] test_fn_fwgrad_bwgrad_cholesky_inverse_cuda_complex128
- [ ] test_fn_fwgrad_bwgrad_copysign_cuda_float64
- [ ] test_fn_fwgrad_bwgrad_fft_*
- [ ] test_fn_fwgrad_bwgrad_float_power_cuda_complex128
- [ ] test_fn_fwgrad_bwgrad_float_power_cuda_float64
- [ ] test_fn_fwgrad_bwgrad_fmod_cuda_float64 (probably same issue as `__fmod__`)
- [ ] test_fn_fwgrad_bwgrad_linalg_householder_product_cuda_complex128
- [ ] test_fn_fwgrad_bwgrad_linalg_lu_cuda_float64
- [ ] test_fn_fwgrad_bwgrad_linalg_lu_factor_ex_cuda_float64
- [ ] test_fn_fwgrad_bwgrad_linalg_matrix_power_cuda_complex128

See https://ossci-raw-job-status.s3.amazonaws.com/log/7034710626

The failures don't necessarily mean the formulas are wrong, `__rmod__` (and possibly also `fmod`) for example only fails when sample inputs are large enough so that the perturbation of eps will cross a point of non-differentiability with high probability.

### Versions

main

**Comment by Lezcano** [comment]
For the linalg operations, I bet that 99% of those come from testing the gradients on a matrix that's close to being singular rather than the formulas being wrong.

**Comment by redwrasse** [comment]
Came to this issue from a code reference and following up out of curiosity as to what's left to do here. Do failing tests, slow or not, need to be rewritten to not test near singular matrix inputs?

**Comment by soulitzer** [comment]
> Came to this issue from a code reference and following up out of curiosity as to what's left to do here. Do failing tests, slow or not, need to be rewritten to not test near singular matrix inputs?

Yeah if a specific test is failing because of near-singular matrix inputs, then that should help yes. Though in general, the tests listed here are ones that pass the fast version of gradcheck on the same inputs (likely because the Jacobian computed by autograd only has a few mismatched entries).
