### ISSUE TITLE
[Tracker] AO migration of quantization from `torch.nn` to `torch.ao.nn`

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#81667]
## Motivation

There are several locations under the `torch.nn` that are related to the quantization. In order to reduce the cluttering and "takeover" by the quantization, the nn modules that are relevant are being migrated to `torch.ao`.

### Upcoming deadlines

- [ ] 08/2022: Migration of the code from `torch.nn` to `torch.ao.nn`. At this point both location could be used, while the old location would have `from torch.ao... import ...`
- [ ] 08/2022: Importing from the `torch.nn` would show a deprecation warning
- [ ] PyTorch 1.13: The deprecation warning is shown
- [ ] PyTorch 1.14: The deprecation error is shown
- [ ] PyTorch 1.14+: The `torch.nn` location is cleaned up and not usable anymore.

### Currently under review:

- [ ] `torch.nn.quantized` → `torch.ao.nn.quantized`
  - [ ] [`torch.nn.quantized.functional` → `torch.ao.nn.quantized.functional`](https://github.com/pytorch/pytorch/pull/78712)
  - [ ] [`torch.nn.quantized.modules` → `torch.ao.nn.quantized.modules`](https://github.com/pytorch/pytorch/pull/78713)
  - [ ] [`torch.nn.quantized.dynamic` → `torch.ao.nn.quantized.dynamic`](https://github.com/pytorch/pytorch/pull/78714)
  - [ ] [`torch.nn.quantized._reference` → `torch.ao.nn.quantized._reference`](https://github.com/pytorch/pytorch/pull/78715)
- [ ] [`torch.nn.quantizable` → `torch.ao.nn.quantizable`](https://github.com/pytorch/pytorch/pull/78717)
- [ ] [`torch.nn.qat` → `torch.ao.nn.qat`](https://github.com/pytorch/pytorch/pull/78716)
  - [ ] `torch.nn.qat.modules` → `torch.ao.nn.qat.modules`
  - [ ] `torch.nn.qat.dynamic` → `torch.ao.nn.qat.dynamic`
- [ ] `torch.nn.intrinsic` → `torch.ao.nn.intrinsic`
  - [ ] `torch.nn.intrinsic.modules` → `torch.ao.nn.intrinsic.modules`
  - [ ] `torch.nn.intrinsic.qat` → `torch.ao.nn.intrinsic.qat`
  - [ ] `torch.nn.intrinsic.quantized` → `torch.ao.nn.intrinsic.quantized`
    - [ ] `torch.nn.intrinsic.quantized.modules` → `torch.ao.nn.intrinsic.quantized.modules`
    - [ ] `torch.nn.intrinsic.quantized.dynamic` → `torch.ao.nn.intrinsic.quantized.dynamic`

cc @anjali411 @alban

**Comment by andrewor14** [comment]
@supriyar @vkuzo Should we close this for now, since we're not actively working on this anymore?

**Comment by vkuzo** [comment]
I think keeping it open with low priority makes sense to me.  The work isn't done and it's not ideal to abandon a migration midway.
