### ISSUE TITLE
[Tracking] Operator coverage for symbolic shape tracing

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#82048]
### 🚀 The feature, motivation and pitch

Op Coverage mostly taken from https://github.com/pytorch/pytorch/blob/master/test/test_proxy_tensor.py#L387

Decompositions Needed (i.e. we need to write a Primtorch decomposition or meta function)

- [ ] `aten._to_copy.default`
- [ ] `aten.mm.default`
- [ ] `aten.slice.Tensor`

SymInt overloads needed (i.e. we need to support calling it with SymInts as an argument)
- [ ] `aten.new_empty`
- [ ] `aten.reshape` (tricky since it's CompositeImplicitAutograd?)

cc: @ezyang @Krovatkin 

cc @ezyang
