### ISSUE TITLE
[ONNX] Future registration process operators to accommodate `quantized::` ops and more

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#83787]
### TODO

- [x] Create the registry #84382 
- [x] Discover all quantized operators #83919 
    - #84496 
- [x] Implement the decorator
    - https://github.com/pytorch/pytorch/pull/84709
    - #84448 
- [x] #84553 
    - https://github.com/pytorch/pytorch/pull/84728
    - https://github.com/pytorch/pytorch/pull/84776
    - https://github.com/pytorch/pytorch/pull/85491
- [x] Clean up
    - https://github.com/pytorch/pytorch/pull/85165
    - https://github.com/pytorch/pytorch/pull/85349
- [x] Op dispatcher from the registry https://github.com/pytorch/pytorch/issues/82046
    - https://github.com/pytorch/pytorch/pull/85350
    - https://github.com/pytorch/pytorch/pull/85486
    - https://github.com/pytorch/pytorch/pull/85487
    - https://github.com/pytorch/pytorch/pull/85488
- [ ] Add an attribute to TupleConstruct nodes. Verify that it works.
- [ ] Implement the quantization handler
    - https://github.com/pytorch/pytorch/issues/87508
    - https://github.com/pytorch/pytorch/pull/85312
- [ ] Verify registered symbolics against aten schema

-----

Currently to support `quantized::` ops in onnx, we need to (1) create a symbolic in the `Quantized` class (2) unpack quantized args with a function call. In some cases we need to unfuse an operator like `add_relu`. To support `aten::` ops that takes quantized inputs, we need to use the quantized_args decorator. In special `aten::` cases, we also need to specify the requantization scale and zero points.

We would like to specify as little information about the op as possible when adding support for quantized args and infer as much info as possible.

Since there is a quantized tensor representation in TorchScript, we should be able to leverage that and avoid the need for explicitly specifying which arguments are quantized.

The proposed decorator will (1) register a symbolic function to a specified name and (2) apply specified transformations that alter the inputs

```python
# Assuming the quantized::symbolic_a has signature 
# g, x: _C.Value, y: _C.Value, arg1: bool, op_scale, op_zero_point

@onnx_symbolic("quantized::symbolic_a", opset=10, decorate=[quantized_args_handler])
@symbolic_helper.parse_args("v", "v", "b")
def symbolic_a(g: _C.Graph, x: _C.Value, y: _C.Value, arg1: bool) -> _C.Value:
    ...

```

where `default_quantization_handler` turns any quantized input into de-quantized values, and re-quantizes the output with `op_scale` and `op_zero_point`.

This design allows for (1) easy discovery by simply searching for the op name (quantized::symbolic_a) to find the corresponding code (2) flexible code organization because the function does not need to live in a particular symbolic_opset file (3) function overloading by registering the same symbolic multiple times, or registering different symbolics that are design to handle the same aten op variations (4) flexible input transformation by providing a chain of decorators (5) easier code gen. 

The proposed decorator also does not interfere with the current symbolic discovery process to allow for a gradual transition.

When we decide to use the register decorator for all ops, we will have

```python
@onnx_symbolic("quantized::symbolic_a", opset=10, decorate=[quantized_op_handler])
@onnx_symbolic("aten::symbolic_a", opset=10)
@symbolic_helper.parse_args("v", "v", "b")
def symbolic_a(g: _C.Graph, x: _C.Value, y: _C.Value, arg1: bool) -> _C.Value:
    ...
```

When we need to specify zero_point and scale to an aten op, we can supply those to a handler e.g. `quantized_args`.

```python
@onnx_symbolic("aten::symbolic_b", opset=10, decorate=[symbolic_helper.quantized_args(True, True, scale=1/128, zero_point=0)])
@symbolic_helper.parse_args("v", "v", "b")
def symbolic_b(g: _C.Graph, x: _C.Value, y: _C.Value, arg1: bool) -> _C.Value:
    ...
```

or more simply to a handler that will recognize quantized inputs e.g. `quantized_aten_handler`

```python
@onnx_symbolic("aten::symbolic_b", opset=10, decorate=[quantized_aten_handler(scale=1/128, zero_point=0)])
@symbolic_helper.parse_args("v", "v", "b")
def symbolic_b(g: _C.Graph, x: _C.Value, y: _C.Value, arg1: bool) -> _C.Value:
    ...
```

to shorten what we need to type (if preferred), we can alias many things and do

```python
register = functools.partial(onnx_symbolic, opset=10)

@register("aten::symbolic_a", decorate=[quantized_aten(1/128, 0)])
@symbolic_helper.parse_args("v", "v", "b")
def symbolic_b(g: _C.Graph, x: _C.Value, y: _C.Value, arg1: bool) -> _C.Value:
    ...
```

### Alternatives

torch.fx

**Comment by BowenBao** [comment]
A very great proposal! I really like how simple and flexible it is to write and manage symbolic functions. One important question, how do you envision the calling of symbolic function from other symbolic functions?

**Comment by justinchuby** [comment]
> A very great proposal! I really like how simple and flexible it is to write and manage symbolic functions. One important question, how do you envision the calling of symbolic function from other symbolic functions?

Yes. The calling experience should stay the same with this proposal.

**Comment by justinchuby** [comment]
## Design notes

1. How should a function be retrieved? What should the dispatch interface be?
2. Should we support overloads?
