### ISSUE TITLE
[JIT][meta] Hybrid front-end operator-level robustness testing master task

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8530]
Tests: https://github.com/pytorch/pytorch/pull/8145

Results: https://gist.github.com/zdevito/6d62435b68edf027a98ed6c9d96ef3df

Unsupported ops:
Master https://github.com/pytorch/pytorch/issues/8527

(Note these issues are closed because they were taking up a lot of space on the issues page)
- [x] 10 tests [8507 Unsupported op descriptor index_fill](https://github.com/pytorch/pytorch/issues/8507)
- [x] 10 tests [8497 Unsupported op descriptor index-{2,3,4}](https://github.com/pytorch/pytorch/issues/8497)
- [x] 6 tests [8522 Unsupported op descriptor scatter](https://github.com/pytorch/pytorch/issues/8522)
- [x] 6 tests [8521 Unsupported op descriptor scatter_add](https://github.com/pytorch/pytorch/issues/8521)
- [x] 6 tests [8511 Unsupported op descriptor masked_fill](https://github.com/pytorch/pytorch/issues/8511)
- [x] 6 tests [8506 Unsupported op descriptor index_copy](https://github.com/pytorch/pytorch/issues/8506)
- [x] 6 tests [8505 Unsupported op descriptor index_add](https://github.com/pytorch/pytorch/issues/8505)
- [x] 4 tests [8512 Unsupported op descriptor masked_scatter](https://github.com/pytorch/pytorch/issues/8512)

Issues:

- [x] 21 tests [8499 Accumulation operator shape propagation broadcast failures ](https://github.com/pytorch/pytorch/issues/8499)
- [x] 15 tests [8393 Can't allocate zero gradients for a value without a type](https://github.com/pytorch/pytorch/issues/8393)
- [x] 17 tests [8516 Better handle IntList arguments for ops like permute](https://github.com/pytorch/pytorch/issues/8516)
- [x] 11 tests [8498 Expand number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)](https://github.com/pytorch/pytorch/issues/8498)
- [x] 10 tests [8513 elementwise min/max attempting to create a Scalar from a 3 dim Tensor](https://github.com/pytorch/pytorch/issues/8513)]
- [x] 5 tests [8526 expected ident but found 'where' here](https://github.com/pytorch/pytorch/issues/8526)
- [x] 5 tests [8538 Missing check for non-method functions in operator-level tests](https://github.com/pytorch/pytorch/issues/8538)
- [x] 5 tests [8528 Generalize variadic output logic for min, max and split](https://github.com/pytorch/pytorch/issues/8528)
- [x] 4 tests [8502 Don't support None in the script](https://github.com/pytorch/pytorch/issues/8502)
- [x] 4 tests [8500 addc{div,mul} type issues - scalar accumulation](https://github.com/pytorch/pytorch/issues/8500)
- [x] 4 tests [8518 Don't support empty tuple literal](https://github.com/pytorch/pytorch/issues/8518)
- [x] 3 tests [8525 split: expected a value of type Tensor for argument 'split_size' but found (LongTensor[], LongTensor[], LongTensor[])](https://github.com/pytorch/pytorch/issues/8525)
- [x] 3 tests [8501 Don't support differentiation of aten::addmm in certain cases](https://github.com/pytorch/pytorch/issues/8501)
- [x] 2 tests [8520 Don't support torch.Size() in the script](https://github.com/pytorch/pytorch/issues/8520)
- [x] 2 tests (probably test issue) [8514 Elementwise min/max scalar tests fail with tuple comparison](https://github.com/pytorch/pytorch/issues/8514)
- [x] 2 tests [8515 Don't support inf in the script](https://github.com/pytorch/pytorch/issues/8515)
- [x] 1 test (test probably needs restructuring) [8510 Inverse test is singular](https://github.com/pytorch/pytorch/issues/8510)
- [x] 1 test (test probably needs restructuring) [8504 gesv operator test needs re-examining](https://github.com/pytorch/pytorch/issues/8504)

Related Issues:
- [x] [7504 literals don't interact well with gpu tensors](https://github.com/pytorch/pytorch/issues/7504)

**Comment by driazati** [comment]
All issues have been addressed
