### ISSUE TITLE
Einsum Optimization Tracker

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#88002]
There are many things one can do to improve einsum (in terms of perf and usability!) so this issue seeks to track them all. 

## The Multi-Contractions Case
As of torch 1.13, `torch.einsum` automatically uses opt-einsum to optimize the contraction path for when there are 3+ tensors to contract and opt-einsum is installed. As of now, section 1 of https://github.com/pytorch/pytorch/issues/60295 has been completed. 
Tasks remaining include to:
- [ ] Achieve numpy compatibility by adding optimize as an torch.einsum API kwarg (our previous attempt was blocked by failing JIT tracing https://github.com/pytorch/pytorch/pull/85908)
- [ ] [P0] Submit a fix to https://github.com/dgasmith/opt_einsum to set `torch.backends.opt_einsum.enabled = False` to avoid recomputing the path when opt_einsum calls torch.einsum as a backend.
- [ ] Test out cuQuantum perf as an opt_einsum replacement

## The Single Contraction Case
The path to faster single contractions includes:
- [ ] Benchmarking einsum with torch.inductor, experimenting with replacing bmm with mul -> sum for discontiguous tensors.
- [ ] Testing out cuTensor perf (to see if there are significant improvements since Yaroslav's last benchmarks in #57121.)

## Additional Context
See previous relevant issues https://github.com/pytorch/pytorch/issues/60295 and https://github.com/pytorch/pytorch/issues/57121 for context.
