### ISSUE TITLE
[threaded pg] tracking MultithreadedTestCase/threaded pg related issues

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#89941]
We are working on making threaded pg and MultithreadedTestCase be robust and ready for testing usage. This is the mega thread that tracks relevant issues when using threaded pg for testing (feel free to edit the list to add more):

- [x] Cannot use MultithreadedTestCase to create sub pgs inside (i.e. new_group not working in MultithreadedTestCase) https://github.com/pytorch/pytorch/pull/91649
- [x] MultithreadedTestCase hangs when running certain test cases https://github.com/pytorch/pytorch/issues/90504
- [x] MultithreadedTestCase should call TestCase.setUp() in perThreadSetUp (i.e. ensure seed in sync between threads)
- [x] MultithreadedTestCase should have a way to share certain thread local states https://github.com/pytorch/pytorch/pull/91650
- [x] If the execution thread crashes, it should notify all the remaining threads to shutdown immediately instead of waiting. https://github.com/pytorch/pytorch/issues/90504

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by XilunWu** [comment]
#90504

**Comment by XilunWu** [comment]
threaded PG's RNG issue on test: #90585 90585

**Comment by wanchaol** [comment]
https://github.com/pytorch/pytorch/pull/91649 and https://github.com/pytorch/pytorch/pull/91650 fixes the remaining issue, closing this.
