### ISSUE TITLE
[CUDA][CUDA 12] CUDA 12 Support Tracking Issue

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#91122]
CUDA 12 has been released, but we've identified several blocking issues (some code/API compatibility, some API functionality) that need to be addressed before a PyTorch + CUDA 12 build/environment could be considered usable by mainstream users. We're creating this issue to hopefully avoid duplicating work in identifying and resolving issues.

Required code changes for build-breaking changes:

- [x] Drop compute capability < 5.0 (#91213)
- [x] Wrap `cudaGraphInstantiate` as the API has changed (#91118)
- [x] Skip building `cudaProfilerInitialize` (#91118, #95582)
- [x] Support `const` `CUDASparse` descriptors (#90765, #90897, #91050)

Known API functionality issues:

- [x] `cudaSetDevice` is currently eagerly creating a CUDA context when called, which is a significant departure from previous behavior. This potentially creates many unused contexts that waste GPU memory (especially in DDP workloads), and would either require framework or CUDA toolkit code changes to resolve. (#91191, #91219, #94864)

Nightly CUDA 12.1 builds are now available for the adventurous:
@ https://pytorch.org/get-started/locally/
e.g.,
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```

CC @ptrblck @crcrpar @IvanYashchuk @xwang233 @Aidyn-A @Fuzzkatt @syed-ahmed @puririshi98 @ngimel @malfet 

Please feel free to update this issue as new items are discovered/resolved.

cc @ngimel

**Comment by yan12125** [comment]
> Support `const` `CUDASparse` descriptors

Already addressed in https://github.com/pytorch/pytorch/pull/90765 and https://github.com/pytorch/pytorch/pull/90897? Also, https://github.com/pytorch/pytorch/pull/91050 further refines changes related to cuSparse.

**Comment by johnnynunez** [comment]
When will it be in nightly?

**Comment by ptrblck** [comment]
After the 11.8 with sm_90 builds were enabled and made public, we will continue with the CUDA12 binary bringup.
At this moment, a few PRs are still open and reviewed such as this one: https://github.com/pytorch/builder/pull/1263

**Comment by johnnynunez** [comment]
> After the 11.8 with sm_90 builds were enabled and made public, we will continue with the CUDA12 binary bringup.
> At this moment, a few PRs are still open and reviewed such as this one: [pytorch/builder#1263](https://github.com/pytorch/builder/pull/1263)

Thanks!

**Comment by xkszltl** [comment]
This part would need to be fixed as well:
- https://github.com/pytorch/pytorch/blob/bc51ee4ed7d514a20ce36090e9c090e301e9f3e5/caffe2/contrib/prof/cuda_profile_ops.cc#L61

**Comment by xkszltl** [comment]
CC @jianyuh who's working on similar PR https://github.com/pytorch/pytorch/pull/91118

**Comment by jianyuh** [comment]
> This part would need to be fixed as well:
> 
> * https://github.com/pytorch/pytorch/blob/bc51ee4ed7d514a20ce36090e9c090e301e9f3e5/caffe2/contrib/prof/cuda_profile_ops.cc#L61

Something like https://github.com/pytorch/pytorch/pull/95582 ?

**Comment by johnnynunez** [comment]
Cudnn 8.8 is out as well compatible with cuda 12.0

**Comment by johnnynunez** [comment]
CUDA 12.1 is out

**Comment by ddelange** [comment]
> CUDA 12.1 is out: https://nvidia.github.io/cuda-python/release/12.1.0-notes.html

fwiw, there is no cuDNN for CUDA 12.1 [yet](https://gitlab.com/nvidia/container-images/cuda/-/issues/186#note_1308231033)

**Comment by PiotrDabkowski** [comment]
Hey, is there some ETA for the Nightly PyTorch build with CUDA 12?

**Comment by johnnynunez** [comment]
> > CUDA 12.1 is out: https://nvidia.github.io/cuda-python/release/12.1.0-notes.html
> 
> fwiw, there is no cuDNN for CUDA 12.1 [yet](https://gitlab.com/nvidia/container-images/cuda/-/issues/186#note_1308231033)

8.8.1

**Comment by sterlind** [comment]
FYI, I successfully compiled PyTorch with CUDA 12.1, on WSL2 (Ubuntu 22.04), and it seems to work! I subjected myself to this so I could get access to CUDA profiling, since that's only supported on WSL as of CUDA 12.0. I'll outline my procedure for any other lost souls embarking on this Sisyphean task:

1. Install CUDA 12.1 and cuDNN 8.8.1 using the `.deb` archives provided by Nvidia (*not* using pip or conda.) Make sure to follow post-installation instructions and that nvcc (from `/usr/local/cuda/bin`) is in $PATH.
2. Clone [magma](https://bitbucket.org/icl/magma/src/master/README), build and install it. My make.inc was `BACKEND = cuda\nFORT = false\nGPU_TARGET = sm_89`.
3. Install clang, libmkl-dev, libomp-dev, others via apt. update-alternatives to select `clang` and `clang++` for `cc` and `c++` respectively (I had trouble building with conda due to sandboxing fails, which is why I resorted to this.)
4. `python setup.py develop`, install as root (ugh, I know, again, desperate.)
5. Abort install and debug if logs warn of CUPTI being disabled for Kineto. I saw this before I stopped using conda, because of some strange interaction between conda's cuda package and cmake's FindCUDAPackage implementation.
6. Make sure GPU driver reported by `nvidia-smi` is 525+.
7. On the Windows side, open Nvidia Control Panel, `Developer -> Manage GPU Performance Counters`, select `Allow access` and hit Apply. Monitor should blip black at this point.
8. Now profiling should work:

```bash
sterlind@REDACTED:~$ python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.profiler import profile, ProfilerActivity
>>> with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
...     torch.randn(128, 128).cuda()**2
...
STAGE:2023-03-29 00:29:30 22306:22306 ActivityProfilerController.cpp:311] Completed Stage: Warm Up
tensor([[5.7398e-02, 3.4480e-01, 2.4028e-01,  ..., 2.4325e-01, 1.0869e+00,
         2.0355e+00],
        [8.0108e-02, 2.8249e-01, 6.4294e-01,  ..., 1.3758e-03, 1.2476e+00,
         4.7756e-01],
        [4.2178e+00, 4.7478e-02, 3.0230e+00,  ..., 2.5068e-01, 4.3795e-01,
         2.2346e+00],
        ...,
        [4.6171e-01, 5.8717e-02, 3.7117e+00,  ..., 1.1240e-02, 6.5606e-01,
         3.3799e+00],
        [2.9934e+00, 9.1235e-02, 8.1225e-01,  ..., 1.5539e+00, 3.9602e-02,
         1.7947e-01],
        [1.6940e-02, 3.6519e-02, 1.0624e-01,  ..., 1.1720e-01, 3.0470e-03,
         1.5738e+00]], device='cuda:0')
STAGE:2023-03-29 00:29:37 22306:22306 ActivityProfilerController.cpp:317] Completed Stage: Collection
STAGE:2023-03-29 00:29:37 22306:22306 ActivityProfilerController.cpp:321] Completed Stage: Post Processing
>>> print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
--------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
--------------------------  ------------  ------------  ------------  ------------  ------------  ------------
     cudaStreamIsCapturing        99.03%        6.706s        99.03%        6.706s        6.706s             1
          cudaLaunchKernel         0.67%      45.105ms         0.67%      45.105ms       1.735ms            26
```

I know this is extremely bleeding edge and I'm probably the first person to try this config, but thought I'd let y'all know it works! :)

**Comment by AzharSindhi** [comment]
Any updates?

**Comment by eqy** [comment]
We are currently verifying that the set device issue has been resolved.

**Comment by josephusmv** [comment]
> FYI, I successfully compiled PyTorch with CUDA 12.1, on WSL2 (Ubuntu 22.04), and it seems to work! I subjected myself to this so I could get access to CUDA profiling, since that's only supported on WSL as of CUDA 12.0. I'll outline my procedure for any other lost souls embarking on this Sisyphean task:
> 
>     1. Install CUDA 12.1 and cuDNN 8.8.1 using the `.deb` archives provided by Nvidia (_not_ using pip or conda.) Make sure to follow post-installation instructions and that nvcc (from `/usr/local/cuda/bin`) is in $PATH.
> 
>     2. Clone [magma](https://bitbucket.org/icl/magma/src/master/README), build and install it. My make.inc was `BACKEND = cuda\nFORT = false\nGPU_TARGET = sm_89`.
> 
>     3. Install clang, libmkl-dev, libomp-dev, others via apt. update-alternatives to select `clang` and `clang++` for `cc` and `c++` respectively (I had trouble building with conda due to sandboxing fails, which is why I resorted to this.)
> 
>     4. `python setup.py develop`, install as root (ugh, I know, again, desperate.)
> 
>     5. Abort install and debug if logs warn of CUPTI being disabled for Kineto. I saw this before I stopped using conda, because of some strange interaction between conda's cuda package and cmake's FindCUDAPackage implementation.
> 
>     6. Make sure GPU driver reported by `nvidia-smi` is 525+.
> 
>     7. On the Windows side, open Nvidia Control Panel, `Developer -> Manage GPU Performance Counters`, select `Allow access` and hit Apply. Monitor should blip black at this point.
> 
>     8. Now profiling should work:
> 
> 
> ```shell
> sterlind@REDACTED:~$ python
> Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> from torch.profiler import profile, ProfilerActivity
> >>> with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
> ...     torch.randn(128, 128).cuda()**2
> ...
> STAGE:2023-03-29 00:29:30 22306:22306 ActivityProfilerController.cpp:311] Completed Stage: Warm Up
> tensor([[5.7398e-02, 3.4480e-01, 2.4028e-01,  ..., 2.4325e-01, 1.0869e+00,
>          2.0355e+00],
>         [8.0108e-02, 2.8249e-01, 6.4294e-01,  ..., 1.3758e-03, 1.2476e+00,
>          4.7756e-01],
>         [4.2178e+00, 4.7478e-02, 3.0230e+00,  ..., 2.5068e-01, 4.3795e-01,
>          2.2346e+00],
>         ...,
>         [4.6171e-01, 5.8717e-02, 3.7117e+00,  ..., 1.1240e-02, 6.5606e-01,
>          3.3799e+00],
>         [2.9934e+00, 9.1235e-02, 8.1225e-01,  ..., 1.5539e+00, 3.9602e-02,
>          1.7947e-01],
>         [1.6940e-02, 3.6519e-02, 1.0624e-01,  ..., 1.1720e-01, 3.0470e-03,
>          1.5738e+00]], device='cuda:0')
> STAGE:2023-03-29 00:29:37 22306:22306 ActivityProfilerController.cpp:317] Completed Stage: Collection
> STAGE:2023-03-29 00:29:37 22306:22306 ActivityProfilerController.cpp:321] Completed Stage: Post Processing
> >>> print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
> --------------------------  ------------  ------------  ------------  ------------  ------------  ------------
>                       Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
> --------------------------  ------------  ------------  ------------  ------------  ------------  ------------
>      cudaStreamIsCapturing        99.03%        6.706s        99.03%        6.706s        6.706s             1
>           cudaLaunchKernel         0.67%      45.105ms         0.67%      45.105ms       1.735ms            26
> ```
> 
> I know this is extremely bleeding edge and I'm probably the first person to try this config, but thought I'd let y'all know it works! :)

Is this still the only workable solution now? does PyTorch release a official release now? @ptrblck

**Comment by ngimel** [comment]
12.1 nightlies are already built (but we don't run 12.1 CI yet, so some things may not work here or there).

**Comment by fcolecumberri** [comment]
> 12.1 nightlies are already built (but we don't run 12.1 CI yet, so some things may not work here or there).

Sooo... Do you hava an idea about how much time will it take to have a stable build?

**Comment by ddelange** [comment]
there are nightlies:
```
pip install torch~=2.1.0.dev20230524 --extra-index-url=https://download.pytorch.org/whl/nightly/cu121
```

**Comment by jakirkham** [comment]
In terms of Conda packaging, we've added a full CTK suite of packages to conda-forge. There's a breakdown in issue ( https://github.com/conda-forge/staged-recipes/issues/21382 ). Basically everything is in including compilers, libraries, devtools, etc.. Only thing still pending is `nsight-compute` (and a handful of metapackages that depend on it).

We are in the process of rebuilding packages in conda-forge to use CUDA 12. This involves some changes. More background and details in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 ).

There is a PR in conda-forge to rebuild PyTorch for CUDA 12 ( https://github.com/conda-forge/pytorch-cpu-feedstock/pull/171 ). Though am guessing that still will depend on whatever remaining work is needed here and a new release of PyTorch.

Mentioning this here in case it is of some value to devs and if there are questions on how to use these.

**Comment by ptrblck** [comment]
The nighty binaries are already shipping with CUDA 12.1 (https://pytorch.org/get-started/locally/), which is also the target for the next PyTorch 2.1.0 release.
@eqy can we close this tracking issue?

**Comment by ddelange** [comment]
Hi @ptrblck 👋 

ref [CUDA Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) do I understand correctly that the torch 2.1.0 wheels will still run fine on e.g. CUDA 11.8 runtimes?

**Comment by jakirkham** [comment]
Is this statement from the OP still true?

> At the current time, we consider CUDA 12 support to be a _work in progress_ and do not recommend PyTorch users to upgrade.

**Comment by eqy** [comment]
> Is this statement from the OP still true?
> 
> > At the current time, we consider CUDA 12 support to be a _work in progress_ and do not recommend PyTorch users to upgrade.

While the amount of testing has increased, I believe the official recommendation to upgrade would come when CUDA 12+ is the default on the getting started landing page @ https://pytorch.org/get-started/locally/

**Comment by ptrblck** [comment]
> do I understand correctly that the torch 2.1.0 wheels will still run fine on e.g. CUDA 11.8 runtimes?

I assume you are referring to the CUDA 11.8 driver?
If so, then no and you would need to update your NVIDIA driver to be able to execute the wheels built and shipping with CUDA 12.x.
The link mentions *forward compatibility* for data center GPUs, which needs an additional setup.

**Comment by maxhgerlach** [comment]
@ptrblck, it looks like NVIDIA's PyTorch container has shipped with a CUDA 12.x build for a while now. Are there reservations against using that version? 

https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-06.html#rel-23-06

**Comment by mmccarty** [comment]
> The nighty binaries are already shipping with CUDA 12.1 (https://pytorch.org/get-started/locally/), which is also the target for the next PyTorch 2.1.0 release.
@ptrblck - Is there a public tracker for the PyTorch 2.1.0 release?

**Comment by ptrblck** [comment]
> Are there reservations against using that version?

@maxhgerlach No, we don't have CUDA 12 - specific issues or open action items, which is why I suggested closing this issue.
However, I refer to @eqy in case he wants to wait for the stable 2.1.0+cu121 release before closing it.

@mmccarty I'm not aware a 2.1.0 tracking issue was already created.

**Comment by mmccarty** [comment]
> However, I refer to @eqy in case he wants to wait for the stable 2.1.0+cu121 release before closing it.

Does anyone know the timeline for this release?

**Comment by vadimkantorov** [comment]
If CUDA 12.1 is supported for nightly (or if CUDA 12.0 supported for stable) - even if only for pip installation, it would be great to add this installation command on https://pytorch.org and mention CUDA 12 there

**Comment by rshoemake-launch** [comment]
I'm having an issue with the nightly builds install for the cuda12.1 support:

Requirement already satisfied: mpmath>=0.19 in /home/rshoemake/.local/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

**Comment by sanjibnarzary** [comment]
If anyone is interested you can test with my build (python 3.8 and 3.10). I have build the torch 2.2 form source which works on CUDA 12.2. Here is the link [Torch for CUDA 12.2](http://get.alayaran.com/wheels/) or
```
pip3 install torch --index-url http://get.alayaran.com/wheels/whl/cu122
```

**Comment by sdake** [comment]
> Torch for CUDA 12.2

Hi @sanjibnarzary . Would you mind sharing your build implementation? I have spent a little bit of time, perhaps 3-5 hours, (trying) to build pytorch in a container with 12.2. I could of course use your work for development. We have to build all our software in prod from our environments.

Here are a couple takes:

[LibPytorch built within docker, then results copied out](https://github.com/artificialwisdomai/origin/pull/102/files)

[PyTorch built within docker, then results copied out](https://github.com/artificialwisdomai/origin/pull/99/files)

Please forgive the break in protocol... I have three questions, and they are unrelated to this issue.

- Can Ninja be used as a build generator for PyTorch (or Libtorch for that matter - I struggle here).
- Is there any way to avoid using `setup.py` and instead rely completely on `cmake` or `ninja` to build Pytorch? If you take a look at the docker file in this comment, you will see I specify variables with types, which is safer.

Eg:
```
ENV T_TORCH_CUDA_ARCH_LIST="STRING=8.0;8.6"
ENV T_MAX_JOBS="INTEGER=30"
ENV T_USE_CUDNN="BOOL=TRUE"
ENV T_USE_CUSPARSELT="BOOL=TRUE"
ENV T_USE_FBGEMM="BOOL=TRUE"
ENV T_USE_KINETO="BOOL=TRUE"
ENV T_USE_NUMPY="BOOL=TRUE"
ENV T_USE_NNPACK="BOOL=TRUE"
ENV T_USE_QNNPACK="BOOL=TRUE"
ENV T_USE_SYSTEM_NCCL="BOOL=FALSE"
ENV T_USE_NCCL="BOOL=FALSE"
ENV T_BUILD_CAFFE2="BOOL=TRUE"
ENV T_BUILD_CAFFE2_OPS="BOOL=TRUE"
ENV T_USE_FLASH_ATTENTION="BOOL=TRUE"
ENV T_BUILD_BINARY="BOOL=TRUE"
ENV T_BLAS="BOOL=TRUE"
ENV T_USE_ZSTD="BOOL=TRUE"
```

I then use these [environment variables](https://github.com/artificialwisdomai/origin/pull/99/files#diff-9b6c262a20e69279dcaf114c89a8e66b31e8d0a7865c3fe59601a54aec266154R130) which work great with `cmake`. Not so much with setup.py.

... My requirements are odd. Its standard BIGCO stuff. ...

Thank you,
-steve

**Comment by bhack** [comment]
With the new `2.1.0` release it seems we are still missing official `12.x` Docker images.

**Comment by eqy** [comment]
Closing this issue for now as the getting started page has been updated. @bhack please open a new issue if the Docker images are still missing.
