### ISSUE TITLE
vmap support for special bessel functions

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91402]
## Tasks
Add vmap support for the following PyTorch operations. That is, each one needs a batching rule.
- [ ] special.bessel_j0
- [ ] special.bessel_y0
- [ ] special.bessel_j1
- [ ] special.modified_bessel_i0
- [ ] special.bessel_y1
- [ ] special.scaled_modified_bessel_k0
- [ ] special.scaled_modified_bessel_k1
- [ ] special.modified_bessel_i1

There might be more `special.*bessel*` operations that behave in the same way that I may have missed.

## Expected behavior
Currently, when one does vmap over them, they raise a warning suggesting the batching rule is not implemented:
```py
import torch
from functorch import vmap
x = torch.randn(32, 2, 3)
y = vmap(torch.special.bessel_j0)(x)
#  UserWarning: There is a performance drop because we have not yet implemented the batching rule
```
We expect to not see a warning

## Read this!

See this note for more context https://github.com/pytorch/pytorch/blob/master/functorch/writing_batching_rules.md

If you're new to developing PyTorch and/or function transforms, we would recommend reading through https://github.com/pytorch/pytorch/wiki/Core-Frontend-Onboarding#unit-8-function-transforms-optional

Should likely be similar to https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/functorch/BatchRulesUnaryOps.cpp, though you'll have to figure out which macros to use.

## Testing

`pytest test/functorch/test_vmap.py -v -k "bessel_j1"` should pass (currently, it is an expected failure). Ditto for everything else.

cc @Chillee @samdow @soumith

**Comment by MDK8888** [comment]
Hey, I would love to work on this!

**Comment by MDK8888** [comment]
Hey, I'd love to work on this!
