### ISSUE TITLE
[0.4.1] master tracking issue

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9280]
[not a comprehensive list yet]

## important
- [x] fix segfault when importing pytorch & sentencepiece (https://github.com/pytorch/pytorch/issues/8358)
- [x] segfault when importing fasttext & pytorch #9129
- [x] align `torch.stft` with librosa signature & behavior (@SsnL, #7883) 
- [ ] warn in dataloader if `IS_WINDOWS && py2.7 && num_workers > 0` (#9232)
- [ ] fix the perf discrepancy of argmax & argmin between numpy and GPU version. (@ailzhang, #8817)
- [ ] Fix windows cuda 8 build (@peterjc123 #9092) 
- [ ] Multiplication of tensor with numpy scalar does not always work #9468
- [x] segfault when calling .grad_fn() (#8774)
<del>- [ ] `.to(a_param)` returns a tensor (#9303)</del>

## wishlist

- [ ] type hints in pycharm #7318
- [ ] Fix font on docs site so it isn't immortalized in the 0.4.1 release... #8391 
- [ ] celu activation https://github.com/pytorch/pytorch/pull/8551
- [ ] check if dense-sparse addition in coalesced case has regression (@SsnL)

## binaries

- [x] get static cuda linking working again {cublas, cufft, curand, cusparse}
- [x] get static cudnn linking working
- [x] get static nccl2 linking working
- [x] get static MKL linking working (if not working)
- [x] add Python 3.7 binaries
- [x] Make CUDA9 the default binary (instead of CUDA8)
- [x] Linux
  - [ ] Build CUDA conda binaries
  - [ ] Build CPU-only conda binaries
  - [ ] Build CUDA wheels
  - [ ] Build CPU wheels
- [x] OSX
  - [ ] Build CUDA conda binaries
  - [ ] Build CPU-only conda binaries
  - [ ] Build CUDA wheels
  - [ ] Build CPU wheels
- [x] Windows
  - [ ] Build CUDA conda binaries
  - [ ] Build CPU-only conda binaries
  - [ ] Build CUDA wheels
  - [ ] Build CPU wheels
-  [x] Stage binaries to `-c soumith`
-  [x] Test on examples/, community repos for regressions

**Comment by t-vi** [comment]
Would #7763 qualify?

**Comment by SsnL** [comment]
I thought that it was fixed?

**Comment by SsnL** [comment]
@t-vi 0.4.1 will contain (almost) all commits in current master. This list is to track the critical fixes not yet implemented on master. :)

**Comment by t-vi** [comment]
Ah thanks!
