### ISSUE TITLE
Tooling Issue Tracking

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#93520]
### Minifier
- [x] [Accuracy minifier](https://github.com/pytorch/pytorch/issues/93715)
- [x] Ensure FX graphs dumped by hooks and `TORCHINDUCTOR_TRACE=1` are runnable in the minifier
- [ ] https://github.com/pytorch/pytorch/issues/93696
- [ ] https://github.com/pytorch/pytorch/issues/93694
- [x] https://github.com/pytorch/pytorch/issues/93673 @williamwen42 
- [x] Cleanup minifier print outs, currently a lot of exceptions are printed @mlazos https://github.com/pytorch/pytorch/pull/87537
- [ ] Ensure minifier runs are sensible in torchbench (check that the output isn't hidden somehwere)

### General UX
- [x] Single debug folder @mlazos https://github.com/pytorch/pytorch/pull/87438
- [ ] Enable debug dump of ir/log/minifier into single folder with one flag when there is an issue @mlazos 
Automatically run minifier with correct mode setting (aot autograd or dynamo) on exception
- [x] https://github.com/pytorch/torchdynamo/issues/1383 @mlazos 
- [x] https://github.com/pytorch/torchdynamo/issues/1376 @mlazos 
- [x] Indicator that dynamo is still running @msaroufim 
- [x] Always have next step for user in error messages
- [ ] Single config for all components (`torch.compile.config`)

### Documentation
- [ ] Stride check example in debug runbook
- [ ] Accuracy minifier example in debug runbook
- [x] FAQ once people have started to try these tools out and we have early feedback @msaroufim 

### Compilation Statistics
- [ ] https://github.com/pytorch/pytorch/issues/93675

### PyTorch Profiler Integration ([main issue](https://github.com/pytorch/pytorch/issues/93717))
- [ ] Fix links missing between CPU and GPU traces (figure out which metadata is required for this)
- [x] Add fused kernel naming to make it clearer which kernels are the results of fusion @mlazos (https://github.com/pytorch/pytorch/pull/88624)
- [ ] Add support in TorchDynamo to handle profiler context (currently they are ignored)
Currently disabled because most backends don't support it
- [ ] Identify additional requirements for integrating with the profiler infra

### Exceptions
- [ ] Fix handling of RAISE_VARARGS to show a nicer error message than Unsupported

### Logging
- [x] [Log steps of compilation](https://github.com/pytorch/pytorch/issues/93674)
- [x] Hooks for logging FX graph to external source
- [x] https://github.com/pytorch/torchdynamo/issues/1462 @mlazos 
- [x] https://github.com/pytorch/torchdynamo/issues/1167 @williamwen42 
- [x] Add logging to AOT and make it interoperate with TorchInductor trace @mlazos 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Any update on this issue? Should we close it?

**Comment by ydwu4** [comment]
Will close it for now due to inactivity but feel free to re-open when necessary.
