### ISSUE TITLE
[Inductor] Task Tracker for CPU Backend Optimization

### ISSUE THREAD

**Issue by jgong5** [pytorch/pytorch#93557]
This issue summarizes all the completed, WIP and planned tasks about (or related to) TorchInductor CPU backend optimization. Note that the list is not fixed and would grow per benchmark result and feedbacks from maintainers and the community.

### Completed

- [x] https://github.com/pytorch/torchdynamo/pull/1452
- [x] https://github.com/pytorch/torchdynamo/pull/1468
- [x] https://github.com/pytorch/torchdynamo/pull/1486, https://github.com/pytorch/pytorch/pull/87037

### WIP
- [x] https://github.com/pytorch/pytorch/issues/93552 (FP32 data type as first stage)
  - [x] https://github.com/pytorch/pytorch/pull/87068
  - [x] https://github.com/pytorch/pytorch/pull/87356
  - [x] https://github.com/pytorch/pytorch/pull/88160
  - [x] https://github.com/pytorch/pytorch/pull/88482
  - [x] https://github.com/pytorch/pytorch/pull/88736
- [x] https://github.com/pytorch/pytorch/issues/93522
- [x] Conv/Linear post-op fusion for inference
  - [x] https://github.com/pytorch/pytorch/pull/87063
  - [x] https://github.com/pytorch/pytorch/pull/87064
  - [x] https://github.com/pytorch/pytorch/pull/87065
  - [x] https://github.com/pytorch/pytorch/pull/87066
- [x] Conv/Linear weight prepack for inference

### Planned (short-term)

- [x] Explicit vectorization support for BF16 data type
- [x] Explicit vectorization support for INT8 data type

### Planned (longer than short-term)
- [ ] Codegen for conv/gemm
- [ ] Autotune
- [ ] clang/llvm integration

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Hi, are all the issues fixed in this issue tracker? Can we close this issue if all are finished or not interesting anymore?

**Comment by jgong5** [comment]
> Hi @jgong5, are the tracked issues fixed? Can we close this issue if so or not interesting anymore?

We have addressed all the short-term tasks and are working on longer term ones. I think we can close this and track longer-term items separately.
