### ISSUE TITLE
Tracker for manually running pytorch/examples 

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#93556]
- [x] imagenet
  - https://github.com/pytorch/torchdynamo/issues/1687 and https://github.com/pytorch/torchdynamo/issues/1701 were filed and fixed.
- [x] word_language_model
  - https://github.com/pytorch/torchdynamo/issues/1712 was filed and fixed
- [ ] time_sequence_prediction
  - https://github.com/pytorch/pytorch/issues/93558 was filed 
- [ ] fast_neural_style
- [ ] mnist
- [ ] mnist_hogwild
- [ ] regression
- [ ] reinforcement_learning
- [ ] siamese_network
- [ ] super_resolution
- [ ] vae
- [ ] dcgan

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
I'll close the issue tracker due to no activity but feel free to re-open if it's still relevant.
