### ISSUE TITLE
PyTorch core test with inductor issue tracker

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93581]
The passing rate is tracked at https://github.com/pytorch/pytorch/issues/93559

* **test_modules.py**
  - [ ] pytorch/pytorch#93584
  - [ ] pytorch/pytorch#93585
  - [x] pytorch/torchdynamo#1782
* **test_nn.py**
  - [x] pytorch/torchdynamo#1783 (@yanboliang)
  - [ ] pytorch/pytorch#93586 (@yanboliang)
  - [x] pytorch/torchdynamo#1785 (@yanboliang)
  - [ ] pytorch/torchdynamo#1786 (@krovatkin)
  - [ ] pytorch/torchdynamo#1787 (@krovatkin)
  - [x] pytorch/torchdynamo#1788
  - [x] pytorch/torchdynamo#1789 (**dup of pytorch/pytorch#93589**)
  - [ ] pytorch/pytorch#93588
  - [ ] pytorch/pytorch#93589 (@bdhirsh )
  - [ ] pytorch/torchdynamo#1792
* **test_torch.py**
  - [x] pytorch/torchdynamo#1793 (@desertfire )
  - [x] pytorch/torchdynamo#1794 (@desertfire )
  - [ ] pytorch/pytorch#93591 (@eellison)
  - [x] pytorch/torchdynamo#1796 (@eellison)
  - [x] pytorch/torchdynamo#1797 (@desertfire )
  - [x] pytorch/torchdynamo#1798 (@Krovatkin)
  - [x] pytorch/torchdynamo#1799 (@Krovatkin )
  - [x] pytorch/torchdynamo#1800 (@Krovatkin )
  - [x] pytorch/torchdynamo#1801 (@Krovatkin )
  - [ ] pytorch/pytorch#93476  (@eellison)
