### ISSUE TITLE
TorchBench + Dynamo TRT

### ISSUE THREAD

**Issue by bitfort** [pytorch/pytorch#93741]
As of today, the current status of TorchDynamo+FX2TRT on supporting models in TorchBench:
1. 27 models could fully run on TRT (except drq, yolov3, hf_Bart) with performance larger than 1x.
2. 21 models could run with poor performance or throw Errors due to fx tracer issue or TRT cuda issue.
3. 4 models are not qualified for inference now. 
- mobilenet_v2_quantized_qat, resnet50_quantized_qat due to quantization
- maml need backward pass
- pytorch_struct no inference mode

Issue list:

- [x]  pytorch_stargan, pytorch_CycleGAN_and_pix2pix, tts_angular, demucs - pytorch/torchdynamo#115 
- [x]  hf_Longformer, pyhpc_isoneutral_mixing, speech_transformer - pytorch/torchdynamo#117
- [x]  hf_T5, hf_GPT2, soft_actor_critic - pytorch/torchdynamo#118
- [ ] pyhpc_turbulent_kinetic_energy, moco - pytorch/torchdynamo#120
- [ ] fastNLP_Bert - pytorch/torchdynamo#121
- [ ] vision_maskrcnn, detectron2_maskrcnn, Super_SloMo, opacus_cifar10, hf_BigBird, pyhpc_equation_of_state - pytorch/torchdynamo#122
- [ ] dlrm - pytorch/torchdynamo#123
- [x] pytorch/torchdynamo#250 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh
