### ISSUE TITLE
TorchInductor missing ops tracker

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93757]
The following ops are using `ir.FallbackKernel` via `make_fallback()` in [lowering.py](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/lowering.py#L894) and appear in benchmarks.  We should rewrite them to use decomps or lowerings.

- [x] pytorch/pytorch#93650
- [ ] aten.grid_sampler_2d_backward (higher priority)
- [ ] aten.upsample_bilinear2d_backward (higher priority)
- [ ] aten._adaptive_avg_pool2d_backward
- [ ] aten.upsample_bicubic2d_backward
- [ ] aten._fused_moving_avg_obs_fq_helper
- [x] aten.upsample_nearest3d (needed for FAIR model)
- [ ] aten.avg_pool3d (needed for FAIR model)
- [x] aten.bucketize (needed for internal model) - not targeting for codegen, do a fallback
- [x] aten.prod (needed for research model) - not targeting for codegen, do a fallback

Might not be possible (in a performant way), but currently use fallbacks:
- [ ] aten.convolution_backward (might need to hold of on this if perf doesn't match)
- [ ] aten._cudnn_rnn (might need to hold of on this if perf doesn't match) - not targeting for codegen, do a fallback
- [ ] aten._cudnn_rnn_backward (might need to hold of on this if perf doesn't match) - not targeting for codegen, do a fallback
- [ ] aten._embedding_bag (may have a template internally) (Attempted with https://github.com/pytorch/pytorch/pull/84235, but it's very hard to make it performant and inductor-friendly) 
- [ ] pytorch/pytorch#93631 not targeting for codegen, do a fallback
- [ ] torchvision.roi_align (need to sort of decomps for domain libs)

Done:
- [x] aten._adaptive_avg_pool2d
- [x] aten.nll_loss_forward ([PR](https://github.com/pytorch/pytorch/pull/78491))
- [x] aten.grid_sampler_2d (could use the version [from here](https://github.com/pytorch/pytorch/issues/34704))
- [x] aten.upsample_bilinear2d https://github.com/pytorch/pytorch/pull/80964
- [x] aten.reflection_pad2d_backward (higher priority)
- [x] aten.native_batch_norm_backward (https://github.com/pytorch/pytorch/pull/81522)
- [x] aten.avg_pool2d_backward
- [x] aten.expand_as
- [x] aten.glu_backward (https://github.com/pytorch/pytorch/pull/78919)
- [x] aten.masked_fill_
- [x] aten.max_pool2d_with_indices_backward
- [x] aten.select_scatter
- [x] aten.upsample_nearest2d_backward
- [x] aten.baddbmm
- [x] aten.log1p
- [x] aten.bernoulli_
- [x] aten.conj_physical
- [x] pytorch/torchdynamo#885
- [x] aten.im2col_backward
- [x] aten.native_group_norm_backward (https://github.com/pytorch/pytorch/pull/84037)
- [x] aten.im2col (https://github.com/pytorch/pytorch/pull/84303)
- [x] aten.binary_cross_entropy_with_logits (needed for internal model)
- [x] aten.upsample_bicubic2d (#1349)
- [x] aten.unfold https://github.com/pytorch/pytorch/pull/85629
- [x] aten.unfold_backward https://github.com/pytorch/pytorch/pull/85629
- [x] aten.col2im https://github.com/pytorch/pytorch/pull/85541
- [x] aten.mse_loss_backward (higher priority)
- [x] aten.softplus (needed for research model)
- [x] aten.softplus_backward (needed for research model)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel
