### ISSUE TITLE
[ONNX] FX exporter 'test_models_onnxruntime.py' tracker

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#96757]
#### List of unsupported call_functions

```
(Draft) Steps to proceed

1. If operator is in [Core ATen IR](https://pytorch.org/docs/master/ir.html).
    then
    2. Implement in ATenlib. Validate w/ exporter.
    else
    3. If operator has decomposition.
        then
        4. Debug exporter why it is not decomposed. Then goto 1.
        else
        5. Decide whether to add decomposition for the op or goto 2.
```  

Top errors in UnsupportedCallFunctions (3635 total):
- [ ] 1696 errors like: aten.new_zeros.default examples:
        :test_googlenet
        :test_mnasnet
        :test_mobilenet
        :test_dcgan_netG
        :test_fcn
        :test_r2plus1d_18_video
        :test_shufflenet_v2_dynamic_axes
        :test_resnet
        :test_shufflenet
        :test_mobilenet_v3
        :test_deeplab
        :test_dcgan_netD
        :test_inception
        :test_ops
        :test_densenet
- [ ] 848 errors like: aten.empty.memory_format examples:
        :test_googlenet
        :test_mnasnet
        :test_mobilenet
        :test_dcgan_netG
        :test_fcn
        :test_r2plus1d_18_video
        :test_shufflenet_v2_dynamic_axes
        :test_resnet
        :test_shufflenet
        :test_mobilenet_v3
        :test_deeplab
        :test_dcgan_netD
        :test_inception
        :test_ops
        :test_densenet
- [ ] 761 errors like: aten.copy_.default examples:
        :test_alexnet
        :test_squeezenet
        :test_googlenet
        :test_mnasnet
        :test_mobilenet
        :test_dcgan_netG
        :test_fcn
        :test_r2plus1d_18_video
        :test_shufflenet_v2_dynamic_axes
        :test_resnet
        :test_shufflenet
        :test_mobilenet_v3
        :test_deeplab
        :test_dcgan_netD
        :test_inception
        :test_densenet
- [ ] 127 errors like: aten.cat.default examples:
        :test_squeezenet
        :test_googlenet
        :test_shufflenet_v2_dynamic_axes
        :test_shufflenet
        :test_deeplab
        :test_inception
        :test_densenet
- [ ] 90 errors like: aten.add_.Tensor examples:
        :test_resnet
        :test_fcn
        :test_r2plus1d_18_video
        :test_deeplab
- [ ] 35 errors like: aten.hardtanh.default examples:
        :test_mobilenet
- [ ] 31 errors like: aten.max_pool2d_with_indices.default examples:
        :test_alexnet
        :test_squeezenet
        :test_googlenet
        :test_fcn
        :test_shufflenet_v2_dynamic_axes
        :test_resnet
        :test_shufflenet
        :test_mnist
        :test_deeplab
        :test_inception
        :test_densenet
- [ ] 19 errors like: aten.mean.dim examples:
        :test_mnasnet
        :test_googlenet
        :test_mobilenet
        :test_r2plus1d_18_video
        :test_shufflenet_v2_dynamic_axes
        :test_resnet
        :test_shufflenet
        :test_mobilenet_v3
        :test_deeplab
        :test_inception
        :test_densenet
- [ ] 15 errors like: aten.avg_pool2d.default examples:
        :test_alexnet
        :test_squeezenet
        :test_inception
        :test_ops
        :test_densenet
- [ ] 12 errors like: aten.index.Tensor examples:
        :test_fcn
        :test_deeplab
- [ ] 1 errors like: aten.squeeze.dim examples:
        :test_ops
