### ISSUE TITLE
Sharded Grad Scaler Issue Tracker

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#98860]
I recently unintentionally discovered that there exists a [sharded_grad_scaler.py](https://github.com/pytorch/pytorch/blob/4584851da5cad7f2e5f9fd5ed2245f3a06f8359e/torch/distributed/fsdp/sharded_grad_scaler.py#L4) which derives a lot from our [amp/grad_scaler.py](https://github.com/pytorch/pytorch/blob/e64ddd1ab9d46cfc921c19269969ffc5cd7d6f6c/torch/cuda/amp/grad_scaler.py#L195).

- [ ] A lot of the duplication seems unnecessary. ShardedGradScaler should reuse/call as much of GradScaler as possible instead copying/pasting. This way, ShardedGradScaler can be automatically enrolled in GradScaler bug fixes/improvements.
- [ ] It is uncertain whether ShardedGradScaler supports all that current GradScaler supports in a consistent way, such as being able to call unscale separate from step like in the grad clipping use case: https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler.unscale_
- [ ] ShardedGradScaler should be documented as a public API once it's ready. It would be good to link to it from the existing GradScaler page.

cc @rohan-varma
